require 'set'
require 'erb'

module Xdrgen::Generators; end

class CsharpGenerator < Xdrgen::Generators::Base
  AST = Xdrgen::AST

  def generate
    constants_container = Set[]
    render_lib
    render_definitions(@top, constants_container)
    render_constants constants_container
  end

  def render_lib
    %w[XdrDataInputStream XdrDataOutputStream].each do |name|
      template = IO.read(__dir__ + "/templates/#{name}.erb")
      result = ERB.new(template).result(binding)
      @output.write("#{name}.cs", result)
    end
  end

  def render_definitions(node, constants_container)
    node.namespaces.each { |n| render_definitions n, constants_container }
    node.definitions.each { |defn| render_definition(defn, constants_container) }
  end

  def render_definition(defn, constants_container)
    case defn
    when AST::Definitions::Struct
      render_element 'public class', defn do |out|
        render_struct defn, out
        render_nested_definitions defn, out
      end
    when AST::Definitions::Enum
      render_element 'public class', defn do |out|
        render_enum defn, out
      end
    when AST::Definitions::Union
      render_element 'public class', defn do |out|
        render_union defn, out
        render_nested_definitions defn, out
      end
    when AST::Definitions::Typedef
      render_element 'public class', defn do |out|
        render_typedef defn, out
      end
    when AST::Definitions::Const
      constants_container.add([defn.name, defn.value])
    end
  end

  def render_nested_definitions(defn, out)
    return unless defn.respond_to? :nested_definitions
    defn.nested_definitions.each do |ndefn|
      case ndefn
      when AST::Definitions::Struct
        out.break
        out.puts "public class #{name ndefn}"
        out.puts '{'
        out.indent do
          render_struct ndefn, out
          render_nested_definitions ndefn, out
        end
        out.puts '}'
      when AST::Definitions::Enum
        out.break
        out.puts "public class #{name ndefn}"
        out.puts '{'
        out.indent do
          render_enum ndefn, out
        end
        out.puts '}'
      when AST::Definitions::Union
        out.break
        out.puts "public class #{name ndefn}"
        out.puts '{'
        out.indent do
          render_union ndefn, out
          render_nested_definitions ndefn, out
        end
        out.puts '}'
      when AST::Definitions::Typedef
        out.break
        out.puts "public class #{name ndefn}"
        out.puts '{'
        out.indent do
          render_typedef ndefn, out
        end
        out.puts '}'
      end
    end
  end

  def render_element(type, element, post_name = '')
    path = element.name.camelize + '.cs'
    name = name_string element.name
    out  = @output.open(path)
    render_top_matter out, element
    render_source_comment out, element
    out.puts "#{type} #{name}"
    out.puts '{'
    out.indent do
      yield out
      out.unbreak
    end
    out.puts '}'
  end

  def render_constants(constants_container)
    return if constants_container.empty?
    out = @output.open("Constants.cs")
    out.puts '// Automatically generated by xdrgen'
    out.puts '// DO NOT EDIT or your changes may be overwritten'
    out.puts
    out.puts "namespace #{@namespace};"
    out.puts
    out.puts 'public static class Constants'
    out.puts '{'
    out.indent do
      constants_container.sort_by { |const_name, _| const_name }.each do |const_name, const_value|
        out.puts "public const int #{const_name} = #{const_value};"
      end
    end
    out.puts '}'
  end

  # ============================================================================
  # Enum rendering
  # ============================================================================

  def render_enum(enum, out)
    enumname = enum.name + 'Enum'

    out.puts "public enum #{enumname}"
    out.puts '{'
    out.indent do
      out.balance_after /,[\s]*/ do
        enum.members.each do |em|
          out.puts "#{em.name} = #{em.value},"
        end
      end
    end
    out.puts '}'
    out.puts
    out.puts "public #{enumname} InnerValue { get; set; }"
    out.puts
    out.puts "public static #{name enum} Create(#{enumname} v)"
    out.puts '{'
    out.indent do
      out.puts "return new #{name enum}"
      out.puts '{'
      out.indent do
        out.puts 'InnerValue = v,'
      end
      out.puts '};'
    end
    out.puts '}'
    out.puts
    out.puts "public static #{name enum} Decode(XdrDataInputStream stream, int maxDepth)"
    out.puts '{'
    out.indent do
      out.puts '// maxDepth is intentionally not checked - enums are leaf types'
      out.puts 'var value = stream.ReadInt();'
      out.puts 'switch (value)'
      out.puts '{'
      out.indent do
        enum.members.each do |em|
          out.puts "case #{em.value}: return Create(#{enumname}.#{em.name});"
        end
        out.puts 'default:'
        out.indent do
          out.puts 'throw new IOException("Unknown enum value: " + value);'
        end
      end
      out.puts '}'
    end
    out.puts '}'
    out.puts
    out.puts "public static #{name enum} Decode(XdrDataInputStream stream)"
    out.puts '{'
    out.indent do
      out.puts "return Decode(stream, XdrDataInputStream.DefaultMaxDepth);"
    end
    out.puts '}'
    out.puts
    out.puts "public static void Encode(XdrDataOutputStream stream, #{name enum} value)"
    out.puts '{'
    out.indent do
      out.puts 'stream.WriteInt((int)value.InnerValue);'
    end
    out.puts '}'
  end

  # ============================================================================
  # Struct rendering
  # ============================================================================

  def render_struct(struct, out)
    struct.members.each do |m|
      out.puts "public #{decl_string(m.declaration)} #{m.name.camelize} { get; set; }"
    end
    out.puts

    out.puts "public static void Encode(XdrDataOutputStream stream, #{name struct} encoded#{name struct})"
    out.puts '{'
    out.indent do
      struct.members.each do |m|
        encode_member "encoded#{name struct}", m, out
      end
    end
    out.puts '}'
    out.puts

    # decode with maxDepth
    out.puts "public static #{name struct} Decode(XdrDataInputStream stream, int maxDepth)"
    out.puts '{'
    out.indent do
      out.puts 'if (maxDepth <= 0)'
      out.indent do
        out.puts 'throw new IOException("Maximum decoding depth reached");'
      end
      out.puts 'maxDepth -= 1;'
      out.puts "var decoded#{name struct} = new #{name struct}();"
      struct.members.each do |m|
        decode_member "decoded#{name struct}", m, out, "maxDepth"
      end
      out.puts "return decoded#{name struct};"
    end
    out.puts '}'
    out.puts

    # decode without maxDepth (convenience)
    out.puts "public static #{name struct} Decode(XdrDataInputStream stream)"
    out.puts '{'
    out.indent do
      out.puts "return Decode(stream, XdrDataInputStream.DefaultMaxDepth);"
    end
    out.puts '}'
  end

  # ============================================================================
  # Typedef rendering
  # ============================================================================

  def render_typedef(typedef, out)
    out.puts "public #{typedef.name.camelize}()"
    out.puts '{'
    out.puts '}'
    out.puts
    out.puts "public #{typedef.name.camelize}(#{decl_string typedef.declaration} value)"
    out.puts '{'
    out.indent do
      out.puts 'InnerValue = value;'
    end
    out.puts '}'
    out.puts
    out.puts "public #{decl_string typedef.declaration} InnerValue { get; set; }"
    out.puts

    out.puts "public static void Encode(XdrDataOutputStream stream, #{name typedef} encoded#{name typedef})"
    out.puts '{'
    out.indent do
      encode_innervalue_member "encoded#{name typedef}", typedef, out
    end
    out.puts '}'
    out.puts

    # decode with maxDepth
    out.puts "public static #{name typedef} Decode(XdrDataInputStream stream, int maxDepth)"
    out.puts '{'
    out.indent do
      out.puts 'if (maxDepth <= 0)'
      out.indent do
        out.puts 'throw new IOException("Maximum decoding depth reached");'
      end
      out.puts 'maxDepth -= 1;'
      out.puts "var decoded#{name typedef} = new #{name typedef}();"
      decode_innervalue_member "decoded#{name typedef}", typedef, out, "maxDepth"
      out.puts "return decoded#{name typedef};"
    end
    out.puts '}'
    out.puts

    # decode without maxDepth
    out.puts "public static #{name typedef} Decode(XdrDataInputStream stream)"
    out.puts '{'
    out.indent do
      out.puts "return Decode(stream, XdrDataInputStream.DefaultMaxDepth);"
    end
    out.puts '}'
  end

  # ============================================================================
  # Union rendering
  # ============================================================================

  def render_union(union, out)
    if union.discriminant.type.is_a?(AST::Typespecs::Int)
      out.puts "public #{type_string union.discriminant.type} Discriminant { get; set; }"
    else
      out.puts "public #{type_string union.discriminant.type} Discriminant { get; set; } = new();"
    end
    out.puts

    has_non_void_arms = union.arms.any? { |arm| !arm.void? }
    if has_non_void_arms
      union.arms.each do |arm|
        next if arm.void?
        out.puts "public #{decl_string(arm.declaration)} #{arm.name.camelize} { get; set; }"
      end
      out.puts
    end

    # Encode
    out.puts "public static void Encode(XdrDataOutputStream stream, #{name union} encoded#{name union})"
    out.puts '{'
    out.indent do
      if union.discriminant.type.is_a?(AST::Typespecs::Int)
        out.puts "stream.WriteInt(encoded#{name union}.Discriminant);"
        out.puts "switch (encoded#{name union}.Discriminant)"
      else
        out.puts "stream.WriteInt((int)encoded#{name union}.Discriminant.InnerValue);"
        out.puts "switch (encoded#{name union}.Discriminant.InnerValue)"
      end
      out.puts '{'
      out.indent do
        union.arms.each do |arm|
          case arm
          when AST::Definitions::UnionDefaultArm
            out.puts 'default:'
          else
            arm.cases.each do |kase|
              if kase.value.is_a?(AST::Identifier)
                if union.discriminant.type.is_a?(AST::Typespecs::Int)
                  out.puts "case #{kase.value.name}:"
                else
                  out.puts "case #{type_string union.discriminant.type}.#{type_string union.discriminant.type}Enum.#{kase.value.name}:"
                end
              else
                out.puts "case #{kase.value.value}:"
              end
            end
          end
          out.indent do
            encode_member "encoded#{name union}", arm, out
            out.puts 'break;'
          end
        end
      end
      out.puts '}'
    end
    out.puts '}'
    out.puts

    # Decode with maxDepth
    out.puts "public static #{name union} Decode(XdrDataInputStream stream, int maxDepth)"
    out.puts '{'
    out.indent do
      out.puts 'if (maxDepth <= 0)'
      out.indent do
        out.puts 'throw new IOException("Maximum decoding depth reached");'
      end
      out.puts 'maxDepth -= 1;'
      out.puts "var decoded#{name union} = new #{name union}();"
      if union.discriminant.type.is_a?(AST::Typespecs::Int)
        out.puts 'var discriminant = stream.ReadInt();'
        out.puts "decoded#{name union}.Discriminant = discriminant;"
        out.puts "switch (decoded#{name union}.Discriminant)"
      else
        out.puts "var discriminant = #{name union.discriminant.type}.Decode(stream, maxDepth);"
        out.puts "decoded#{name union}.Discriminant = discriminant;"
        out.puts "switch (decoded#{name union}.Discriminant.InnerValue)"
      end
      out.puts '{'
      out.indent do
        has_default_arm = union.arms.any? { |arm| arm.is_a?(AST::Definitions::UnionDefaultArm) }
        union.arms.each do |arm|
          case arm
          when AST::Definitions::UnionDefaultArm
            out.puts 'default:'
          else
            arm.cases.each do |kase|
              if kase.value.is_a?(AST::Identifier)
                if union.discriminant.type.is_a?(AST::Typespecs::Int)
                  out.puts "case #{kase.value.name}:"
                else
                  out.puts "case #{type_string union.discriminant.type}.#{type_string union.discriminant.type}Enum.#{kase.value.name}:"
                end
              else
                out.puts "case #{kase.value.value}:"
              end
            end
          end
          out.indent do
            decode_member "decoded#{name union}", arm, out, "maxDepth"
            out.puts 'break;'
          end
        end
        unless has_default_arm
          out.puts 'default:'
          out.indent do
            out.puts 'throw new IOException("Unknown discriminant value: " + discriminant);'
          end
        end
      end
      out.puts '}'
      out.puts
      out.puts "return decoded#{name union};"
    end
    out.puts '}'
    out.puts

    # Decode without maxDepth
    out.puts "public static #{name union} Decode(XdrDataInputStream stream)"
    out.puts '{'
    out.indent do
      out.puts "return Decode(stream, XdrDataInputStream.DefaultMaxDepth);"
    end
    out.puts '}'
  end

  # ============================================================================
  # Top matter & helpers
  # ============================================================================

  def render_top_matter(out, defn)
    out.puts '// Automatically generated by xdrgen'
    out.puts '// DO NOT EDIT or your changes may be overwritten'
    out.puts
    out.puts 'using System;'
    out.puts 'using System.IO;'
    out.puts
    out.puts "namespace #{@namespace};"
    out.break
  end

  def render_source_comment(out, defn)
    return if defn.is_a?(AST::Definitions::Namespace)
    out.puts '// === xdr source ============================================================'
    out.puts
    out.puts '//  ' + defn.text_value.split("\n").join("\n//  ")
    out.puts
    out.puts '//  ==========================================================================='
  end

  # ============================================================================
  # Encode members (XDR binary)
  # ============================================================================

  def encode_innervalue_member(value, member, out)
    case member.declaration
    when AST::Declarations::Void
      return
    end

    if member.type.sub_type == :optional
      out.puts "if (#{value}.InnerValue != null)"
      out.puts '{'
      out.indent do
        out.puts 'stream.WriteInt(1);'
        encode_innervalue_body value, member, out
      end
      out.puts '}'
      out.puts 'else'
      out.puts '{'
      out.indent do
        out.puts 'stream.WriteInt(0);'
      end
      out.puts '}'
    else
      encode_innervalue_body value, member, out
    end
  end

  def encode_innervalue_body(value, member, out)
    case member.declaration
    when AST::Declarations::Opaque
      out.puts "var #{member.name}size = #{value}.InnerValue.Length;"
      if member.declaration.fixed?
        out.puts "if (#{member.name}size != #{convert_constant member.declaration.size})"
        out.indent do
          out.puts "throw new IOException(\"#{member.name} size \" + #{member.name}size + \" does not match fixed size #{member.declaration.size}\");"
        end
      else
        max_size = member.declaration.resolved_size
        if max_size
          out.puts "if (#{member.name}size > #{convert_constant max_size})"
          out.indent do
            out.puts "throw new IOException(\"#{member.name} size \" + #{member.name}size + \" exceeds max size #{max_size}\");"
          end
        end
        out.puts "stream.WriteInt(#{member.name}size);"
      end
      out.puts "stream.Write(#{value}.InnerValue, 0, #{member.name}size);"
    when AST::Declarations::Array
      out.puts "var #{member.name}size = #{value}.InnerValue.Length;"
      if member.declaration.fixed?
        out.puts "if (#{member.name}size != #{convert_constant member.declaration.size})"
        out.indent do
          out.puts "throw new IOException(\"#{member.name} size \" + #{member.name}size + \" does not match fixed size #{member.declaration.size}\");"
        end
      else
        max_size = member.declaration.resolved_size
        if max_size
          out.puts "if (#{member.name}size > #{convert_constant max_size})"
          out.indent do
            out.puts "throw new IOException(\"#{member.name} size \" + #{member.name}size + \" exceeds max size #{max_size}\");"
          end
        end
        out.puts "stream.WriteInt(#{member.name}size);"
      end
      out.puts "for (var i = 0; i < #{member.name}size; i++)"
      out.puts '{'
      out.indent do
        out.puts "#{encode_type member.declaration.type, "#{value}.InnerValue[i]"};"
      end
      out.puts '}'
    else
      out.puts "#{encode_type member.declaration.type, "#{value}.InnerValue"};"
    end
  end

  def encode_member(value, member, out)
    case member.declaration
    when AST::Declarations::Void
      return
    end

    if member.type.sub_type == :optional
      out.puts "if (#{value}.#{member.name.camelize} != null)"
      out.puts '{'
      out.indent do
        out.puts 'stream.WriteInt(1);'
        encode_member_body value, member, out
      end
      out.puts '}'
      out.puts 'else'
      out.puts '{'
      out.indent do
        out.puts 'stream.WriteInt(0);'
      end
      out.puts '}'
    else
      encode_member_body value, member, out
    end
  end

  def encode_member_body(value, member, out)
    case member.declaration
    when AST::Declarations::Void
      return
    when AST::Declarations::Opaque
      out.puts "var #{member.name}size = #{value}.#{member.name.camelize}.Length;"
      if member.declaration.fixed?
        out.puts "if (#{member.name}size != #{convert_constant member.declaration.size})"
        out.indent do
          out.puts "throw new IOException(\"#{member.name} size \" + #{member.name}size + \" does not match fixed size #{member.declaration.size}\");"
        end
      else
        max_size = member.declaration.resolved_size
        if max_size
          out.puts "if (#{member.name}size > #{convert_constant max_size})"
          out.indent do
            out.puts "throw new IOException(\"#{member.name} size \" + #{member.name}size + \" exceeds max size #{max_size}\");"
          end
        end
        out.puts "stream.WriteInt(#{member.name}size);"
      end
      out.puts "stream.Write(#{value}.#{member.name.camelize}, 0, #{member.name}size);"
    when AST::Declarations::Array
      out.puts "var #{member.name}size = #{value}.#{member.name.camelize}.Length;"
      if member.declaration.fixed?
        out.puts "if (#{member.name}size != #{convert_constant member.declaration.size})"
        out.indent do
          out.puts "throw new IOException(\"#{member.name} size \" + #{member.name}size + \" does not match fixed size #{member.declaration.size}\");"
        end
      else
        max_size = member.declaration.resolved_size
        if max_size
          out.puts "if (#{member.name}size > #{convert_constant max_size})"
          out.indent do
            out.puts "throw new IOException(\"#{member.name} size \" + #{member.name}size + \" exceeds max size #{max_size}\");"
          end
        end
        out.puts "stream.WriteInt(#{member.name}size);"
      end
      out.puts "for (var i = 0; i < #{member.name}size; i++)"
      out.puts '{'
      out.indent do
        out.puts "#{encode_type member.declaration.type, "#{value}.#{member.name.camelize}[i]"};"
      end
      out.puts '}'
    else
      out.puts "#{encode_type member.declaration.type, "#{value}.#{member.name.camelize}"};"
    end
  end

  def encode_type(type, value)
    case type
    when AST::Typespecs::Int
      "stream.WriteInt(#{value})"
    when AST::Typespecs::UnsignedInt
      "stream.WriteUInt(#{value})"
    when AST::Typespecs::Hyper
      "stream.WriteLong(#{value})"
    when AST::Typespecs::UnsignedHyper
      "stream.WriteULong(#{value})"
    when AST::Typespecs::Float
      "stream.WriteFloat(#{value})"
    when AST::Typespecs::Double
      "stream.WriteDouble(#{value})"
    when AST::Typespecs::Quadruple
      raise 'cannot render quadruple in c#'
    when AST::Typespecs::Bool
      "stream.WriteInt(#{value} ? 1 : 0)"
    when AST::Typespecs::String
      "stream.WriteString(#{value})"
    when AST::Typespecs::Simple
      "#{name type.resolved_type}.Encode(stream, #{value})"
    when AST::Concerns::NestedDefinition
      "#{name type}.Encode(stream, #{value})"
    else
      raise "Unknown typespec: #{type.class.name}"
    end
  end

  # ============================================================================
  # Decode members (XDR binary)
  # ============================================================================

  def decode_innervalue_member(value, member, out, depth_var = nil)
    case member.declaration
    when AST::Declarations::Void
      return
    end

    if member.type.sub_type == :optional
      out.puts "var #{member.name.camelize}Present = stream.ReadInt();"
      out.puts "if (#{member.name.camelize}Present != 0)"
      out.puts '{'
      out.indent do
        decode_innervalue_body value, member, out, depth_var
      end
      out.puts '}'
    else
      decode_innervalue_body value, member, out, depth_var
    end
  end

  def decode_innervalue_body(value, member, out, depth_var)
    case member.declaration
    when AST::Declarations::Opaque
      if member.declaration.fixed?
        out.puts "var #{member.name}size = #{convert_constant member.declaration.size};"
      else
        out.puts "var #{member.name}size = stream.ReadInt();"
        emit_decode_size_validation(member.name, member.declaration, out)
      end
      out.puts "#{value}.InnerValue = new byte[#{member.name}size];"
      out.puts "stream.Read(#{value}.InnerValue, 0, #{member.name}size);"
    when AST::Declarations::Array
      if member.declaration.fixed?
        out.puts "var #{member.name}size = #{convert_constant member.declaration.size};"
      else
        out.puts "var #{member.name}size = stream.ReadInt();"
        emit_decode_size_validation(member.name, member.declaration, out)
      end
      out.puts "#{value}.InnerValue = new #{type_string member.type}[#{member.name}size];"
      out.puts "for (var i = 0; i < #{member.name}size; i++)"
      out.puts '{'
      out.indent do
        out.puts "#{value}.InnerValue[i] = #{decode_type member.declaration, depth_var};"
      end
      out.puts '}'
    else
      out.puts "#{value}.InnerValue = #{decode_type member.declaration, depth_var};"
    end
  end

  def decode_member(value, member, out, depth_var = nil)
    case member.declaration
    when AST::Declarations::Void
      return
    end

    if member.type.sub_type == :optional
      out.puts "var #{member.name.camelize}Present = stream.ReadInt();"
      out.puts "if (#{member.name.camelize}Present != 0)"
      out.puts '{'
      out.indent do
        decode_member_value value, member, out, depth_var
      end
      out.puts '}'
    else
      decode_member_value value, member, out, depth_var
    end
  end

  def decode_member_value(value, member, out, depth_var = nil)
    case member.declaration
    when AST::Declarations::Void
      return
    when AST::Declarations::Opaque
      if member.declaration.fixed?
        out.puts "var #{member.name}size = #{convert_constant member.declaration.size};"
      else
        out.puts "var #{member.name}size = stream.ReadInt();"
        emit_decode_size_validation(member.name, member.declaration, out)
      end
      out.puts "#{value}.#{member.name.camelize} = new byte[#{member.name}size];"
      out.puts "stream.Read(#{value}.#{member.name.camelize}, 0, #{member.name}size);"
    when AST::Declarations::Array
      if member.declaration.fixed?
        out.puts "var #{member.name}size = #{convert_constant member.declaration.size};"
      else
        out.puts "var #{member.name}size = stream.ReadInt();"
        emit_decode_size_validation(member.name, member.declaration, out)
      end
      out.puts "#{value}.#{member.name.camelize} = new #{type_string member.type}[#{member.name}size];"
      out.puts "for (var i = 0; i < #{member.name}size; i++)"
      out.puts '{'
      out.indent do
        out.puts "#{value}.#{member.name.camelize}[i] = #{decode_type member.declaration, depth_var};"
      end
      out.puts '}'
    else
      out.puts "#{value}.#{member.name.camelize} = #{decode_type member.declaration, depth_var};"
    end
  end

  def emit_decode_size_validation(member_name, declaration, out)
    out.puts "if (#{member_name}size < 0)"
    out.indent do
      out.puts "throw new IOException(\"#{member_name} size \" + #{member_name}size + \" is negative\");"
    end
    max_size = declaration.resolved_size
    if max_size
      out.puts "if (#{member_name}size > #{convert_constant max_size})"
      out.indent do
        out.puts "throw new IOException(\"#{member_name} size \" + #{member_name}size + \" exceeds max size #{max_size}\");"
      end
    end
    out.puts "var #{member_name}RemainingInputLen = stream.GetRemainingInputLen();"
    out.puts "if (#{member_name}RemainingInputLen >= 0 && #{member_name}RemainingInputLen < #{member_name}size)"
    out.indent do
      out.puts "throw new IOException(\"#{member_name} size \" + #{member_name}size + \" exceeds remaining input length \" + #{member_name}RemainingInputLen);"
    end
  end

  def decode_type(decl, depth_var = nil)
    case decl.type
    when AST::Typespecs::Int
      'stream.ReadInt()'
    when AST::Typespecs::UnsignedInt
      'stream.ReadUInt()'
    when AST::Typespecs::Hyper
      'stream.ReadLong()'
    when AST::Typespecs::UnsignedHyper
      'stream.ReadULong()'
    when AST::Typespecs::Float
      'stream.ReadFloat()'
    when AST::Typespecs::Double
      'stream.ReadDouble()'
    when AST::Typespecs::Quadruple
      raise 'cannot render quadruple in c#'
    when AST::Typespecs::Bool
      'stream.ReadInt() == 1 ? true : false'
    when AST::Typespecs::String
      'stream.ReadString()'
    when AST::Typespecs::Simple
      depth_var ? "#{name decl.type.resolved_type}.Decode(stream, #{depth_var})" : "#{name decl.type.resolved_type}.Decode(stream)"
    when AST::Concerns::NestedDefinition
      depth_var ? "#{name decl.type}.Decode(stream, #{depth_var})" : "#{name decl.type}.Decode(stream)"
    else
      raise "Unknown typespec: #{decl.type.class.name}"
    end
  end

  # ============================================================================
  # Type helpers
  # ============================================================================

  def decl_string(decl)
    case decl
    when AST::Declarations::Opaque
      'byte[]'
    when AST::Declarations::String
      'string'
    when AST::Declarations::Array
      "#{type_string decl.type}[]"
    when AST::Declarations::Optional
      type_string(decl.type).to_s
    when AST::Declarations::Simple
      type_string(decl.type)
    else
      raise "Unknown declaration type: #{decl.class.name}"
    end
  end

  def type_string(type)
    case type
    when AST::Typespecs::Int
      'int'
    when AST::Typespecs::UnsignedInt
      'uint'
    when AST::Typespecs::Hyper
      'long'
    when AST::Typespecs::UnsignedHyper
      'ulong'
    when AST::Typespecs::Float
      'float'
    when AST::Typespecs::Double
      'double'
    when AST::Typespecs::Quadruple
      'Tuple'
    when AST::Typespecs::Bool
      'bool'
    when AST::Typespecs::Opaque
      "Byte[#{type.size}]"
    when AST::Typespecs::Simple
      name type.resolved_type
    when AST::Concerns::NestedDefinition
      name type
    else
      raise "Unknown typespec: #{type.class.name}"
    end
  end

  def name(named)
    parent = name named.parent_defn if named.is_a?(AST::Concerns::NestedDefinition)
    result = named.name.camelize
    "#{parent}#{result}"
  end

  def name_string(name)
    name.camelize
  end

  def convert_constant(str)
    if str.nil? || str.empty?
      str
    elsif str =~ /\A\d+\z/
      str
    else
      "Constants.#{str}"
    end
  end
end
