// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct MyStruct
//  {
//      int    someInt;
//      int64  aBigInt;
//      opaque someOpaque[10];
//      string someString<>;
//      string maxString<100>;
//  };

//  ===========================================================================
public class MyStruct
{
    public int SomeInt { get; set; }
    public Int64 ABigInt { get; set; }
    public byte[] SomeOpaque { get; set; }
    public string SomeString { get; set; }
    public string MaxString { get; set; }

    public static void Encode(XdrDataOutputStream stream, MyStruct encodedMyStruct)
    {
        stream.WriteInt(encodedMyStruct.SomeInt);
        Int64.Encode(stream, encodedMyStruct.ABigInt);
        var someOpaqueSize = encodedMyStruct.SomeOpaque.Length;
        if (someOpaqueSize != 10)
            throw new ArgumentException("someOpaque size " + someOpaqueSize + " does not match fixed size 10");
        stream.Write(encodedMyStruct.SomeOpaque, 0, someOpaqueSize);
        stream.WriteString(encodedMyStruct.SomeString);
        stream.WriteString(encodedMyStruct.MaxString);
    }

    public static MyStruct Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding MyStruct");
        maxDepth -= 1;
        var decodedMyStruct = new MyStruct();
        decodedMyStruct.SomeInt = stream.ReadInt();
        decodedMyStruct.ABigInt = Int64.Decode(stream, maxDepth);
        var someOpaqueSize = 10;
        decodedMyStruct.SomeOpaque = new byte[someOpaqueSize];
        stream.Read(decodedMyStruct.SomeOpaque, 0, someOpaqueSize);
        decodedMyStruct.SomeString = stream.ReadString();
        decodedMyStruct.MaxString = stream.ReadString();
        return decodedMyStruct;
    }

    public static MyStruct Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
