version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
before_build:
- cmd: dotnet restore stellar-dotnet-sdk.sln
build:
  project: stellar-dotnet-sdk.sln
  parallel: true
  verbosity: minimal
test_script:
 - cmd: vstest.console /logger:Appveyor stellar-dotnet-sdk-test
deploy: off

