version: 7.0.{build} 
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017

before_build:
  - cmd: dotnet restore stellar-dotnet-sdk.sln
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"
artifacts:
  - path: 'stellar-dotnet-sdk\**\*.nupkg'
    name: nuget
  - path: 'stellar-dotnet-sdk-xdr\**\*.nupkg'
    name: nuget
build:
  project: stellar-dotnet-sdk.sln
  parallel: true
  verbosity: minimal
test_script:
  - cmd: dotnet format --check
  - cmd: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:ExcludeByFile=\"../stellar-dotnet-sdk/chaos.nacl/**/*.cs\" -p:ExcludeByFile=\"../stellar-dotnet-sdk-xdr/generated/*.cs\" ./stellar-dotnet-sdk-test --test-adapter-path:. --logger:Appveyor
after_test:
  - cmd: packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover "./stellar-dotnet-sdk-test/coverage.opencover.xml" -r %COVERALLS_REPO_TOKEN%
deploy:
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
  provider: NuGet
  api_key:
    secure: J6pqB7e0Vjm9sIZcetbLlCF+HLYemSm3GMBogOg4kbCMJ1AqyjjmflxZnAdxZAL2
  skip_symbols: false
  artifact: nuget
