version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
configuration: Debug
platform:
- x64
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: dotnet restore stellar-dotnet-sdk.sln
build:
  project: stellar-dotnet-sdk.sln
  parallel: true
  verbosity: minimal
deploy: off

