version: 2.1.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
before_build:
- cmd: dotnet restore stellar-dotnet-sdk.sln
dotnet_csproj:
  patch: true
  file: stellar-dotnet-sdk.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
artifacts:
  - path: '**\*.nupkg'
    name: nuget
build:
  project: stellar-dotnet-sdk.sln
  parallel: true
  verbosity: minimal
test_script:
 - cmd: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:ExcludeByFile=\"../stellar-dotnet-sdk/chaos.nacl/**/*.cs\" -p:ExcludeByFile=\"../stellar-dotnet-sdk/xdr/generated/*.cs\" ./stellar-dotnet-sdk-test --test-adapter-path:. --logger:Appveyor 
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "./stellar-dotnet-sdk-test/coverage.opencover.xml" -t 3d1827ed-854c-484b-a639-02544eb921b8
deploy:
  provider: NuGet
  api_key:
    secure: CVuX3vYVhZGwqgX6dQTi/V724vsO7PFLkDwkvIHuSeNuh4NASWRm4318O52x7k+2
  skip_symbols: false
  artifact: nuget
