version: 1.0.{build}
environment: 
    APPVEYOR_BLOCK_DOTNETCORE_TESTS_AUTORUN: true
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
configuration: Debug
platform:
- x64
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: SigfolioWallet.sln
  parallel: true
  verbosity: minimal
deploy: off
test:
    assemblies:
        only:
         -  SigfolioWallet.Test\bin\Debug\netcoreapp2.1\SigfolioWallet.Test.dll
