// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct AccountEntryExtensionV2
//  {
//      uint32 numSponsored;
//      uint32 numSponsoring;
//      SponsorshipDescriptor signerSponsoringIDs<MAX_SIGNERS>;
//  
//      union switch (int v)
//      {
//      case 0:
//          void;
//      case 3:
//          AccountEntryExtensionV3 v3;
//      }
//      ext;
//  };

//  ===========================================================================
public class AccountEntryExtensionV2
{
    public Uint32 NumSponsored { get; set; }
    public Uint32 NumSponsoring { get; set; }
    public SponsorshipDescriptor[] SignerSponsoringIDs { get; set; }
    public AccountEntryExtensionV2Ext Ext { get; set; }

    public static void Encode(XdrDataOutputStream stream, AccountEntryExtensionV2 encodedAccountEntryExtensionV2)
    {
        Uint32.Encode(stream, encodedAccountEntryExtensionV2.NumSponsored);
        Uint32.Encode(stream, encodedAccountEntryExtensionV2.NumSponsoring);
        var signerSponsoringIDsSize = encodedAccountEntryExtensionV2.SignerSponsoringIDs.Length;
        if (signerSponsoringIDsSize > 20)
            throw new ArgumentException("signerSponsoringIDs size " + signerSponsoringIDsSize + " exceeds max size 20");
        stream.WriteInt(signerSponsoringIDsSize);
        for (var i = 0; i < signerSponsoringIDsSize; i++)
        {
            SponsorshipDescriptor.Encode(stream, encodedAccountEntryExtensionV2.SignerSponsoringIDs[i]);
        }
        AccountEntryExtensionV2Ext.Encode(stream, encodedAccountEntryExtensionV2.Ext);
    }

    public static AccountEntryExtensionV2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding AccountEntryExtensionV2");
        maxDepth -= 1;
        var decodedAccountEntryExtensionV2 = new AccountEntryExtensionV2();
        decodedAccountEntryExtensionV2.NumSponsored = Uint32.Decode(stream, maxDepth);
        decodedAccountEntryExtensionV2.NumSponsoring = Uint32.Decode(stream, maxDepth);
        var signerSponsoringIDsSize = stream.ReadInt();
        if (signerSponsoringIDsSize < 0)
            throw new InvalidDataException("signerSponsoringIDs size " + signerSponsoringIDsSize + " is negative");
        if (signerSponsoringIDsSize > 20)
            throw new InvalidDataException("signerSponsoringIDs size " + signerSponsoringIDsSize + " exceeds max size 20");
        decodedAccountEntryExtensionV2.SignerSponsoringIDs = new SponsorshipDescriptor[signerSponsoringIDsSize];
        for (var i = 0; i < signerSponsoringIDsSize; i++)
        {
            decodedAccountEntryExtensionV2.SignerSponsoringIDs[i] = SponsorshipDescriptor.Decode(stream, maxDepth);
        }
        decodedAccountEntryExtensionV2.Ext = AccountEntryExtensionV2Ext.Decode(stream, maxDepth);
        return decodedAccountEntryExtensionV2;
    }

    public static AccountEntryExtensionV2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public class AccountEntryExtensionV2Ext
    {
        public int Discriminant { get; set; }

        public AccountEntryExtensionV3 V3 { get; set; }

        public static void Encode(XdrDataOutputStream stream, AccountEntryExtensionV2Ext encodedAccountEntryExtensionV2Ext)
        {
            stream.WriteInt(encodedAccountEntryExtensionV2Ext.Discriminant);
            switch (encodedAccountEntryExtensionV2Ext.Discriminant)
            {
                case 0:
                    break;
                case 3:
                    AccountEntryExtensionV3.Encode(stream, encodedAccountEntryExtensionV2Ext.V3);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + encodedAccountEntryExtensionV2Ext.Discriminant);
            }
        }

        public static AccountEntryExtensionV2Ext Decode(XdrDataInputStream stream, int maxDepth)
        {
            if (maxDepth <= 0)
                throw new InvalidDataException("Maximum decoding depth reached while decoding AccountEntryExtensionV2Ext");
            maxDepth -= 1;
            var decodedAccountEntryExtensionV2Ext = new AccountEntryExtensionV2Ext();
            var discriminant = stream.ReadInt();
            decodedAccountEntryExtensionV2Ext.Discriminant = discriminant;
            switch (decodedAccountEntryExtensionV2Ext.Discriminant)
            {
                case 0:
                    break;
                case 3:
                    decodedAccountEntryExtensionV2Ext.V3 = AccountEntryExtensionV3.Decode(stream, maxDepth);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + discriminant);
            }

            return decodedAccountEntryExtensionV2Ext;
        }

        public static AccountEntryExtensionV2Ext Decode(XdrDataInputStream stream)
        {
            return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
        }
    }
}
