// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union AllowTrustResult switch (AllowTrustResultCode code)
//  {
//  case ALLOW_TRUST_SUCCESS:
//      void;
//  case ALLOW_TRUST_MALFORMED:
//  case ALLOW_TRUST_NO_TRUST_LINE:
//  case ALLOW_TRUST_TRUST_NOT_REQUIRED:
//  case ALLOW_TRUST_CANT_REVOKE:
//  case ALLOW_TRUST_SELF_NOT_ALLOWED:
//  case ALLOW_TRUST_LOW_RESERVE:
//      void;
//  };

//  ===========================================================================
public class AllowTrustResult
{
    public AllowTrustResultCode Discriminant { get; set; } = new();

    public static void Encode(XdrDataOutputStream stream, AllowTrustResult encodedAllowTrustResult)
    {
        stream.WriteInt((int)encodedAllowTrustResult.Discriminant.InnerValue);
        switch (encodedAllowTrustResult.Discriminant.InnerValue)
        {
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_SUCCESS:
                break;
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_MALFORMED:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_NO_TRUST_LINE:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_TRUST_NOT_REQUIRED:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_CANT_REVOKE:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_SELF_NOT_ALLOWED:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_LOW_RESERVE:
                break;
        }
    }

    public static AllowTrustResult Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedAllowTrustResult = new AllowTrustResult();
        var discriminant = AllowTrustResultCode.Decode(stream, maxDepth);
        decodedAllowTrustResult.Discriminant = discriminant;
        switch (decodedAllowTrustResult.Discriminant.InnerValue)
        {
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_SUCCESS:
                break;
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_MALFORMED:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_NO_TRUST_LINE:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_TRUST_NOT_REQUIRED:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_CANT_REVOKE:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_SELF_NOT_ALLOWED:
            case AllowTrustResultCode.AllowTrustResultCodeEnum.ALLOW_TRUST_LOW_RESERVE:
                break;
            default:
                throw new IOException("Unknown discriminant value: " + discriminant);
        }

        return decodedAllowTrustResult;
    }

    public static AllowTrustResult Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
