// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef opaque AssetCode12[12];

//  ===========================================================================
public class AssetCode12
{
    public AssetCode12()
    {
    }

    public AssetCode12(byte[] value)
    {
        InnerValue = value;
    }

    public byte[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, AssetCode12 encodedAssetCode12)
    {
        var assetCode12Size = encodedAssetCode12.InnerValue.Length;
        if (assetCode12Size != 12)
            throw new ArgumentException("AssetCode12 size " + assetCode12Size + " does not match fixed size 12");
        stream.Write(encodedAssetCode12.InnerValue, 0, assetCode12Size);
    }

    public static AssetCode12 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding AssetCode12");
        maxDepth -= 1;
        var decodedAssetCode12 = new AssetCode12();
        var assetCode12Size = 12;
        decodedAssetCode12.InnerValue = new byte[assetCode12Size];
        stream.Read(decodedAssetCode12.InnerValue, 0, assetCode12Size);
        return decodedAssetCode12;
    }

    public static AssetCode12 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
