// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum BumpSequenceResultCode
//  {
//      // codes considered as "success" for the operation
//      BUMP_SEQUENCE_SUCCESS = 0,
//      // codes considered as "failure" for the operation
//      BUMP_SEQUENCE_BAD_SEQ = -1 // `bumpTo` is not within bounds
//  };

//  ===========================================================================
public class BumpSequenceResultCode
{
    public enum BumpSequenceResultCodeEnum
    {
        BUMP_SEQUENCE_SUCCESS = 0,
        BUMP_SEQUENCE_BAD_SEQ = -1,
    }

    public BumpSequenceResultCodeEnum InnerValue { get; set; }

    public static BumpSequenceResultCode Create(BumpSequenceResultCodeEnum v)
    {
        return new BumpSequenceResultCode
        {
            InnerValue = v,
        };
    }

    public static BumpSequenceResultCode Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        _ = maxDepth;
        var value = stream.ReadInt();
        switch (value)
        {
            case 0: return Create(BumpSequenceResultCodeEnum.BUMP_SEQUENCE_SUCCESS);
            case -1: return Create(BumpSequenceResultCodeEnum.BUMP_SEQUENCE_BAD_SEQ);
            default:
                throw new InvalidDataException("Unknown enum value: " + value);
        }
    }

    public static BumpSequenceResultCode Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, BumpSequenceResultCode value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
