// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ChangeTrustOp
//  {
//      ChangeTrustAsset line;
//  
//      // if limit is set to 0, deletes the trust line
//      int64 limit;
//  };

//  ===========================================================================
public class ChangeTrustOp
{
    public ChangeTrustAsset Line { get; set; }
    public Int64 Limit { get; set; }

    public static void Encode(XdrDataOutputStream stream, ChangeTrustOp encodedChangeTrustOp)
    {
        ChangeTrustAsset.Encode(stream, encodedChangeTrustOp.Line);
        Int64.Encode(stream, encodedChangeTrustOp.Limit);
    }

    public static ChangeTrustOp Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedChangeTrustOp = new ChangeTrustOp();
        decodedChangeTrustOp.Line = ChangeTrustAsset.Decode(stream, maxDepth);
        decodedChangeTrustOp.Limit = Int64.Decode(stream, maxDepth);
        return decodedChangeTrustOp;
    }

    public static ChangeTrustOp Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
