// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union ChangeTrustResult switch (ChangeTrustResultCode code)
//  {
//  case CHANGE_TRUST_SUCCESS:
//      void;
//  case CHANGE_TRUST_MALFORMED:
//  case CHANGE_TRUST_NO_ISSUER:
//  case CHANGE_TRUST_INVALID_LIMIT:
//  case CHANGE_TRUST_LOW_RESERVE:
//  case CHANGE_TRUST_SELF_NOT_ALLOWED:
//  case CHANGE_TRUST_TRUST_LINE_MISSING:
//  case CHANGE_TRUST_CANNOT_DELETE:
//  case CHANGE_TRUST_NOT_AUTH_MAINTAIN_LIABILITIES:
//      void;
//  };

//  ===========================================================================
public class ChangeTrustResult
{
    public ChangeTrustResultCode Discriminant { get; set; } = new();

    public static void Encode(XdrDataOutputStream stream, ChangeTrustResult encodedChangeTrustResult)
    {
        stream.WriteInt((int)encodedChangeTrustResult.Discriminant.InnerValue);
        switch (encodedChangeTrustResult.Discriminant.InnerValue)
        {
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_SUCCESS:
                break;
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_MALFORMED:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_NO_ISSUER:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_INVALID_LIMIT:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_LOW_RESERVE:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_SELF_NOT_ALLOWED:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_TRUST_LINE_MISSING:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_CANNOT_DELETE:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_NOT_AUTH_MAINTAIN_LIABILITIES:
                break;
        }
    }

    public static ChangeTrustResult Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedChangeTrustResult = new ChangeTrustResult();
        var discriminant = ChangeTrustResultCode.Decode(stream, maxDepth);
        decodedChangeTrustResult.Discriminant = discriminant;
        switch (decodedChangeTrustResult.Discriminant.InnerValue)
        {
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_SUCCESS:
                break;
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_MALFORMED:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_NO_ISSUER:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_INVALID_LIMIT:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_LOW_RESERVE:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_SELF_NOT_ALLOWED:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_TRUST_LINE_MISSING:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_CANNOT_DELETE:
            case ChangeTrustResultCode.ChangeTrustResultCodeEnum.CHANGE_TRUST_NOT_AUTH_MAINTAIN_LIABILITIES:
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant);
        }

        return decodedChangeTrustResult;
    }

    public static ChangeTrustResult Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
