// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum ClaimableBalanceFlags
//  {
//      // If set, the issuer account of the asset held by the claimable balance may
//      // clawback the claimable balance
//      CLAIMABLE_BALANCE_CLAWBACK_ENABLED_FLAG = 0x1
//  };

//  ===========================================================================
public class ClaimableBalanceFlags
{
    public enum ClaimableBalanceFlagsEnum
    {
        CLAIMABLE_BALANCE_CLAWBACK_ENABLED_FLAG = 1,
    }

    public ClaimableBalanceFlagsEnum InnerValue { get; set; }

    public static ClaimableBalanceFlags Create(ClaimableBalanceFlagsEnum v)
    {
        return new ClaimableBalanceFlags
        {
            InnerValue = v,
        };
    }

    public static ClaimableBalanceFlags Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        _ = maxDepth;
        var value = stream.ReadInt();
        switch (value)
        {
            case 1: return Create(ClaimableBalanceFlagsEnum.CLAIMABLE_BALANCE_CLAWBACK_ENABLED_FLAG);
            default:
                throw new InvalidDataException("Unknown enum value: " + value);
        }
    }

    public static ClaimableBalanceFlags Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, ClaimableBalanceFlags value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
