// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union ClaimPredicate switch (ClaimPredicateType type)
//  {
//  case CLAIM_PREDICATE_UNCONDITIONAL:
//      void;
//  case CLAIM_PREDICATE_AND:
//      ClaimPredicate andPredicates<2>;
//  case CLAIM_PREDICATE_OR:
//      ClaimPredicate orPredicates<2>;
//  case CLAIM_PREDICATE_NOT:
//      ClaimPredicate* notPredicate;
//  case CLAIM_PREDICATE_BEFORE_ABSOLUTE_TIME:
//      int64 absBefore; // Predicate will be true if closeTime < absBefore
//  case CLAIM_PREDICATE_BEFORE_RELATIVE_TIME:
//      int64 relBefore; // Seconds since closeTime of the ledger in which the
//                       // ClaimableBalanceEntry was created
//  };

//  ===========================================================================
public class ClaimPredicate
{
    public ClaimPredicateType Discriminant { get; set; } = new();

    public ClaimPredicate[] AndPredicates { get; set; }
    public ClaimPredicate[] OrPredicates { get; set; }
    public ClaimPredicate NotPredicate { get; set; }
    public Int64 AbsBefore { get; set; }
    public Int64 RelBefore { get; set; }

    public static void Encode(XdrDataOutputStream stream, ClaimPredicate encodedClaimPredicate)
    {
        stream.WriteInt((int)encodedClaimPredicate.Discriminant.InnerValue);
        switch (encodedClaimPredicate.Discriminant.InnerValue)
        {
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_UNCONDITIONAL:
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_AND:
                var andPredicatesSize = encodedClaimPredicate.AndPredicates.Length;
                if (andPredicatesSize > 2)
                    throw new ArgumentException("andPredicates size " + andPredicatesSize + " exceeds max size 2");
                stream.WriteInt(andPredicatesSize);
                for (var i = 0; i < andPredicatesSize; i++)
                {
                    ClaimPredicate.Encode(stream, encodedClaimPredicate.AndPredicates[i]);
                }
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_OR:
                var orPredicatesSize = encodedClaimPredicate.OrPredicates.Length;
                if (orPredicatesSize > 2)
                    throw new ArgumentException("orPredicates size " + orPredicatesSize + " exceeds max size 2");
                stream.WriteInt(orPredicatesSize);
                for (var i = 0; i < orPredicatesSize; i++)
                {
                    ClaimPredicate.Encode(stream, encodedClaimPredicate.OrPredicates[i]);
                }
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_NOT:
                if (encodedClaimPredicate.NotPredicate != null)
                {
                    stream.WriteInt(1);
                    ClaimPredicate.Encode(stream, encodedClaimPredicate.NotPredicate);
                }
                else
                {
                    stream.WriteInt(0);
                }
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_BEFORE_ABSOLUTE_TIME:
                Int64.Encode(stream, encodedClaimPredicate.AbsBefore);
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_BEFORE_RELATIVE_TIME:
                Int64.Encode(stream, encodedClaimPredicate.RelBefore);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + encodedClaimPredicate.Discriminant.InnerValue);
        }
    }

    public static ClaimPredicate Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding ClaimPredicate");
        maxDepth -= 1;
        var decodedClaimPredicate = new ClaimPredicate();
        var discriminant = ClaimPredicateType.Decode(stream, maxDepth);
        decodedClaimPredicate.Discriminant = discriminant;
        switch (decodedClaimPredicate.Discriminant.InnerValue)
        {
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_UNCONDITIONAL:
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_AND:
                var andPredicatesSize = stream.ReadInt();
                if (andPredicatesSize < 0)
                    throw new InvalidDataException("andPredicates size " + andPredicatesSize + " is negative");
                if (andPredicatesSize > 2)
                    throw new InvalidDataException("andPredicates size " + andPredicatesSize + " exceeds max size 2");
                var andPredicatesRemainingInputLen = stream.GetRemainingInputLen();
                if (andPredicatesRemainingInputLen >= 0 && andPredicatesRemainingInputLen < andPredicatesSize)
                    throw new InvalidDataException("andPredicates size " + andPredicatesSize + " exceeds remaining input length " + andPredicatesRemainingInputLen);
                decodedClaimPredicate.AndPredicates = new ClaimPredicate[andPredicatesSize];
                for (var i = 0; i < andPredicatesSize; i++)
                {
                    decodedClaimPredicate.AndPredicates[i] = ClaimPredicate.Decode(stream, maxDepth);
                }
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_OR:
                var orPredicatesSize = stream.ReadInt();
                if (orPredicatesSize < 0)
                    throw new InvalidDataException("orPredicates size " + orPredicatesSize + " is negative");
                if (orPredicatesSize > 2)
                    throw new InvalidDataException("orPredicates size " + orPredicatesSize + " exceeds max size 2");
                var orPredicatesRemainingInputLen = stream.GetRemainingInputLen();
                if (orPredicatesRemainingInputLen >= 0 && orPredicatesRemainingInputLen < orPredicatesSize)
                    throw new InvalidDataException("orPredicates size " + orPredicatesSize + " exceeds remaining input length " + orPredicatesRemainingInputLen);
                decodedClaimPredicate.OrPredicates = new ClaimPredicate[orPredicatesSize];
                for (var i = 0; i < orPredicatesSize; i++)
                {
                    decodedClaimPredicate.OrPredicates[i] = ClaimPredicate.Decode(stream, maxDepth);
                }
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_NOT:
                var notPredicatePresent = stream.ReadInt();
                if (notPredicatePresent != 0)
                {
                    decodedClaimPredicate.NotPredicate = ClaimPredicate.Decode(stream, maxDepth);
                }
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_BEFORE_ABSOLUTE_TIME:
                decodedClaimPredicate.AbsBefore = Int64.Decode(stream, maxDepth);
                break;
            case ClaimPredicateType.ClaimPredicateTypeEnum.CLAIM_PREDICATE_BEFORE_RELATIVE_TIME:
                decodedClaimPredicate.RelBefore = Int64.Decode(stream, maxDepth);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
        }

        return decodedClaimPredicate;
    }

    public static ClaimPredicate Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
