// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union ClaimAtom switch (ClaimAtomType type)
//  {
//  case CLAIM_ATOM_TYPE_V0:
//      ClaimOfferAtomV0 v0;
//  case CLAIM_ATOM_TYPE_ORDER_BOOK:
//      ClaimOfferAtom orderBook;
//  case CLAIM_ATOM_TYPE_LIQUIDITY_POOL:
//      ClaimLiquidityAtom liquidityPool;
//  };

//  ===========================================================================
public class ClaimAtom
{
    public ClaimAtomType Discriminant { get; set; } = new();

    public ClaimOfferAtomV0 V0 { get; set; }
    public ClaimOfferAtom OrderBook { get; set; }
    public ClaimLiquidityAtom LiquidityPool { get; set; }

    public static void Encode(XdrDataOutputStream stream, ClaimAtom encodedClaimAtom)
    {
        stream.WriteInt((int)encodedClaimAtom.Discriminant.InnerValue);
        switch (encodedClaimAtom.Discriminant.InnerValue)
        {
            case ClaimAtomType.ClaimAtomTypeEnum.CLAIM_ATOM_TYPE_V0:
                ClaimOfferAtomV0.Encode(stream, encodedClaimAtom.V0);
                break;
            case ClaimAtomType.ClaimAtomTypeEnum.CLAIM_ATOM_TYPE_ORDER_BOOK:
                ClaimOfferAtom.Encode(stream, encodedClaimAtom.OrderBook);
                break;
            case ClaimAtomType.ClaimAtomTypeEnum.CLAIM_ATOM_TYPE_LIQUIDITY_POOL:
                ClaimLiquidityAtom.Encode(stream, encodedClaimAtom.LiquidityPool);
                break;
        }
    }

    public static ClaimAtom Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedClaimAtom = new ClaimAtom();
        var discriminant = ClaimAtomType.Decode(stream, maxDepth);
        decodedClaimAtom.Discriminant = discriminant;
        switch (decodedClaimAtom.Discriminant.InnerValue)
        {
            case ClaimAtomType.ClaimAtomTypeEnum.CLAIM_ATOM_TYPE_V0:
                decodedClaimAtom.V0 = ClaimOfferAtomV0.Decode(stream, maxDepth);
                break;
            case ClaimAtomType.ClaimAtomTypeEnum.CLAIM_ATOM_TYPE_ORDER_BOOK:
                decodedClaimAtom.OrderBook = ClaimOfferAtom.Decode(stream, maxDepth);
                break;
            case ClaimAtomType.ClaimAtomTypeEnum.CLAIM_ATOM_TYPE_LIQUIDITY_POOL:
                decodedClaimAtom.LiquidityPool = ClaimLiquidityAtom.Decode(stream, maxDepth);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant);
        }

        return decodedClaimAtom;
    }

    public static ClaimAtom Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
