// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ClaimableBalanceEntry
//  {
//      // Unique identifier for this ClaimableBalanceEntry
//      ClaimableBalanceID balanceID;
//  
//      // List of claimants with associated predicate
//      Claimant claimants<10>;
//  
//      // Any asset including native
//      Asset asset;
//  
//      // Amount of asset
//      int64 amount;
//  
//      // reserved for future use
//      union switch (int v)
//      {
//      case 0:
//          void;
//      case 1:
//          ClaimableBalanceEntryExtensionV1 v1;
//      }
//      ext;
//  };

//  ===========================================================================
public class ClaimableBalanceEntry
{
    public ClaimableBalanceID BalanceID { get; set; }
    public Claimant[] Claimants { get; set; }
    public Asset Asset { get; set; }
    public Int64 Amount { get; set; }
    public ClaimableBalanceEntryExt Ext { get; set; }

    public static void Encode(XdrDataOutputStream stream, ClaimableBalanceEntry encodedClaimableBalanceEntry)
    {
        ClaimableBalanceID.Encode(stream, encodedClaimableBalanceEntry.BalanceID);
        var claimantssize = encodedClaimableBalanceEntry.Claimants.Length;
        if (claimantssize > 10)
            throw new ArgumentException("claimants size " + claimantssize + " exceeds max size 10");
        stream.WriteInt(claimantssize);
        for (var i = 0; i < claimantssize; i++)
        {
            Claimant.Encode(stream, encodedClaimableBalanceEntry.Claimants[i]);
        }
        Asset.Encode(stream, encodedClaimableBalanceEntry.Asset);
        Int64.Encode(stream, encodedClaimableBalanceEntry.Amount);
        ClaimableBalanceEntryExt.Encode(stream, encodedClaimableBalanceEntry.Ext);
    }

    public static ClaimableBalanceEntry Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedClaimableBalanceEntry = new ClaimableBalanceEntry();
        decodedClaimableBalanceEntry.BalanceID = ClaimableBalanceID.Decode(stream, maxDepth);
        var claimantssize = stream.ReadInt();
        if (claimantssize < 0)
            throw new InvalidDataException("claimants size " + claimantssize + " is negative");
        if (claimantssize > 10)
            throw new InvalidDataException("claimants size " + claimantssize + " exceeds max size 10");
        decodedClaimableBalanceEntry.Claimants = new Claimant[claimantssize];
        for (var i = 0; i < claimantssize; i++)
        {
            decodedClaimableBalanceEntry.Claimants[i] = Claimant.Decode(stream, maxDepth);
        }
        decodedClaimableBalanceEntry.Asset = Asset.Decode(stream, maxDepth);
        decodedClaimableBalanceEntry.Amount = Int64.Decode(stream, maxDepth);
        decodedClaimableBalanceEntry.Ext = ClaimableBalanceEntryExt.Decode(stream, maxDepth);
        return decodedClaimableBalanceEntry;
    }

    public static ClaimableBalanceEntry Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public class ClaimableBalanceEntryExt
    {
        public int Discriminant { get; set; }

        public ClaimableBalanceEntryExtensionV1 V1 { get; set; }

        public static void Encode(XdrDataOutputStream stream, ClaimableBalanceEntryExt encodedClaimableBalanceEntryExt)
        {
            stream.WriteInt(encodedClaimableBalanceEntryExt.Discriminant);
            switch (encodedClaimableBalanceEntryExt.Discriminant)
            {
                case 0:
                    break;
                case 1:
                    ClaimableBalanceEntryExtensionV1.Encode(stream, encodedClaimableBalanceEntryExt.V1);
                    break;
            }
        }

        public static ClaimableBalanceEntryExt Decode(XdrDataInputStream stream, int maxDepth)
        {
            if (maxDepth <= 0)
                throw new InvalidDataException("Maximum decoding depth reached");
            maxDepth -= 1;
            var decodedClaimableBalanceEntryExt = new ClaimableBalanceEntryExt();
            var discriminant = stream.ReadInt();
            decodedClaimableBalanceEntryExt.Discriminant = discriminant;
            switch (decodedClaimableBalanceEntryExt.Discriminant)
            {
                case 0:
                    break;
                case 1:
                    decodedClaimableBalanceEntryExt.V1 = ClaimableBalanceEntryExtensionV1.Decode(stream, maxDepth);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + discriminant);
            }

            return decodedClaimableBalanceEntryExt;
        }

        public static ClaimableBalanceEntryExt Decode(XdrDataInputStream stream)
        {
            return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
        }
    }
}
