// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ClaimOfferAtom
//  {
//      // emitted to identify the offer
//      AccountID sellerID; // Account that owns the offer
//      int64 offerID;
//  
//      // amount and asset taken from the owner
//      Asset assetSold;
//      int64 amountSold;
//  
//      // amount and asset sent to the owner
//      Asset assetBought;
//      int64 amountBought;
//  };

//  ===========================================================================
public class ClaimOfferAtom
{
    public AccountID SellerID { get; set; }
    public Int64 OfferID { get; set; }
    public Asset AssetSold { get; set; }
    public Int64 AmountSold { get; set; }
    public Asset AssetBought { get; set; }
    public Int64 AmountBought { get; set; }

    public static void Encode(XdrDataOutputStream stream, ClaimOfferAtom encodedClaimOfferAtom)
    {
        AccountID.Encode(stream, encodedClaimOfferAtom.SellerID);
        Int64.Encode(stream, encodedClaimOfferAtom.OfferID);
        Asset.Encode(stream, encodedClaimOfferAtom.AssetSold);
        Int64.Encode(stream, encodedClaimOfferAtom.AmountSold);
        Asset.Encode(stream, encodedClaimOfferAtom.AssetBought);
        Int64.Encode(stream, encodedClaimOfferAtom.AmountBought);
    }

    public static ClaimOfferAtom Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedClaimOfferAtom = new ClaimOfferAtom();
        decodedClaimOfferAtom.SellerID = AccountID.Decode(stream, maxDepth);
        decodedClaimOfferAtom.OfferID = Int64.Decode(stream, maxDepth);
        decodedClaimOfferAtom.AssetSold = Asset.Decode(stream, maxDepth);
        decodedClaimOfferAtom.AmountSold = Int64.Decode(stream, maxDepth);
        decodedClaimOfferAtom.AssetBought = Asset.Decode(stream, maxDepth);
        decodedClaimOfferAtom.AmountBought = Int64.Decode(stream, maxDepth);
        return decodedClaimOfferAtom;
    }

    public static ClaimOfferAtom Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
