// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union ClaimClaimableBalanceResult switch (ClaimClaimableBalanceResultCode code)
//  {
//  case CLAIM_CLAIMABLE_BALANCE_SUCCESS:
//      void;
//  case CLAIM_CLAIMABLE_BALANCE_DOES_NOT_EXIST:
//  case CLAIM_CLAIMABLE_BALANCE_CANNOT_CLAIM:
//  case CLAIM_CLAIMABLE_BALANCE_LINE_FULL:
//  case CLAIM_CLAIMABLE_BALANCE_NO_TRUST:
//  case CLAIM_CLAIMABLE_BALANCE_NOT_AUTHORIZED:
//      void;
//  };

//  ===========================================================================
public class ClaimClaimableBalanceResult
{
    public ClaimClaimableBalanceResultCode Discriminant { get; set; } = new();

    public static void Encode(XdrDataOutputStream stream, ClaimClaimableBalanceResult encodedClaimClaimableBalanceResult)
    {
        stream.WriteInt((int)encodedClaimClaimableBalanceResult.Discriminant.InnerValue);
        switch (encodedClaimClaimableBalanceResult.Discriminant.InnerValue)
        {
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_SUCCESS:
                break;
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_DOES_NOT_EXIST:
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_CANNOT_CLAIM:
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_LINE_FULL:
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_NO_TRUST:
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_NOT_AUTHORIZED:
                break;
        }
    }

    public static ClaimClaimableBalanceResult Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedClaimClaimableBalanceResult = new ClaimClaimableBalanceResult();
        var discriminant = ClaimClaimableBalanceResultCode.Decode(stream, maxDepth);
        decodedClaimClaimableBalanceResult.Discriminant = discriminant;
        switch (decodedClaimClaimableBalanceResult.Discriminant.InnerValue)
        {
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_SUCCESS:
                break;
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_DOES_NOT_EXIST:
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_CANNOT_CLAIM:
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_LINE_FULL:
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_NO_TRUST:
            case ClaimClaimableBalanceResultCode.ClaimClaimableBalanceResultCodeEnum.CLAIM_CLAIMABLE_BALANCE_NOT_AUTHORIZED:
                break;
            default:
                throw new IOException("Unknown discriminant value: " + discriminant);
        }

        return decodedClaimClaimableBalanceResult;
    }

    public static ClaimClaimableBalanceResult Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
