// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ClaimLiquidityAtom
//  {
//      PoolID liquidityPoolID;
//  
//      // amount and asset taken from the pool
//      Asset assetSold;
//      int64 amountSold;
//  
//      // amount and asset sent to the pool
//      Asset assetBought;
//      int64 amountBought;
//  };

//  ===========================================================================
public class ClaimLiquidityAtom
{
    public PoolID LiquidityPoolID { get; set; }
    public Asset AssetSold { get; set; }
    public Int64 AmountSold { get; set; }
    public Asset AssetBought { get; set; }
    public Int64 AmountBought { get; set; }

    public static void Encode(XdrDataOutputStream stream, ClaimLiquidityAtom encodedClaimLiquidityAtom)
    {
        PoolID.Encode(stream, encodedClaimLiquidityAtom.LiquidityPoolID);
        Asset.Encode(stream, encodedClaimLiquidityAtom.AssetSold);
        Int64.Encode(stream, encodedClaimLiquidityAtom.AmountSold);
        Asset.Encode(stream, encodedClaimLiquidityAtom.AssetBought);
        Int64.Encode(stream, encodedClaimLiquidityAtom.AmountBought);
    }

    public static ClaimLiquidityAtom Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedClaimLiquidityAtom = new ClaimLiquidityAtom();
        decodedClaimLiquidityAtom.LiquidityPoolID = PoolID.Decode(stream, maxDepth);
        decodedClaimLiquidityAtom.AssetSold = Asset.Decode(stream, maxDepth);
        decodedClaimLiquidityAtom.AmountSold = Int64.Decode(stream, maxDepth);
        decodedClaimLiquidityAtom.AssetBought = Asset.Decode(stream, maxDepth);
        decodedClaimLiquidityAtom.AmountBought = Int64.Decode(stream, maxDepth);
        return decodedClaimLiquidityAtom;
    }

    public static ClaimLiquidityAtom Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
