// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ColdArchiveDeletedLeaf
//  {
//      uint32 index;
//      LedgerKey deletedKey;
//  };

//  ===========================================================================
public class ColdArchiveDeletedLeaf
{
    public Uint32 Index { get; set; }
    public LedgerKey DeletedKey { get; set; }

    public static void Encode(XdrDataOutputStream stream, ColdArchiveDeletedLeaf encodedColdArchiveDeletedLeaf)
    {
        Uint32.Encode(stream, encodedColdArchiveDeletedLeaf.Index);
        LedgerKey.Encode(stream, encodedColdArchiveDeletedLeaf.DeletedKey);
    }

    public static ColdArchiveDeletedLeaf Decode(XdrDataInputStream stream)
    {
        var decodedColdArchiveDeletedLeaf = new ColdArchiveDeletedLeaf();
        decodedColdArchiveDeletedLeaf.Index = Uint32.Decode(stream);
        decodedColdArchiveDeletedLeaf.DeletedKey = LedgerKey.Decode(stream);
        return decodedColdArchiveDeletedLeaf;
    }
}