// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ConfigSettingContractParallelComputeV0
//  {
//      // Maximum number of clusters with dependent transactions allowed in a
//      // stage of parallel tx set component.
//      // This effectively sets the lower bound on the number of physical threads
//      // necessary to effectively apply transaction sets in parallel.
//      uint32 ledgerMaxDependentTxClusters;
//  };

//  ===========================================================================
public class ConfigSettingContractParallelComputeV0
{
    public Uint32 LedgerMaxDependentTxClusters { get; set; }

    public static void Encode(XdrDataOutputStream stream, ConfigSettingContractParallelComputeV0 encodedConfigSettingContractParallelComputeV0)
    {
        Uint32.Encode(stream, encodedConfigSettingContractParallelComputeV0.LedgerMaxDependentTxClusters);
    }

    public static ConfigSettingContractParallelComputeV0 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding ConfigSettingContractParallelComputeV0");
        maxDepth -= 1;
        var decodedConfigSettingContractParallelComputeV0 = new ConfigSettingContractParallelComputeV0();
        decodedConfigSettingContractParallelComputeV0.LedgerMaxDependentTxClusters = Uint32.Decode(stream, maxDepth);
        return decodedConfigSettingContractParallelComputeV0;
    }

    public static ConfigSettingContractParallelComputeV0 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
