// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef Hash ContractID;

//  ===========================================================================
public class ContractID
{
    public ContractID()
    {
    }

    public ContractID(Hash value)
    {
        InnerValue = value;
    }

    public Hash InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, ContractID encodedContractID)
    {
        Hash.Encode(stream, encodedContractID.InnerValue);
    }

    public static ContractID Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedContractID = new ContractID();
        decodedContractID.InnerValue = Hash.Decode(stream, maxDepth);
        return decodedContractID;
    }

    public static ContractID Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
