// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ContractCodeEntry {
//      union switch (int v)
//      {
//          case 0:
//              void;
//          case 1:
//              struct
//              {
//                  ExtensionPoint ext;
//                  ContractCodeCostInputs costInputs;
//              } v1;
//      } ext;
//  
//      Hash hash;
//      opaque code<>;
//  };

//  ===========================================================================
public class ContractCodeEntry
{
    public ContractCodeEntryExt Ext { get; set; }
    public Hash Hash { get; set; }
    public byte[] Code { get; set; }

    public static void Encode(XdrDataOutputStream stream, ContractCodeEntry encodedContractCodeEntry)
    {
        ContractCodeEntryExt.Encode(stream, encodedContractCodeEntry.Ext);
        Hash.Encode(stream, encodedContractCodeEntry.Hash);
        var codeSize = encodedContractCodeEntry.Code.Length;
        stream.WriteInt(codeSize);
        stream.Write(encodedContractCodeEntry.Code, 0, codeSize);
    }

    public static ContractCodeEntry Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding ContractCodeEntry");
        maxDepth -= 1;
        var decodedContractCodeEntry = new ContractCodeEntry();
        decodedContractCodeEntry.Ext = ContractCodeEntryExt.Decode(stream, maxDepth);
        decodedContractCodeEntry.Hash = Hash.Decode(stream, maxDepth);
        var codeSize = stream.ReadInt();
        if (codeSize < 0)
            throw new InvalidDataException("code size " + codeSize + " is negative");
        var codeRemainingInputLen = stream.GetRemainingInputLen();
        if (codeRemainingInputLen >= 0 && codeRemainingInputLen < codeSize)
            throw new InvalidDataException("code size " + codeSize + " exceeds remaining input length " + codeRemainingInputLen);
        decodedContractCodeEntry.Code = new byte[codeSize];
        stream.Read(decodedContractCodeEntry.Code, 0, codeSize);
        return decodedContractCodeEntry;
    }

    public static ContractCodeEntry Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public class ContractCodeEntryExt
    {
        public int Discriminant { get; set; }

        public ContractCodeEntryV1 V1 { get; set; }

        public static void Encode(XdrDataOutputStream stream, ContractCodeEntryExt encodedContractCodeEntryExt)
        {
            stream.WriteInt(encodedContractCodeEntryExt.Discriminant);
            switch (encodedContractCodeEntryExt.Discriminant)
            {
                case 0:
                    break;
                case 1:
                    ContractCodeEntryV1.Encode(stream, encodedContractCodeEntryExt.V1);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + encodedContractCodeEntryExt.Discriminant);
            }
        }

        public static ContractCodeEntryExt Decode(XdrDataInputStream stream, int maxDepth)
        {
            if (maxDepth <= 0)
                throw new InvalidDataException("Maximum decoding depth reached while decoding ContractCodeEntryExt");
            maxDepth -= 1;
            var decodedContractCodeEntryExt = new ContractCodeEntryExt();
            var discriminant = stream.ReadInt();
            decodedContractCodeEntryExt.Discriminant = discriminant;
            switch (decodedContractCodeEntryExt.Discriminant)
            {
                case 0:
                    break;
                case 1:
                    decodedContractCodeEntryExt.V1 = ContractCodeEntryV1.Decode(stream, maxDepth);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + discriminant);
            }

            return decodedContractCodeEntryExt;
        }

        public static ContractCodeEntryExt Decode(XdrDataInputStream stream)
        {
            return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
        }

        public class ContractCodeEntryV1
        {
            public ExtensionPoint Ext { get; set; }
            public ContractCodeCostInputs CostInputs { get; set; }

            public static void Encode(XdrDataOutputStream stream, ContractCodeEntryV1 encodedContractCodeEntryV1)
            {
                ExtensionPoint.Encode(stream, encodedContractCodeEntryV1.Ext);
                ContractCodeCostInputs.Encode(stream, encodedContractCodeEntryV1.CostInputs);
            }

            public static ContractCodeEntryV1 Decode(XdrDataInputStream stream, int maxDepth)
            {
                if (maxDepth <= 0)
                    throw new InvalidDataException("Maximum decoding depth reached while decoding ContractCodeEntryV1");
                maxDepth -= 1;
                var decodedContractCodeEntryV1 = new ContractCodeEntryV1();
                decodedContractCodeEntryV1.Ext = ExtensionPoint.Decode(stream, maxDepth);
                decodedContractCodeEntryV1.CostInputs = ContractCodeCostInputs.Decode(stream, maxDepth);
                return decodedContractCodeEntryV1;
            }

            public static ContractCodeEntryV1 Decode(XdrDataInputStream stream)
            {
                return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
            }
        }
    }
}
