// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ContractEvent
//  {
//      // We can use this to add more fields, or because it
//      // is first, to change ContractEvent into a union.
//      ExtensionPoint ext;
//  
//      ContractID* contractID;
//      ContractEventType type;
//  
//      union switch (int v)
//      {
//      case 0:
//          struct
//          {
//              SCVal topics<>;
//              SCVal data;
//          } v0;
//      }
//      body;
//  };

//  ===========================================================================
public class ContractEvent
{
    public ExtensionPoint Ext { get; set; }
    public ContractID ContractID { get; set; }
    public ContractEventType Type { get; set; }
    public ContractEventBody Body { get; set; }

    public static void Encode(XdrDataOutputStream stream, ContractEvent encodedContractEvent)
    {
        ExtensionPoint.Encode(stream, encodedContractEvent.Ext);
        if (encodedContractEvent.ContractID != null)
        {
            stream.WriteInt(1);
            ContractID.Encode(stream, encodedContractEvent.ContractID);
        }
        else
        {
            stream.WriteInt(0);
        }
        ContractEventType.Encode(stream, encodedContractEvent.Type);
        ContractEventBody.Encode(stream, encodedContractEvent.Body);
    }

    public static ContractEvent Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding ContractEvent");
        maxDepth -= 1;
        var decodedContractEvent = new ContractEvent();
        decodedContractEvent.Ext = ExtensionPoint.Decode(stream, maxDepth);
        var ContractIDPresent = stream.ReadInt();
        if (ContractIDPresent != 0)
        {
            decodedContractEvent.ContractID = ContractID.Decode(stream, maxDepth);
        }
        decodedContractEvent.Type = ContractEventType.Decode(stream, maxDepth);
        decodedContractEvent.Body = ContractEventBody.Decode(stream, maxDepth);
        return decodedContractEvent;
    }

    public static ContractEvent Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public class ContractEventBody
    {
        public int Discriminant { get; set; }

        public ContractEventV0 V0 { get; set; }

        public static void Encode(XdrDataOutputStream stream, ContractEventBody encodedContractEventBody)
        {
            stream.WriteInt(encodedContractEventBody.Discriminant);
            switch (encodedContractEventBody.Discriminant)
            {
                case 0:
                    ContractEventV0.Encode(stream, encodedContractEventBody.V0);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + encodedContractEventBody.Discriminant);
            }
        }

        public static ContractEventBody Decode(XdrDataInputStream stream, int maxDepth)
        {
            if (maxDepth <= 0)
                throw new InvalidDataException("Maximum decoding depth reached while decoding ContractEventBody");
            maxDepth -= 1;
            var decodedContractEventBody = new ContractEventBody();
            var discriminant = stream.ReadInt();
            decodedContractEventBody.Discriminant = discriminant;
            switch (decodedContractEventBody.Discriminant)
            {
                case 0:
                    decodedContractEventBody.V0 = ContractEventV0.Decode(stream, maxDepth);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + discriminant);
            }

            return decodedContractEventBody;
        }

        public static ContractEventBody Decode(XdrDataInputStream stream)
        {
            return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
        }

        public class ContractEventV0
        {
            public SCVal[] Topics { get; set; }
            public SCVal Data { get; set; }

            public static void Encode(XdrDataOutputStream stream, ContractEventV0 encodedContractEventV0)
            {
                var topicssize = encodedContractEventV0.Topics.Length;
                stream.WriteInt(topicssize);
                for (var i = 0; i < topicssize; i++)
                {
                    SCVal.Encode(stream, encodedContractEventV0.Topics[i]);
                }
                SCVal.Encode(stream, encodedContractEventV0.Data);
            }

            public static ContractEventV0 Decode(XdrDataInputStream stream, int maxDepth)
            {
                if (maxDepth <= 0)
                    throw new InvalidDataException("Maximum decoding depth reached while decoding ContractEventV0");
                maxDepth -= 1;
                var decodedContractEventV0 = new ContractEventV0();
                var topicssize = stream.ReadInt();
                if (topicssize < 0)
                    throw new InvalidDataException("topics size " + topicssize + " is negative");
                decodedContractEventV0.Topics = new SCVal[topicssize];
                for (var i = 0; i < topicssize; i++)
                {
                    decodedContractEventV0.Topics[i] = SCVal.Decode(stream, maxDepth);
                }
                decodedContractEventV0.Data = SCVal.Decode(stream, maxDepth);
                return decodedContractEventV0;
            }

            public static ContractEventV0 Decode(XdrDataInputStream stream)
            {
                return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
            }
        }
    }
}
