// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef ContractCostParamEntry ContractCostParams<CONTRACT_COST_COUNT_LIMIT>;

//  ===========================================================================
public class ContractCostParams
{
    public ContractCostParams()
    {
    }

    public ContractCostParams(ContractCostParamEntry[] value)
    {
        InnerValue = value;
    }

    public ContractCostParamEntry[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, ContractCostParams encodedContractCostParams)
    {
        var contractCostParamsSize = encodedContractCostParams.InnerValue.Length;
        if (contractCostParamsSize > 1024)
            throw new ArgumentException("ContractCostParams size " + contractCostParamsSize + " exceeds max size 1024");
        stream.WriteInt(contractCostParamsSize);
        for (var i = 0; i < contractCostParamsSize; i++)
        {
            ContractCostParamEntry.Encode(stream, encodedContractCostParams.InnerValue[i]);
        }
    }

    public static ContractCostParams Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding ContractCostParams");
        maxDepth -= 1;
        var decodedContractCostParams = new ContractCostParams();
        var contractCostParamsSize = stream.ReadInt();
        if (contractCostParamsSize < 0)
            throw new InvalidDataException("ContractCostParams size " + contractCostParamsSize + " is negative");
        if (contractCostParamsSize > 1024)
            throw new InvalidDataException("ContractCostParams size " + contractCostParamsSize + " exceeds max size 1024");
        decodedContractCostParams.InnerValue = new ContractCostParamEntry[contractCostParamsSize];
        for (var i = 0; i < contractCostParamsSize; i++)
        {
            decodedContractCostParams.InnerValue[i] = ContractCostParamEntry.Decode(stream, maxDepth);
        }
        return decodedContractCostParams;
    }

    public static ContractCostParams Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
