// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum ContractDataDurability {
//      TEMPORARY = 0,
//      PERSISTENT = 1
//  };

//  ===========================================================================
public class ContractDataDurability
{
    public enum ContractDataDurabilityEnum
    {
        TEMPORARY = 0,
        PERSISTENT = 1,
    }

    public ContractDataDurabilityEnum InnerValue { get; set; }

    public static ContractDataDurability Create(ContractDataDurabilityEnum v)
    {
        return new ContractDataDurability
        {
            InnerValue = v,
        };
    }

    public static ContractDataDurability Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        var value = stream.ReadInt();
        switch (value)
        {
            case 0: return Create(ContractDataDurabilityEnum.TEMPORARY);
            case 1: return Create(ContractDataDurabilityEnum.PERSISTENT);
            default:
                throw new InvalidDataException("Unknown enum value: " + value);
        }
    }

    public static ContractDataDurability Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, ContractDataDurability value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
