// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ContractCodeCostInputs {
//      ExtensionPoint ext;
//      uint32 nInstructions;
//      uint32 nFunctions;
//      uint32 nGlobals;
//      uint32 nTableEntries;
//      uint32 nTypes;
//      uint32 nDataSegments;
//      uint32 nElemSegments;
//      uint32 nImports;
//      uint32 nExports;
//      uint32 nDataSegmentBytes;
//  };

//  ===========================================================================
public class ContractCodeCostInputs
{
    public ExtensionPoint Ext { get; set; }
    public Uint32 NInstructions { get; set; }
    public Uint32 NFunctions { get; set; }
    public Uint32 NGlobals { get; set; }
    public Uint32 NTableEntries { get; set; }
    public Uint32 NTypes { get; set; }
    public Uint32 NDataSegments { get; set; }
    public Uint32 NElemSegments { get; set; }
    public Uint32 NImports { get; set; }
    public Uint32 NExports { get; set; }
    public Uint32 NDataSegmentBytes { get; set; }

    public static void Encode(XdrDataOutputStream stream, ContractCodeCostInputs encodedContractCodeCostInputs)
    {
        ExtensionPoint.Encode(stream, encodedContractCodeCostInputs.Ext);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NInstructions);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NFunctions);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NGlobals);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NTableEntries);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NTypes);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NDataSegments);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NElemSegments);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NImports);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NExports);
        Uint32.Encode(stream, encodedContractCodeCostInputs.NDataSegmentBytes);
    }

    public static ContractCodeCostInputs Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedContractCodeCostInputs = new ContractCodeCostInputs();
        decodedContractCodeCostInputs.Ext = ExtensionPoint.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NInstructions = Uint32.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NFunctions = Uint32.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NGlobals = Uint32.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NTableEntries = Uint32.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NTypes = Uint32.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NDataSegments = Uint32.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NElemSegments = Uint32.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NImports = Uint32.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NExports = Uint32.Decode(stream, maxDepth);
        decodedContractCodeCostInputs.NDataSegmentBytes = Uint32.Decode(stream, maxDepth);
        return decodedContractCodeCostInputs;
    }

    public static ContractCodeCostInputs Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
