// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct CreateContractArgsV2
//  {
//      ContractIDPreimage contractIDPreimage;
//      ContractExecutable executable;
//      // Arguments of the contract's constructor.
//      SCVal constructorArgs<>;
//  };

//  ===========================================================================
public class CreateContractArgsV2
{
    public ContractIDPreimage ContractIDPreimage { get; set; }
    public ContractExecutable Executable { get; set; }
    public SCVal[] ConstructorArgs { get; set; }

    public static void Encode(XdrDataOutputStream stream, CreateContractArgsV2 encodedCreateContractArgsV2)
    {
        ContractIDPreimage.Encode(stream, encodedCreateContractArgsV2.ContractIDPreimage);
        ContractExecutable.Encode(stream, encodedCreateContractArgsV2.Executable);
        var constructorArgsSize = encodedCreateContractArgsV2.ConstructorArgs.Length;
        stream.WriteInt(constructorArgsSize);
        for (var i = 0; i < constructorArgsSize; i++)
        {
            SCVal.Encode(stream, encodedCreateContractArgsV2.ConstructorArgs[i]);
        }
    }

    public static CreateContractArgsV2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding CreateContractArgsV2");
        maxDepth -= 1;
        var decodedCreateContractArgsV2 = new CreateContractArgsV2();
        decodedCreateContractArgsV2.ContractIDPreimage = ContractIDPreimage.Decode(stream, maxDepth);
        decodedCreateContractArgsV2.Executable = ContractExecutable.Decode(stream, maxDepth);
        var constructorArgsSize = stream.ReadInt();
        if (constructorArgsSize < 0)
            throw new InvalidDataException("constructorArgs size " + constructorArgsSize + " is negative");
        decodedCreateContractArgsV2.ConstructorArgs = new SCVal[constructorArgsSize];
        for (var i = 0; i < constructorArgsSize; i++)
        {
            decodedCreateContractArgsV2.ConstructorArgs[i] = SCVal.Decode(stream, maxDepth);
        }
        return decodedCreateContractArgsV2;
    }

    public static CreateContractArgsV2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
