// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union CreateAccountResult switch (CreateAccountResultCode code)
//  {
//  case CREATE_ACCOUNT_SUCCESS:
//      void;
//  case CREATE_ACCOUNT_MALFORMED:
//  case CREATE_ACCOUNT_UNDERFUNDED:
//  case CREATE_ACCOUNT_LOW_RESERVE:
//  case CREATE_ACCOUNT_ALREADY_EXIST:
//      void;
//  };

//  ===========================================================================
public class CreateAccountResult
{
    public CreateAccountResultCode Discriminant { get; set; } = new();

    public static void Encode(XdrDataOutputStream stream, CreateAccountResult encodedCreateAccountResult)
    {
        stream.WriteInt((int)encodedCreateAccountResult.Discriminant.InnerValue);
        switch (encodedCreateAccountResult.Discriminant.InnerValue)
        {
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_SUCCESS:
                break;
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_MALFORMED:
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_UNDERFUNDED:
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_LOW_RESERVE:
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_ALREADY_EXIST:
                break;
        }
    }

    public static CreateAccountResult Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedCreateAccountResult = new CreateAccountResult();
        var discriminant = CreateAccountResultCode.Decode(stream, maxDepth);
        decodedCreateAccountResult.Discriminant = discriminant;
        switch (decodedCreateAccountResult.Discriminant.InnerValue)
        {
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_SUCCESS:
                break;
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_MALFORMED:
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_UNDERFUNDED:
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_LOW_RESERVE:
            case CreateAccountResultCode.CreateAccountResultCodeEnum.CREATE_ACCOUNT_ALREADY_EXIST:
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
        }

        return decodedCreateAccountResult;
    }

    public static CreateAccountResult Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
