// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct Curve25519Secret
//  {
//      opaque key[32];
//  };

//  ===========================================================================
public class Curve25519Secret
{
    public byte[] Key { get; set; }

    public static void Encode(XdrDataOutputStream stream, Curve25519Secret encodedCurve25519Secret)
    {
        var keysize = encodedCurve25519Secret.Key.Length;
        if (keysize != 32)
            throw new ArgumentException("key size " + keysize + " does not match fixed size 32");
        stream.Write(encodedCurve25519Secret.Key, 0, keysize);
    }

    public static Curve25519Secret Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedCurve25519Secret = new Curve25519Secret();
        var keysize = 32;
        decodedCurve25519Secret.Key = new byte[keysize];
        stream.Read(decodedCurve25519Secret.Key, 0, keysize);
        return decodedCurve25519Secret;
    }

    public static Curve25519Secret Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
