// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef opaque DataValue<64>;

//  ===========================================================================
public class DataValue
{
    public DataValue()
    {
    }

    public DataValue(byte[] value)
    {
        InnerValue = value;
    }

    public byte[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, DataValue encodedDataValue)
    {
        var DataValuesize = encodedDataValue.InnerValue.Length;
        if (DataValuesize > 64)
            throw new ArgumentException("DataValue size " + DataValuesize + " exceeds max size 64");
        stream.WriteInt(DataValuesize);
        stream.Write(encodedDataValue.InnerValue, 0, DataValuesize);
    }

    public static DataValue Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding DataValue");
        maxDepth -= 1;
        var decodedDataValue = new DataValue();
        var DataValuesize = stream.ReadInt();
        if (DataValuesize < 0)
            throw new InvalidDataException("DataValue size " + DataValuesize + " is negative");
        if (DataValuesize > 64)
            throw new InvalidDataException("DataValue size " + DataValuesize + " exceeds max size 64");
        var DataValueRemainingInputLen = stream.GetRemainingInputLen();
        if (DataValueRemainingInputLen >= 0 && DataValueRemainingInputLen < DataValuesize)
            throw new InvalidDataException("DataValue size " + DataValuesize + " exceeds remaining input length " + DataValueRemainingInputLen);
        decodedDataValue.InnerValue = new byte[DataValuesize];
        stream.Read(decodedDataValue.InnerValue, 0, DataValuesize);
        return decodedDataValue;
    }

    public static DataValue Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
