// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef opaque EncodedLedgerKey<>;

//  ===========================================================================
public class EncodedLedgerKey
{
    public EncodedLedgerKey()
    {
    }

    public EncodedLedgerKey(byte[] value)
    {
        InnerValue = value;
    }

    public byte[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, EncodedLedgerKey encodedEncodedLedgerKey)
    {
        var encodedLedgerKeySize = encodedEncodedLedgerKey.InnerValue.Length;
        stream.WriteInt(encodedLedgerKeySize);
        stream.Write(encodedEncodedLedgerKey.InnerValue, 0, encodedLedgerKeySize);
    }

    public static EncodedLedgerKey Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding EncodedLedgerKey");
        maxDepth -= 1;
        var decodedEncodedLedgerKey = new EncodedLedgerKey();
        var encodedLedgerKeySize = stream.ReadInt();
        if (encodedLedgerKeySize < 0)
            throw new InvalidDataException("EncodedLedgerKey size " + encodedLedgerKeySize + " is negative");
        var encodedLedgerKeyRemainingInputLen = stream.GetRemainingInputLen();
        if (encodedLedgerKeyRemainingInputLen >= 0 && encodedLedgerKeyRemainingInputLen < encodedLedgerKeySize)
            throw new InvalidDataException("EncodedLedgerKey size " + encodedLedgerKeySize + " exceeds remaining input length " + encodedLedgerKeyRemainingInputLen);
        decodedEncodedLedgerKey.InnerValue = new byte[encodedLedgerKeySize];
        stream.Read(decodedEncodedLedgerKey.InnerValue, 0, encodedLedgerKeySize);
        return decodedEncodedLedgerKey;
    }

    public static EncodedLedgerKey Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
