// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef opaque EncryptedBody<64000>;

//  ===========================================================================
public class EncryptedBody
{
    public EncryptedBody()
    {
    }

    public EncryptedBody(byte[] value)
    {
        InnerValue = value;
    }

    public byte[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, EncryptedBody encodedEncryptedBody)
    {
        var encryptedBodySize = encodedEncryptedBody.InnerValue.Length;
        if (encryptedBodySize > 64000)
            throw new ArgumentException("EncryptedBody size " + encryptedBodySize + " exceeds max size 64000");
        stream.WriteInt(encryptedBodySize);
        stream.Write(encodedEncryptedBody.InnerValue, 0, encryptedBodySize);
    }

    public static EncryptedBody Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding EncryptedBody");
        maxDepth -= 1;
        var decodedEncryptedBody = new EncryptedBody();
        var encryptedBodySize = stream.ReadInt();
        if (encryptedBodySize < 0)
            throw new InvalidDataException("EncryptedBody size " + encryptedBodySize + " is negative");
        if (encryptedBodySize > 64000)
            throw new InvalidDataException("EncryptedBody size " + encryptedBodySize + " exceeds max size 64000");
        var encryptedBodyRemainingInputLen = stream.GetRemainingInputLen();
        if (encryptedBodyRemainingInputLen >= 0 && encryptedBodyRemainingInputLen < encryptedBodySize)
            throw new InvalidDataException("EncryptedBody size " + encryptedBodySize + " exceeds remaining input length " + encryptedBodyRemainingInputLen);
        decodedEncryptedBody.InnerValue = new byte[encryptedBodySize];
        stream.Read(decodedEncryptedBody.InnerValue, 0, encryptedBodySize);
        return decodedEncryptedBody;
    }

    public static EncryptedBody Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
