// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ExtendFootprintTTLOp
//  {
//      ExtensionPoint ext;
//      uint32 extendTo;
//  };

//  ===========================================================================
public class ExtendFootprintTTLOp
{
    public ExtensionPoint Ext { get; set; }
    public Uint32 ExtendTo { get; set; }

    public static void Encode(XdrDataOutputStream stream, ExtendFootprintTTLOp encodedExtendFootprintTTLOp)
    {
        ExtensionPoint.Encode(stream, encodedExtendFootprintTTLOp.Ext);
        Uint32.Encode(stream, encodedExtendFootprintTTLOp.ExtendTo);
    }

    public static ExtendFootprintTTLOp Decode(XdrDataInputStream stream)
    {
        var decodedExtendFootprintTTLOp = new ExtendFootprintTTLOp();
        decodedExtendFootprintTTLOp.Ext = ExtensionPoint.Decode(stream);
        decodedExtendFootprintTTLOp.ExtendTo = Uint32.Decode(stream);
        return decodedExtendFootprintTTLOp;
    }
}