// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union ExtensionPoint switch (int v)
//  {
//  case 0:
//      void;
//  };

//  ===========================================================================
public class ExtensionPoint
{
    public int Discriminant { get; set; }

    public static void Encode(XdrDataOutputStream stream, ExtensionPoint encodedExtensionPoint)
    {
        stream.WriteInt(encodedExtensionPoint.Discriminant);
        switch (encodedExtensionPoint.Discriminant)
        {
            case 0:
                break;
        }
    }

    public static ExtensionPoint Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedExtensionPoint = new ExtensionPoint();
        var discriminant = stream.ReadInt();
        decodedExtensionPoint.Discriminant = discriminant;
        switch (decodedExtensionPoint.Discriminant)
        {
            case 0:
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant);
        }

        return decodedExtensionPoint;
    }

    public static ExtensionPoint Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
