// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ExtendFootprintTTLOp
//  {
//      ExtensionPoint ext;
//      uint32 extendTo;
//  };

//  ===========================================================================
public class ExtendFootprintTTLOp
{
    public ExtensionPoint Ext { get; set; }
    public Uint32 ExtendTo { get; set; }

    public static void Encode(XdrDataOutputStream stream, ExtendFootprintTTLOp encodedExtendFootprintTTLOp)
    {
        ExtensionPoint.Encode(stream, encodedExtendFootprintTTLOp.Ext);
        Uint32.Encode(stream, encodedExtendFootprintTTLOp.ExtendTo);
    }

    public static ExtendFootprintTTLOp Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedExtendFootprintTTLOp = new ExtendFootprintTTLOp();
        decodedExtendFootprintTTLOp.Ext = ExtensionPoint.Decode(stream, maxDepth);
        decodedExtendFootprintTTLOp.ExtendTo = Uint32.Decode(stream, maxDepth);
        return decodedExtendFootprintTTLOp;
    }

    public static ExtendFootprintTTLOp Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
