// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct FrozenLedgerKeys {
//      EncodedLedgerKey keys<>;
//  };

//  ===========================================================================
public class FrozenLedgerKeys
{
    public EncodedLedgerKey[] Keys { get; set; }

    public static void Encode(XdrDataOutputStream stream, FrozenLedgerKeys encodedFrozenLedgerKeys)
    {
        var keysSize = encodedFrozenLedgerKeys.Keys.Length;
        stream.WriteInt(keysSize);
        for (var i = 0; i < keysSize; i++)
        {
            EncodedLedgerKey.Encode(stream, encodedFrozenLedgerKeys.Keys[i]);
        }
    }

    public static FrozenLedgerKeys Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding FrozenLedgerKeys");
        maxDepth -= 1;
        var decodedFrozenLedgerKeys = new FrozenLedgerKeys();
        var keysSize = stream.ReadInt();
        if (keysSize < 0)
            throw new InvalidDataException("keys size " + keysSize + " is negative");
        var keysRemainingInputLen = stream.GetRemainingInputLen();
        if (keysRemainingInputLen >= 0 && keysRemainingInputLen < keysSize)
            throw new InvalidDataException("keys size " + keysSize + " exceeds remaining input length " + keysRemainingInputLen);
        decodedFrozenLedgerKeys.Keys = new EncodedLedgerKey[keysSize];
        for (var i = 0; i < keysSize; i++)
        {
            decodedFrozenLedgerKeys.Keys[i] = EncodedLedgerKey.Decode(stream, maxDepth);
        }
        return decodedFrozenLedgerKeys;
    }

    public static FrozenLedgerKeys Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
