// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct FrozenLedgerKeysDelta {
//      EncodedLedgerKey keysToFreeze<>;
//      EncodedLedgerKey keysToUnfreeze<>;
//  };

//  ===========================================================================
public class FrozenLedgerKeysDelta
{
    public EncodedLedgerKey[] KeysToFreeze { get; set; }
    public EncodedLedgerKey[] KeysToUnfreeze { get; set; }

    public static void Encode(XdrDataOutputStream stream, FrozenLedgerKeysDelta encodedFrozenLedgerKeysDelta)
    {
        var keysToFreezeSize = encodedFrozenLedgerKeysDelta.KeysToFreeze.Length;
        stream.WriteInt(keysToFreezeSize);
        for (var i = 0; i < keysToFreezeSize; i++)
        {
            EncodedLedgerKey.Encode(stream, encodedFrozenLedgerKeysDelta.KeysToFreeze[i]);
        }
        var keysToUnfreezeSize = encodedFrozenLedgerKeysDelta.KeysToUnfreeze.Length;
        stream.WriteInt(keysToUnfreezeSize);
        for (var i = 0; i < keysToUnfreezeSize; i++)
        {
            EncodedLedgerKey.Encode(stream, encodedFrozenLedgerKeysDelta.KeysToUnfreeze[i]);
        }
    }

    public static FrozenLedgerKeysDelta Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding FrozenLedgerKeysDelta");
        maxDepth -= 1;
        var decodedFrozenLedgerKeysDelta = new FrozenLedgerKeysDelta();
        var keysToFreezeSize = stream.ReadInt();
        if (keysToFreezeSize < 0)
            throw new InvalidDataException("keysToFreeze size " + keysToFreezeSize + " is negative");
        var keysToFreezeRemainingInputLen = stream.GetRemainingInputLen();
        if (keysToFreezeRemainingInputLen >= 0 && keysToFreezeRemainingInputLen < keysToFreezeSize)
            throw new InvalidDataException("keysToFreeze size " + keysToFreezeSize + " exceeds remaining input length " + keysToFreezeRemainingInputLen);
        decodedFrozenLedgerKeysDelta.KeysToFreeze = new EncodedLedgerKey[keysToFreezeSize];
        for (var i = 0; i < keysToFreezeSize; i++)
        {
            decodedFrozenLedgerKeysDelta.KeysToFreeze[i] = EncodedLedgerKey.Decode(stream, maxDepth);
        }
        var keysToUnfreezeSize = stream.ReadInt();
        if (keysToUnfreezeSize < 0)
            throw new InvalidDataException("keysToUnfreeze size " + keysToUnfreezeSize + " is negative");
        var keysToUnfreezeRemainingInputLen = stream.GetRemainingInputLen();
        if (keysToUnfreezeRemainingInputLen >= 0 && keysToUnfreezeRemainingInputLen < keysToUnfreezeSize)
            throw new InvalidDataException("keysToUnfreeze size " + keysToUnfreezeSize + " exceeds remaining input length " + keysToUnfreezeRemainingInputLen);
        decodedFrozenLedgerKeysDelta.KeysToUnfreeze = new EncodedLedgerKey[keysToUnfreezeSize];
        for (var i = 0; i < keysToUnfreezeSize; i++)
        {
            decodedFrozenLedgerKeysDelta.KeysToUnfreeze[i] = EncodedLedgerKey.Decode(stream, maxDepth);
        }
        return decodedFrozenLedgerKeysDelta;
    }

    public static FrozenLedgerKeysDelta Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
