// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union GeneralizedTransactionSet switch (int v)
//  {
//  // We consider the legacy TransactionSet to be v0.
//  case 1:
//      TransactionSetV1 v1TxSet;
//  };

//  ===========================================================================
public class GeneralizedTransactionSet
{
    public int Discriminant { get; set; }

    public TransactionSetV1 V1TxSet { get; set; }

    public static void Encode(XdrDataOutputStream stream, GeneralizedTransactionSet encodedGeneralizedTransactionSet)
    {
        stream.WriteInt(encodedGeneralizedTransactionSet.Discriminant);
        switch (encodedGeneralizedTransactionSet.Discriminant)
        {
            case 1:
                TransactionSetV1.Encode(stream, encodedGeneralizedTransactionSet.V1TxSet);
                break;
        }
    }

    public static GeneralizedTransactionSet Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedGeneralizedTransactionSet = new GeneralizedTransactionSet();
        var discriminant = stream.ReadInt();
        decodedGeneralizedTransactionSet.Discriminant = discriminant;
        switch (decodedGeneralizedTransactionSet.Discriminant)
        {
            case 1:
                decodedGeneralizedTransactionSet.V1TxSet = TransactionSetV1.Decode(stream, maxDepth);
                break;
            default:
                throw new IOException("Unknown discriminant value: " + discriminant);
        }

        return decodedGeneralizedTransactionSet;
    }

    public static GeneralizedTransactionSet Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
