// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct HmacSha256Mac
//  {
//      opaque mac[32];
//  };

//  ===========================================================================
public class HmacSha256Mac
{
    public byte[] Mac { get; set; }

    public static void Encode(XdrDataOutputStream stream, HmacSha256Mac encodedHmacSha256Mac)
    {
        var macsize = encodedHmacSha256Mac.Mac.Length;
        if (macsize != 32)
            throw new IOException("mac size " + macsize + " does not match fixed size 32");
        stream.Write(encodedHmacSha256Mac.Mac, 0, macsize);
    }

    public static HmacSha256Mac Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedHmacSha256Mac = new HmacSha256Mac();
        var macsize = 32;
        decodedHmacSha256Mac.Mac = new byte[macsize];
        stream.Read(decodedHmacSha256Mac.Mac, 0, macsize);
        return decodedHmacSha256Mac;
    }

    public static HmacSha256Mac Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
