// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct HmacSha256Key
//  {
//      opaque key[32];
//  };

//  ===========================================================================
public class HmacSha256Key
{
    public byte[] Key { get; set; }

    public static void Encode(XdrDataOutputStream stream, HmacSha256Key encodedHmacSha256Key)
    {
        var keySize = encodedHmacSha256Key.Key.Length;
        if (keySize != 32)
            throw new ArgumentException("key size " + keySize + " does not match fixed size 32");
        stream.Write(encodedHmacSha256Key.Key, 0, keySize);
    }

    public static HmacSha256Key Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding HmacSha256Key");
        maxDepth -= 1;
        var decodedHmacSha256Key = new HmacSha256Key();
        var keySize = 32;
        decodedHmacSha256Key.Key = new byte[keySize];
        stream.Read(decodedHmacSha256Key.Key, 0, keySize);
        return decodedHmacSha256Key;
    }

    public static HmacSha256Key Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
