// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union InflationResult switch (InflationResultCode code)
//  {
//  case INFLATION_SUCCESS:
//      InflationPayout payouts<>;
//  case INFLATION_NOT_TIME:
//      void;
//  };

//  ===========================================================================
public class InflationResult
{
    public InflationResultCode Discriminant { get; set; } = new();

    public InflationPayout[] Payouts { get; set; }

    public static void Encode(XdrDataOutputStream stream, InflationResult encodedInflationResult)
    {
        stream.WriteInt((int)encodedInflationResult.Discriminant.InnerValue);
        switch (encodedInflationResult.Discriminant.InnerValue)
        {
            case InflationResultCode.InflationResultCodeEnum.INFLATION_SUCCESS:
                var payoutsSize = encodedInflationResult.Payouts.Length;
                stream.WriteInt(payoutsSize);
                for (var i = 0; i < payoutsSize; i++)
                {
                    InflationPayout.Encode(stream, encodedInflationResult.Payouts[i]);
                }
                break;
            case InflationResultCode.InflationResultCodeEnum.INFLATION_NOT_TIME:
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + encodedInflationResult.Discriminant.InnerValue);
        }
    }

    public static InflationResult Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding InflationResult");
        maxDepth -= 1;
        var decodedInflationResult = new InflationResult();
        var discriminant = InflationResultCode.Decode(stream, maxDepth);
        decodedInflationResult.Discriminant = discriminant;
        switch (decodedInflationResult.Discriminant.InnerValue)
        {
            case InflationResultCode.InflationResultCodeEnum.INFLATION_SUCCESS:
                var payoutsSize = stream.ReadInt();
                if (payoutsSize < 0)
                    throw new InvalidDataException("payouts size " + payoutsSize + " is negative");
                var payoutsRemainingInputLen = stream.GetRemainingInputLen();
                if (payoutsRemainingInputLen >= 0 && payoutsRemainingInputLen < payoutsSize)
                    throw new InvalidDataException("payouts size " + payoutsSize + " exceeds remaining input length " + payoutsRemainingInputLen);
                decodedInflationResult.Payouts = new InflationPayout[payoutsSize];
                for (var i = 0; i < payoutsSize; i++)
                {
                    decodedInflationResult.Payouts[i] = InflationPayout.Decode(stream, maxDepth);
                }
                break;
            case InflationResultCode.InflationResultCodeEnum.INFLATION_NOT_TIME:
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
        }

        return decodedInflationResult;
    }

    public static InflationResult Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
