// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct InvokeHostFunctionOp
//  {
//      // Host function to invoke.
//      HostFunction hostFunction;
//      // Per-address authorizations for this host function.
//      SorobanAuthorizationEntry auth<>;
//  };

//  ===========================================================================
public class InvokeHostFunctionOp
{
    public HostFunction HostFunction { get; set; }
    public SorobanAuthorizationEntry[] Auth { get; set; }

    public static void Encode(XdrDataOutputStream stream, InvokeHostFunctionOp encodedInvokeHostFunctionOp)
    {
        HostFunction.Encode(stream, encodedInvokeHostFunctionOp.HostFunction);
        var authSize = encodedInvokeHostFunctionOp.Auth.Length;
        stream.WriteInt(authSize);
        for (var i = 0; i < authSize; i++)
        {
            SorobanAuthorizationEntry.Encode(stream, encodedInvokeHostFunctionOp.Auth[i]);
        }
    }

    public static InvokeHostFunctionOp Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding InvokeHostFunctionOp");
        maxDepth -= 1;
        var decodedInvokeHostFunctionOp = new InvokeHostFunctionOp();
        decodedInvokeHostFunctionOp.HostFunction = HostFunction.Decode(stream, maxDepth);
        var authSize = stream.ReadInt();
        if (authSize < 0)
            throw new InvalidDataException("auth size " + authSize + " is negative");
        var authRemainingInputLen = stream.GetRemainingInputLen();
        if (authRemainingInputLen >= 0 && authRemainingInputLen < authSize)
            throw new InvalidDataException("auth size " + authSize + " exceeds remaining input length " + authRemainingInputLen);
        decodedInvokeHostFunctionOp.Auth = new SorobanAuthorizationEntry[authSize];
        for (var i = 0; i < authSize; i++)
        {
            decodedInvokeHostFunctionOp.Auth[i] = SorobanAuthorizationEntry.Decode(stream, maxDepth);
        }
        return decodedInvokeHostFunctionOp;
    }

    public static InvokeHostFunctionOp Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
