// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct InvokeHostFunctionSuccessPreImage
//  {
//      SCVal returnValue;
//      ContractEvent events<>;
//  };

//  ===========================================================================
public class InvokeHostFunctionSuccessPreImage
{
    public SCVal ReturnValue { get; set; }
    public ContractEvent[] Events { get; set; }

    public static void Encode(XdrDataOutputStream stream, InvokeHostFunctionSuccessPreImage encodedInvokeHostFunctionSuccessPreImage)
    {
        SCVal.Encode(stream, encodedInvokeHostFunctionSuccessPreImage.ReturnValue);
        var eventsSize = encodedInvokeHostFunctionSuccessPreImage.Events.Length;
        stream.WriteInt(eventsSize);
        for (var i = 0; i < eventsSize; i++)
        {
            ContractEvent.Encode(stream, encodedInvokeHostFunctionSuccessPreImage.Events[i]);
        }
    }

    public static InvokeHostFunctionSuccessPreImage Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding InvokeHostFunctionSuccessPreImage");
        maxDepth -= 1;
        var decodedInvokeHostFunctionSuccessPreImage = new InvokeHostFunctionSuccessPreImage();
        decodedInvokeHostFunctionSuccessPreImage.ReturnValue = SCVal.Decode(stream, maxDepth);
        var eventsSize = stream.ReadInt();
        if (eventsSize < 0)
            throw new InvalidDataException("events size " + eventsSize + " is negative");
        var eventsRemainingInputLen = stream.GetRemainingInputLen();
        if (eventsRemainingInputLen >= 0 && eventsRemainingInputLen < eventsSize)
            throw new InvalidDataException("events size " + eventsSize + " exceeds remaining input length " + eventsRemainingInputLen);
        decodedInvokeHostFunctionSuccessPreImage.Events = new ContractEvent[eventsSize];
        for (var i = 0; i < eventsSize; i++)
        {
            decodedInvokeHostFunctionSuccessPreImage.Events[i] = ContractEvent.Decode(stream, maxDepth);
        }
        return decodedInvokeHostFunctionSuccessPreImage;
    }

    public static InvokeHostFunctionSuccessPreImage Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
