// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum IPAddrType
//  {
//      IPv4 = 0,
//      IPv6 = 1
//  };

//  ===========================================================================
public class IPAddrType
{
    public enum IPAddrTypeEnum
    {
        IPv4 = 0,
        IPv6 = 1,
    }

    public IPAddrTypeEnum InnerValue { get; set; }

    public static IPAddrType Create(IPAddrTypeEnum v)
    {
        return new IPAddrType
        {
            InnerValue = v,
        };
    }

    public static IPAddrType Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        var value = stream.ReadInt();
        switch (value)
        {
            case 0: return Create(IPAddrTypeEnum.IPv4);
            case 1: return Create(IPAddrTypeEnum.IPv6);
            default:
                throw new IOException("Unknown enum value: " + value);
        }
    }

    public static IPAddrType Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, IPAddrType value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
