// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct LedgerHeaderExtensionV1
//  {
//      uint32 flags; // LedgerHeaderFlags
//  
//      union switch (int v)
//      {
//      case 0:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public class LedgerHeaderExtensionV1
{
    public Uint32 Flags { get; set; }
    public LedgerHeaderExtensionV1Ext Ext { get; set; }

    public static void Encode(XdrDataOutputStream stream, LedgerHeaderExtensionV1 encodedLedgerHeaderExtensionV1)
    {
        Uint32.Encode(stream, encodedLedgerHeaderExtensionV1.Flags);
        LedgerHeaderExtensionV1Ext.Encode(stream, encodedLedgerHeaderExtensionV1.Ext);
    }

    public static LedgerHeaderExtensionV1 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedLedgerHeaderExtensionV1 = new LedgerHeaderExtensionV1();
        decodedLedgerHeaderExtensionV1.Flags = Uint32.Decode(stream, maxDepth);
        decodedLedgerHeaderExtensionV1.Ext = LedgerHeaderExtensionV1Ext.Decode(stream, maxDepth);
        return decodedLedgerHeaderExtensionV1;
    }

    public static LedgerHeaderExtensionV1 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public class LedgerHeaderExtensionV1Ext
    {
        public int Discriminant { get; set; }

        public static void Encode(XdrDataOutputStream stream, LedgerHeaderExtensionV1Ext encodedLedgerHeaderExtensionV1Ext)
        {
            stream.WriteInt(encodedLedgerHeaderExtensionV1Ext.Discriminant);
            switch (encodedLedgerHeaderExtensionV1Ext.Discriminant)
            {
                case 0:
                    break;
            }
        }

        public static LedgerHeaderExtensionV1Ext Decode(XdrDataInputStream stream, int maxDepth)
        {
            if (maxDepth <= 0)
                throw new IOException("Maximum decoding depth reached");
            maxDepth -= 1;
            var decodedLedgerHeaderExtensionV1Ext = new LedgerHeaderExtensionV1Ext();
            var discriminant = stream.ReadInt();
            decodedLedgerHeaderExtensionV1Ext.Discriminant = discriminant;
            switch (decodedLedgerHeaderExtensionV1Ext.Discriminant)
            {
                case 0:
                    break;
                default:
                    throw new IOException("Unknown discriminant value: " + discriminant);
            }

            return decodedLedgerHeaderExtensionV1Ext;
        }

        public static LedgerHeaderExtensionV1Ext Decode(XdrDataInputStream stream)
        {
            return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
        }
    }
}
