// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct LedgerCloseMetaV2
//  {
//      LedgerCloseMetaExt ext;
//  
//      LedgerHeaderHistoryEntry ledgerHeader;
//  
//      GeneralizedTransactionSet txSet;
//  
//      // NB: transactions are sorted in apply order here
//      // fees for all transactions are processed first
//      // followed by applying transactions
//      TransactionResultMetaV1 txProcessing<>;
//  
//      // upgrades are applied last
//      UpgradeEntryMeta upgradesProcessing<>;
//  
//      // other misc information attached to the ledger close
//      SCPHistoryEntry scpInfo<>;
//  
//      // Size in bytes of live Soroban state, to support downstream
//      // systems calculating storage fees correctly.
//      uint64 totalByteSizeOfLiveSorobanState;
//  
//      // TTL and data/code keys that have been evicted at this ledger.
//      LedgerKey evictedKeys<>;
//  };

//  ===========================================================================
public class LedgerCloseMetaV2
{
    public LedgerCloseMetaExt Ext { get; set; }
    public LedgerHeaderHistoryEntry LedgerHeader { get; set; }
    public GeneralizedTransactionSet TxSet { get; set; }
    public TransactionResultMetaV1[] TxProcessing { get; set; }
    public UpgradeEntryMeta[] UpgradesProcessing { get; set; }
    public SCPHistoryEntry[] ScpInfo { get; set; }
    public Uint64 TotalByteSizeOfLiveSorobanState { get; set; }
    public LedgerKey[] EvictedKeys { get; set; }

    public static void Encode(XdrDataOutputStream stream, LedgerCloseMetaV2 encodedLedgerCloseMetaV2)
    {
        LedgerCloseMetaExt.Encode(stream, encodedLedgerCloseMetaV2.Ext);
        LedgerHeaderHistoryEntry.Encode(stream, encodedLedgerCloseMetaV2.LedgerHeader);
        GeneralizedTransactionSet.Encode(stream, encodedLedgerCloseMetaV2.TxSet);
        var txProcessingsize = encodedLedgerCloseMetaV2.TxProcessing.Length;
        stream.WriteInt(txProcessingsize);
        for (var i = 0; i < txProcessingsize; i++)
        {
            TransactionResultMetaV1.Encode(stream, encodedLedgerCloseMetaV2.TxProcessing[i]);
        }
        var upgradesProcessingsize = encodedLedgerCloseMetaV2.UpgradesProcessing.Length;
        stream.WriteInt(upgradesProcessingsize);
        for (var i = 0; i < upgradesProcessingsize; i++)
        {
            UpgradeEntryMeta.Encode(stream, encodedLedgerCloseMetaV2.UpgradesProcessing[i]);
        }
        var scpInfosize = encodedLedgerCloseMetaV2.ScpInfo.Length;
        stream.WriteInt(scpInfosize);
        for (var i = 0; i < scpInfosize; i++)
        {
            SCPHistoryEntry.Encode(stream, encodedLedgerCloseMetaV2.ScpInfo[i]);
        }
        Uint64.Encode(stream, encodedLedgerCloseMetaV2.TotalByteSizeOfLiveSorobanState);
        var evictedKeyssize = encodedLedgerCloseMetaV2.EvictedKeys.Length;
        stream.WriteInt(evictedKeyssize);
        for (var i = 0; i < evictedKeyssize; i++)
        {
            LedgerKey.Encode(stream, encodedLedgerCloseMetaV2.EvictedKeys[i]);
        }
    }

    public static LedgerCloseMetaV2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedLedgerCloseMetaV2 = new LedgerCloseMetaV2();
        decodedLedgerCloseMetaV2.Ext = LedgerCloseMetaExt.Decode(stream, maxDepth);
        decodedLedgerCloseMetaV2.LedgerHeader = LedgerHeaderHistoryEntry.Decode(stream, maxDepth);
        decodedLedgerCloseMetaV2.TxSet = GeneralizedTransactionSet.Decode(stream, maxDepth);
        var txProcessingsize = stream.ReadInt();
        if (txProcessingsize < 0)
            throw new InvalidDataException("txProcessing size " + txProcessingsize + " is negative");
        var txProcessingRemainingInputLen = stream.GetRemainingInputLen();
        if (txProcessingRemainingInputLen >= 0 && txProcessingRemainingInputLen < txProcessingsize)
            throw new InvalidDataException("txProcessing size " + txProcessingsize + " exceeds remaining input length " + txProcessingRemainingInputLen);
        decodedLedgerCloseMetaV2.TxProcessing = new TransactionResultMetaV1[txProcessingsize];
        for (var i = 0; i < txProcessingsize; i++)
        {
            decodedLedgerCloseMetaV2.TxProcessing[i] = TransactionResultMetaV1.Decode(stream, maxDepth);
        }
        var upgradesProcessingsize = stream.ReadInt();
        if (upgradesProcessingsize < 0)
            throw new InvalidDataException("upgradesProcessing size " + upgradesProcessingsize + " is negative");
        var upgradesProcessingRemainingInputLen = stream.GetRemainingInputLen();
        if (upgradesProcessingRemainingInputLen >= 0 && upgradesProcessingRemainingInputLen < upgradesProcessingsize)
            throw new InvalidDataException("upgradesProcessing size " + upgradesProcessingsize + " exceeds remaining input length " + upgradesProcessingRemainingInputLen);
        decodedLedgerCloseMetaV2.UpgradesProcessing = new UpgradeEntryMeta[upgradesProcessingsize];
        for (var i = 0; i < upgradesProcessingsize; i++)
        {
            decodedLedgerCloseMetaV2.UpgradesProcessing[i] = UpgradeEntryMeta.Decode(stream, maxDepth);
        }
        var scpInfosize = stream.ReadInt();
        if (scpInfosize < 0)
            throw new InvalidDataException("scpInfo size " + scpInfosize + " is negative");
        var scpInfoRemainingInputLen = stream.GetRemainingInputLen();
        if (scpInfoRemainingInputLen >= 0 && scpInfoRemainingInputLen < scpInfosize)
            throw new InvalidDataException("scpInfo size " + scpInfosize + " exceeds remaining input length " + scpInfoRemainingInputLen);
        decodedLedgerCloseMetaV2.ScpInfo = new SCPHistoryEntry[scpInfosize];
        for (var i = 0; i < scpInfosize; i++)
        {
            decodedLedgerCloseMetaV2.ScpInfo[i] = SCPHistoryEntry.Decode(stream, maxDepth);
        }
        decodedLedgerCloseMetaV2.TotalByteSizeOfLiveSorobanState = Uint64.Decode(stream, maxDepth);
        var evictedKeyssize = stream.ReadInt();
        if (evictedKeyssize < 0)
            throw new InvalidDataException("evictedKeys size " + evictedKeyssize + " is negative");
        var evictedKeysRemainingInputLen = stream.GetRemainingInputLen();
        if (evictedKeysRemainingInputLen >= 0 && evictedKeysRemainingInputLen < evictedKeyssize)
            throw new InvalidDataException("evictedKeys size " + evictedKeyssize + " exceeds remaining input length " + evictedKeysRemainingInputLen);
        decodedLedgerCloseMetaV2.EvictedKeys = new LedgerKey[evictedKeyssize];
        for (var i = 0; i < evictedKeyssize; i++)
        {
            decodedLedgerCloseMetaV2.EvictedKeys[i] = LedgerKey.Decode(stream, maxDepth);
        }
        return decodedLedgerCloseMetaV2;
    }

    public static LedgerCloseMetaV2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
