// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct LedgerSCPMessages
//  {
//      uint32 ledgerSeq;
//      SCPEnvelope messages<>;
//  };

//  ===========================================================================
public class LedgerSCPMessages
{
    public Uint32 LedgerSeq { get; set; }
    public SCPEnvelope[] Messages { get; set; }

    public static void Encode(XdrDataOutputStream stream, LedgerSCPMessages encodedLedgerSCPMessages)
    {
        Uint32.Encode(stream, encodedLedgerSCPMessages.LedgerSeq);
        var messagesSize = encodedLedgerSCPMessages.Messages.Length;
        stream.WriteInt(messagesSize);
        for (var i = 0; i < messagesSize; i++)
        {
            SCPEnvelope.Encode(stream, encodedLedgerSCPMessages.Messages[i]);
        }
    }

    public static LedgerSCPMessages Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding LedgerSCPMessages");
        maxDepth -= 1;
        var decodedLedgerSCPMessages = new LedgerSCPMessages();
        decodedLedgerSCPMessages.LedgerSeq = Uint32.Decode(stream, maxDepth);
        var messagesSize = stream.ReadInt();
        if (messagesSize < 0)
            throw new InvalidDataException("messages size " + messagesSize + " is negative");
        decodedLedgerSCPMessages.Messages = new SCPEnvelope[messagesSize];
        for (var i = 0; i < messagesSize; i++)
        {
            decodedLedgerSCPMessages.Messages[i] = SCPEnvelope.Decode(stream, maxDepth);
        }
        return decodedLedgerSCPMessages;
    }

    public static LedgerSCPMessages Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
