// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct LedgerBounds
//  {
//      uint32 minLedger;
//      uint32 maxLedger; // 0 here means no maxLedger
//  };

//  ===========================================================================
public class LedgerBounds
{
    public Uint32 MinLedger { get; set; }
    public Uint32 MaxLedger { get; set; }

    public static void Encode(XdrDataOutputStream stream, LedgerBounds encodedLedgerBounds)
    {
        Uint32.Encode(stream, encodedLedgerBounds.MinLedger);
        Uint32.Encode(stream, encodedLedgerBounds.MaxLedger);
    }

    public static LedgerBounds Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedLedgerBounds = new LedgerBounds();
        decodedLedgerBounds.MinLedger = Uint32.Decode(stream, maxDepth);
        decodedLedgerBounds.MaxLedger = Uint32.Decode(stream, maxDepth);
        return decodedLedgerBounds;
    }

    public static LedgerBounds Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
