// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct Liabilities
//  {
//      int64 buying;
//      int64 selling;
//  };

//  ===========================================================================
public class Liabilities
{
    public Int64 Buying { get; set; }
    public Int64 Selling { get; set; }

    public static void Encode(XdrDataOutputStream stream, Liabilities encodedLiabilities)
    {
        Int64.Encode(stream, encodedLiabilities.Buying);
        Int64.Encode(stream, encodedLiabilities.Selling);
    }

    public static Liabilities Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedLiabilities = new Liabilities();
        decodedLiabilities.Buying = Int64.Decode(stream, maxDepth);
        decodedLiabilities.Selling = Int64.Decode(stream, maxDepth);
        return decodedLiabilities;
    }

    public static Liabilities Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
