// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct LiquidityPoolEntry
//  {
//      PoolID liquidityPoolID;
//  
//      union switch (LiquidityPoolType type)
//      {
//      case LIQUIDITY_POOL_CONSTANT_PRODUCT:
//          struct
//          {
//              LiquidityPoolConstantProductParameters params;
//  
//              int64 reserveA;        // amount of A in the pool
//              int64 reserveB;        // amount of B in the pool
//              int64 totalPoolShares; // total number of pool shares issued
//              int64 poolSharesTrustLineCount; // number of trust lines for the
//                                              // associated pool shares
//          } constantProduct;
//      }
//      body;
//  };

//  ===========================================================================
public class LiquidityPoolEntry
{
    public PoolID LiquidityPoolID { get; set; }
    public LiquidityPoolEntryBody Body { get; set; }

    public static void Encode(XdrDataOutputStream stream, LiquidityPoolEntry encodedLiquidityPoolEntry)
    {
        PoolID.Encode(stream, encodedLiquidityPoolEntry.LiquidityPoolID);
        LiquidityPoolEntryBody.Encode(stream, encodedLiquidityPoolEntry.Body);
    }

    public static LiquidityPoolEntry Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding LiquidityPoolEntry");
        maxDepth -= 1;
        var decodedLiquidityPoolEntry = new LiquidityPoolEntry();
        decodedLiquidityPoolEntry.LiquidityPoolID = PoolID.Decode(stream, maxDepth);
        decodedLiquidityPoolEntry.Body = LiquidityPoolEntryBody.Decode(stream, maxDepth);
        return decodedLiquidityPoolEntry;
    }

    public static LiquidityPoolEntry Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public class LiquidityPoolEntryBody
    {
        public LiquidityPoolType Discriminant { get; set; } = new();

        public LiquidityPoolEntryConstantProduct ConstantProduct { get; set; }

        public static void Encode(XdrDataOutputStream stream, LiquidityPoolEntryBody encodedLiquidityPoolEntryBody)
        {
            stream.WriteInt((int)encodedLiquidityPoolEntryBody.Discriminant.InnerValue);
            switch (encodedLiquidityPoolEntryBody.Discriminant.InnerValue)
            {
                case LiquidityPoolType.LiquidityPoolTypeEnum.LIQUIDITY_POOL_CONSTANT_PRODUCT:
                    LiquidityPoolEntryConstantProduct.Encode(stream, encodedLiquidityPoolEntryBody.ConstantProduct);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + encodedLiquidityPoolEntryBody.Discriminant.InnerValue);
            }
        }

        public static LiquidityPoolEntryBody Decode(XdrDataInputStream stream, int maxDepth)
        {
            if (maxDepth <= 0)
                throw new InvalidDataException("Maximum decoding depth reached while decoding LiquidityPoolEntryBody");
            maxDepth -= 1;
            var decodedLiquidityPoolEntryBody = new LiquidityPoolEntryBody();
            var discriminant = LiquidityPoolType.Decode(stream, maxDepth);
            decodedLiquidityPoolEntryBody.Discriminant = discriminant;
            switch (decodedLiquidityPoolEntryBody.Discriminant.InnerValue)
            {
                case LiquidityPoolType.LiquidityPoolTypeEnum.LIQUIDITY_POOL_CONSTANT_PRODUCT:
                    decodedLiquidityPoolEntryBody.ConstantProduct = LiquidityPoolEntryConstantProduct.Decode(stream, maxDepth);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
            }

            return decodedLiquidityPoolEntryBody;
        }

        public static LiquidityPoolEntryBody Decode(XdrDataInputStream stream)
        {
            return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
        }

        public class LiquidityPoolEntryConstantProduct
        {
            public LiquidityPoolConstantProductParameters Params { get; set; }
            public Int64 ReserveA { get; set; }
            public Int64 ReserveB { get; set; }
            public Int64 TotalPoolShares { get; set; }
            public Int64 PoolSharesTrustLineCount { get; set; }

            public static void Encode(XdrDataOutputStream stream, LiquidityPoolEntryConstantProduct encodedLiquidityPoolEntryConstantProduct)
            {
                LiquidityPoolConstantProductParameters.Encode(stream, encodedLiquidityPoolEntryConstantProduct.Params);
                Int64.Encode(stream, encodedLiquidityPoolEntryConstantProduct.ReserveA);
                Int64.Encode(stream, encodedLiquidityPoolEntryConstantProduct.ReserveB);
                Int64.Encode(stream, encodedLiquidityPoolEntryConstantProduct.TotalPoolShares);
                Int64.Encode(stream, encodedLiquidityPoolEntryConstantProduct.PoolSharesTrustLineCount);
            }

            public static LiquidityPoolEntryConstantProduct Decode(XdrDataInputStream stream, int maxDepth)
            {
                if (maxDepth <= 0)
                    throw new InvalidDataException("Maximum decoding depth reached while decoding LiquidityPoolEntryConstantProduct");
                maxDepth -= 1;
                var decodedLiquidityPoolEntryConstantProduct = new LiquidityPoolEntryConstantProduct();
                decodedLiquidityPoolEntryConstantProduct.Params = LiquidityPoolConstantProductParameters.Decode(stream, maxDepth);
                decodedLiquidityPoolEntryConstantProduct.ReserveA = Int64.Decode(stream, maxDepth);
                decodedLiquidityPoolEntryConstantProduct.ReserveB = Int64.Decode(stream, maxDepth);
                decodedLiquidityPoolEntryConstantProduct.TotalPoolShares = Int64.Decode(stream, maxDepth);
                decodedLiquidityPoolEntryConstantProduct.PoolSharesTrustLineCount = Int64.Decode(stream, maxDepth);
                return decodedLiquidityPoolEntryConstantProduct;
            }

            public static LiquidityPoolEntryConstantProduct Decode(XdrDataInputStream stream)
            {
                return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
            }
        }
    }
}
