// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union Memo switch (MemoType type)
//  {
//  case MEMO_NONE:
//      void;
//  case MEMO_TEXT:
//      string text<28>;
//  case MEMO_ID:
//      uint64 id;
//  case MEMO_HASH:
//      Hash hash; // the hash of what to pull from the content server
//  case MEMO_RETURN:
//      Hash retHash; // the hash of the tx you are rejecting
//  };

//  ===========================================================================
public class Memo
{
    public MemoType Discriminant { get; set; } = new();

    public string Text { get; set; }
    public Uint64 Id { get; set; }
    public Hash Hash { get; set; }
    public Hash RetHash { get; set; }

    public static void Encode(XdrDataOutputStream stream, Memo encodedMemo)
    {
        stream.WriteInt((int)encodedMemo.Discriminant.InnerValue);
        switch (encodedMemo.Discriminant.InnerValue)
        {
            case MemoType.MemoTypeEnum.MEMO_NONE:
                break;
            case MemoType.MemoTypeEnum.MEMO_TEXT:
                stream.WriteString(encodedMemo.Text);
                break;
            case MemoType.MemoTypeEnum.MEMO_ID:
                Uint64.Encode(stream, encodedMemo.Id);
                break;
            case MemoType.MemoTypeEnum.MEMO_HASH:
                Hash.Encode(stream, encodedMemo.Hash);
                break;
            case MemoType.MemoTypeEnum.MEMO_RETURN:
                Hash.Encode(stream, encodedMemo.RetHash);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + encodedMemo.Discriminant.InnerValue);
        }
    }

    public static Memo Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding Memo");
        maxDepth -= 1;
        var decodedMemo = new Memo();
        var discriminant = MemoType.Decode(stream, maxDepth);
        decodedMemo.Discriminant = discriminant;
        switch (decodedMemo.Discriminant.InnerValue)
        {
            case MemoType.MemoTypeEnum.MEMO_NONE:
                break;
            case MemoType.MemoTypeEnum.MEMO_TEXT:
                decodedMemo.Text = stream.ReadString();
                break;
            case MemoType.MemoTypeEnum.MEMO_ID:
                decodedMemo.Id = Uint64.Decode(stream, maxDepth);
                break;
            case MemoType.MemoTypeEnum.MEMO_HASH:
                decodedMemo.Hash = Hash.Decode(stream, maxDepth);
                break;
            case MemoType.MemoTypeEnum.MEMO_RETURN:
                decodedMemo.RetHash = Hash.Decode(stream, maxDepth);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
        }

        return decodedMemo;
    }

    public static Memo Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
