// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union MuxedAccount switch (CryptoKeyType type)
//  {
//  case KEY_TYPE_ED25519:
//      uint256 ed25519;
//  case KEY_TYPE_MUXED_ED25519:
//      struct
//      {
//          uint64 id;
//          uint256 ed25519;
//      } med25519;
//  };

//  ===========================================================================
public class MuxedAccount
{
    public CryptoKeyType Discriminant { get; set; } = new();

    public Uint256 Ed25519 { get; set; }
    public MuxedAccountMed25519 Med25519 { get; set; }

    public static void Encode(XdrDataOutputStream stream, MuxedAccount encodedMuxedAccount)
    {
        stream.WriteInt((int)encodedMuxedAccount.Discriminant.InnerValue);
        switch (encodedMuxedAccount.Discriminant.InnerValue)
        {
            case CryptoKeyType.CryptoKeyTypeEnum.KEY_TYPE_ED25519:
                Uint256.Encode(stream, encodedMuxedAccount.Ed25519);
                break;
            case CryptoKeyType.CryptoKeyTypeEnum.KEY_TYPE_MUXED_ED25519:
                MuxedAccountMed25519.Encode(stream, encodedMuxedAccount.Med25519);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + encodedMuxedAccount.Discriminant.InnerValue);
        }
    }

    public static MuxedAccount Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding MuxedAccount");
        maxDepth -= 1;
        var decodedMuxedAccount = new MuxedAccount();
        var discriminant = CryptoKeyType.Decode(stream, maxDepth);
        decodedMuxedAccount.Discriminant = discriminant;
        switch (decodedMuxedAccount.Discriminant.InnerValue)
        {
            case CryptoKeyType.CryptoKeyTypeEnum.KEY_TYPE_ED25519:
                decodedMuxedAccount.Ed25519 = Uint256.Decode(stream, maxDepth);
                break;
            case CryptoKeyType.CryptoKeyTypeEnum.KEY_TYPE_MUXED_ED25519:
                decodedMuxedAccount.Med25519 = MuxedAccountMed25519.Decode(stream, maxDepth);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
        }

        return decodedMuxedAccount;
    }

    public static MuxedAccount Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public class MuxedAccountMed25519
    {
        public Uint64 Id { get; set; }
        public Uint256 Ed25519 { get; set; }

        public static void Encode(XdrDataOutputStream stream, MuxedAccountMed25519 encodedMuxedAccountMed25519)
        {
            Uint64.Encode(stream, encodedMuxedAccountMed25519.Id);
            Uint256.Encode(stream, encodedMuxedAccountMed25519.Ed25519);
        }

        public static MuxedAccountMed25519 Decode(XdrDataInputStream stream, int maxDepth)
        {
            if (maxDepth <= 0)
                throw new InvalidDataException("Maximum decoding depth reached while decoding MuxedAccountMed25519");
            maxDepth -= 1;
            var decodedMuxedAccountMed25519 = new MuxedAccountMed25519();
            decodedMuxedAccountMed25519.Id = Uint64.Decode(stream, maxDepth);
            decodedMuxedAccountMed25519.Ed25519 = Uint256.Decode(stream, maxDepth);
            return decodedMuxedAccountMed25519;
        }

        public static MuxedAccountMed25519 Decode(XdrDataInputStream stream)
        {
            return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
        }
    }
}
