// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct OperationMetaV2
//  {
//      ExtensionPoint ext;
//  
//      LedgerEntryChanges changes;
//  
//      ContractEvent events<>;
//  };

//  ===========================================================================
public class OperationMetaV2
{
    public ExtensionPoint Ext { get; set; }
    public LedgerEntryChanges Changes { get; set; }
    public ContractEvent[] Events { get; set; }

    public static void Encode(XdrDataOutputStream stream, OperationMetaV2 encodedOperationMetaV2)
    {
        ExtensionPoint.Encode(stream, encodedOperationMetaV2.Ext);
        LedgerEntryChanges.Encode(stream, encodedOperationMetaV2.Changes);
        var eventssize = encodedOperationMetaV2.Events.Length;
        stream.WriteInt(eventssize);
        for (var i = 0; i < eventssize; i++)
        {
            ContractEvent.Encode(stream, encodedOperationMetaV2.Events[i]);
        }
    }

    public static OperationMetaV2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedOperationMetaV2 = new OperationMetaV2();
        decodedOperationMetaV2.Ext = ExtensionPoint.Decode(stream, maxDepth);
        decodedOperationMetaV2.Changes = LedgerEntryChanges.Decode(stream, maxDepth);
        var eventssize = stream.ReadInt();
        if (eventssize < 0)
            throw new InvalidDataException("events size " + eventssize + " is negative");
        decodedOperationMetaV2.Events = new ContractEvent[eventssize];
        for (var i = 0; i < eventssize; i++)
        {
            decodedOperationMetaV2.Events[i] = ContractEvent.Decode(stream, maxDepth);
        }
        return decodedOperationMetaV2;
    }

    public static OperationMetaV2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
