// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct OperationMeta
//  {
//      LedgerEntryChanges changes;
//  };

//  ===========================================================================
public class OperationMeta
{
    public LedgerEntryChanges Changes { get; set; }

    public static void Encode(XdrDataOutputStream stream, OperationMeta encodedOperationMeta)
    {
        LedgerEntryChanges.Encode(stream, encodedOperationMeta.Changes);
    }

    public static OperationMeta Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedOperationMeta = new OperationMeta();
        decodedOperationMeta.Changes = LedgerEntryChanges.Decode(stream, maxDepth);
        return decodedOperationMeta;
    }

    public static OperationMeta Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
