// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct PathPaymentStrictSendOp
//  {
//      Asset sendAsset;  // asset we pay with
//      int64 sendAmount; // amount of sendAsset to send (excluding fees)
//  
//      MuxedAccount destination; // recipient of the payment
//      Asset destAsset;          // what they end up with
//      int64 destMin;            // the minimum amount of dest asset to
//                                // be received
//                                // The operation will fail if it can't be met
//  
//      Asset path<5>; // additional hops it must go through to get there
//  };

//  ===========================================================================
public class PathPaymentStrictSendOp
{
    public Asset SendAsset { get; set; }
    public Int64 SendAmount { get; set; }
    public MuxedAccount Destination { get; set; }
    public Asset DestAsset { get; set; }
    public Int64 DestMin { get; set; }
    public Asset[] Path { get; set; }

    public static void Encode(XdrDataOutputStream stream, PathPaymentStrictSendOp encodedPathPaymentStrictSendOp)
    {
        Asset.Encode(stream, encodedPathPaymentStrictSendOp.SendAsset);
        Int64.Encode(stream, encodedPathPaymentStrictSendOp.SendAmount);
        MuxedAccount.Encode(stream, encodedPathPaymentStrictSendOp.Destination);
        Asset.Encode(stream, encodedPathPaymentStrictSendOp.DestAsset);
        Int64.Encode(stream, encodedPathPaymentStrictSendOp.DestMin);
        var pathsize = encodedPathPaymentStrictSendOp.Path.Length;
        if (pathsize > 5)
            throw new ArgumentException("path size " + pathsize + " exceeds max size 5");
        stream.WriteInt(pathsize);
        for (var i = 0; i < pathsize; i++)
        {
            Asset.Encode(stream, encodedPathPaymentStrictSendOp.Path[i]);
        }
    }

    public static PathPaymentStrictSendOp Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedPathPaymentStrictSendOp = new PathPaymentStrictSendOp();
        decodedPathPaymentStrictSendOp.SendAsset = Asset.Decode(stream, maxDepth);
        decodedPathPaymentStrictSendOp.SendAmount = Int64.Decode(stream, maxDepth);
        decodedPathPaymentStrictSendOp.Destination = MuxedAccount.Decode(stream, maxDepth);
        decodedPathPaymentStrictSendOp.DestAsset = Asset.Decode(stream, maxDepth);
        decodedPathPaymentStrictSendOp.DestMin = Int64.Decode(stream, maxDepth);
        var pathsize = stream.ReadInt();
        if (pathsize < 0)
            throw new InvalidDataException("path size " + pathsize + " is negative");
        if (pathsize > 5)
            throw new InvalidDataException("path size " + pathsize + " exceeds max size 5");
        var pathRemainingInputLen = stream.GetRemainingInputLen();
        if (pathRemainingInputLen >= 0 && pathRemainingInputLen < pathsize)
            throw new InvalidDataException("path size " + pathsize + " exceeds remaining input length " + pathRemainingInputLen);
        decodedPathPaymentStrictSendOp.Path = new Asset[pathsize];
        for (var i = 0; i < pathsize; i++)
        {
            decodedPathPaymentStrictSendOp.Path[i] = Asset.Decode(stream, maxDepth);
        }
        return decodedPathPaymentStrictSendOp;
    }

    public static PathPaymentStrictSendOp Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
