// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct PeerAddress
//  {
//      union switch (IPAddrType type)
//      {
//      case IPv4:
//          opaque ipv4[4];
//      case IPv6:
//          opaque ipv6[16];
//      }
//      ip;
//      uint32 port;
//      uint32 numFailures;
//  };

//  ===========================================================================
public class PeerAddress
{
    public PeerAddressIp Ip { get; set; }
    public Uint32 Port { get; set; }
    public Uint32 NumFailures { get; set; }

    public static void Encode(XdrDataOutputStream stream, PeerAddress encodedPeerAddress)
    {
        PeerAddressIp.Encode(stream, encodedPeerAddress.Ip);
        Uint32.Encode(stream, encodedPeerAddress.Port);
        Uint32.Encode(stream, encodedPeerAddress.NumFailures);
    }

    public static PeerAddress Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding PeerAddress");
        maxDepth -= 1;
        var decodedPeerAddress = new PeerAddress();
        decodedPeerAddress.Ip = PeerAddressIp.Decode(stream, maxDepth);
        decodedPeerAddress.Port = Uint32.Decode(stream, maxDepth);
        decodedPeerAddress.NumFailures = Uint32.Decode(stream, maxDepth);
        return decodedPeerAddress;
    }

    public static PeerAddress Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public class PeerAddressIp
    {
        public IPAddrType Discriminant { get; set; } = new();

        public byte[] Ipv4 { get; set; }
        public byte[] Ipv6 { get; set; }

        public static void Encode(XdrDataOutputStream stream, PeerAddressIp encodedPeerAddressIp)
        {
            stream.WriteInt((int)encodedPeerAddressIp.Discriminant.InnerValue);
            switch (encodedPeerAddressIp.Discriminant.InnerValue)
            {
                case IPAddrType.IPAddrTypeEnum.IPv4:
                    var ipv4Size = encodedPeerAddressIp.Ipv4.Length;
                    if (ipv4Size != 4)
                        throw new ArgumentException("ipv4 size " + ipv4Size + " does not match fixed size 4");
                    stream.Write(encodedPeerAddressIp.Ipv4, 0, ipv4Size);
                    break;
                case IPAddrType.IPAddrTypeEnum.IPv6:
                    var ipv6Size = encodedPeerAddressIp.Ipv6.Length;
                    if (ipv6Size != 16)
                        throw new ArgumentException("ipv6 size " + ipv6Size + " does not match fixed size 16");
                    stream.Write(encodedPeerAddressIp.Ipv6, 0, ipv6Size);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + encodedPeerAddressIp.Discriminant.InnerValue);
            }
        }

        public static PeerAddressIp Decode(XdrDataInputStream stream, int maxDepth)
        {
            if (maxDepth <= 0)
                throw new InvalidDataException("Maximum decoding depth reached while decoding PeerAddressIp");
            maxDepth -= 1;
            var decodedPeerAddressIp = new PeerAddressIp();
            var discriminant = IPAddrType.Decode(stream, maxDepth);
            decodedPeerAddressIp.Discriminant = discriminant;
            switch (decodedPeerAddressIp.Discriminant.InnerValue)
            {
                case IPAddrType.IPAddrTypeEnum.IPv4:
                    var ipv4Size = 4;
                    decodedPeerAddressIp.Ipv4 = new byte[ipv4Size];
                    stream.Read(decodedPeerAddressIp.Ipv4, 0, ipv4Size);
                    break;
                case IPAddrType.IPAddrTypeEnum.IPv6:
                    var ipv6Size = 16;
                    decodedPeerAddressIp.Ipv6 = new byte[ipv6Size];
                    stream.Read(decodedPeerAddressIp.Ipv6, 0, ipv6Size);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
            }

            return decodedPeerAddressIp;
        }

        public static PeerAddressIp Decode(XdrDataInputStream stream)
        {
            return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
        }
    }
}
