// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct PersistedSCPStateV1
//  {
//  	// Tx sets are saved separately
//  	SCPEnvelope scpEnvelopes<>;
//  	SCPQuorumSet quorumSets<>;
//  };

//  ===========================================================================
public class PersistedSCPStateV1
{
    public SCPEnvelope[] ScpEnvelopes { get; set; }
    public SCPQuorumSet[] QuorumSets { get; set; }

    public static void Encode(XdrDataOutputStream stream, PersistedSCPStateV1 encodedPersistedSCPStateV1)
    {
        var scpEnvelopesSize = encodedPersistedSCPStateV1.ScpEnvelopes.Length;
        stream.WriteInt(scpEnvelopesSize);
        for (var i = 0; i < scpEnvelopesSize; i++)
        {
            SCPEnvelope.Encode(stream, encodedPersistedSCPStateV1.ScpEnvelopes[i]);
        }
        var quorumSetsSize = encodedPersistedSCPStateV1.QuorumSets.Length;
        stream.WriteInt(quorumSetsSize);
        for (var i = 0; i < quorumSetsSize; i++)
        {
            SCPQuorumSet.Encode(stream, encodedPersistedSCPStateV1.QuorumSets[i]);
        }
    }

    public static PersistedSCPStateV1 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding PersistedSCPStateV1");
        maxDepth -= 1;
        var decodedPersistedSCPStateV1 = new PersistedSCPStateV1();
        var scpEnvelopesSize = stream.ReadInt();
        if (scpEnvelopesSize < 0)
            throw new InvalidDataException("scpEnvelopes size " + scpEnvelopesSize + " is negative");
        var scpEnvelopesRemainingInputLen = stream.GetRemainingInputLen();
        if (scpEnvelopesRemainingInputLen >= 0 && scpEnvelopesRemainingInputLen < scpEnvelopesSize)
            throw new InvalidDataException("scpEnvelopes size " + scpEnvelopesSize + " exceeds remaining input length " + scpEnvelopesRemainingInputLen);
        decodedPersistedSCPStateV1.ScpEnvelopes = new SCPEnvelope[scpEnvelopesSize];
        for (var i = 0; i < scpEnvelopesSize; i++)
        {
            decodedPersistedSCPStateV1.ScpEnvelopes[i] = SCPEnvelope.Decode(stream, maxDepth);
        }
        var quorumSetsSize = stream.ReadInt();
        if (quorumSetsSize < 0)
            throw new InvalidDataException("quorumSets size " + quorumSetsSize + " is negative");
        var quorumSetsRemainingInputLen = stream.GetRemainingInputLen();
        if (quorumSetsRemainingInputLen >= 0 && quorumSetsRemainingInputLen < quorumSetsSize)
            throw new InvalidDataException("quorumSets size " + quorumSetsSize + " exceeds remaining input length " + quorumSetsRemainingInputLen);
        decodedPersistedSCPStateV1.QuorumSets = new SCPQuorumSet[quorumSetsSize];
        for (var i = 0; i < quorumSetsSize; i++)
        {
            decodedPersistedSCPStateV1.QuorumSets[i] = SCPQuorumSet.Decode(stream, maxDepth);
        }
        return decodedPersistedSCPStateV1;
    }

    public static PersistedSCPStateV1 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
