// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum PublicKeyType
//  {
//      PUBLIC_KEY_TYPE_ED25519 = KEY_TYPE_ED25519
//  };

//  ===========================================================================
public class PublicKeyType
{
    public enum PublicKeyTypeEnum
    {
        PUBLIC_KEY_TYPE_ED25519 = 0,
    }

    public PublicKeyTypeEnum InnerValue { get; set; }

    public static PublicKeyType Create(PublicKeyTypeEnum v)
    {
        return new PublicKeyType
        {
            InnerValue = v,
        };
    }

    public static PublicKeyType Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        var value = stream.ReadInt();
        switch (value)
        {
            case 0: return Create(PublicKeyTypeEnum.PUBLIC_KEY_TYPE_ED25519);
            default:
                throw new InvalidDataException("Unknown enum value: " + value);
        }
    }

    public static PublicKeyType Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, PublicKeyType value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
