// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum SCAddressType
//  {
//      SC_ADDRESS_TYPE_ACCOUNT = 0,
//      SC_ADDRESS_TYPE_CONTRACT = 1,
//      SC_ADDRESS_TYPE_MUXED_ACCOUNT = 2,
//      SC_ADDRESS_TYPE_CLAIMABLE_BALANCE = 3,
//      SC_ADDRESS_TYPE_LIQUIDITY_POOL = 4
//  };

//  ===========================================================================
public class SCAddressType
{
    public enum SCAddressTypeEnum
    {
        SC_ADDRESS_TYPE_ACCOUNT = 0,
        SC_ADDRESS_TYPE_CONTRACT = 1,
        SC_ADDRESS_TYPE_MUXED_ACCOUNT = 2,
        SC_ADDRESS_TYPE_CLAIMABLE_BALANCE = 3,
        SC_ADDRESS_TYPE_LIQUIDITY_POOL = 4,
    }

    public SCAddressTypeEnum InnerValue { get; set; }

    public static SCAddressType Create(SCAddressTypeEnum v)
    {
        return new SCAddressType
        {
            InnerValue = v,
        };
    }

    public static SCAddressType Decode(XdrDataInputStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 0: return Create(SCAddressTypeEnum.SC_ADDRESS_TYPE_ACCOUNT);
            case 1: return Create(SCAddressTypeEnum.SC_ADDRESS_TYPE_CONTRACT);
            case 2: return Create(SCAddressTypeEnum.SC_ADDRESS_TYPE_MUXED_ACCOUNT);
            case 3: return Create(SCAddressTypeEnum.SC_ADDRESS_TYPE_CLAIMABLE_BALANCE);
            case 4: return Create(SCAddressTypeEnum.SC_ADDRESS_TYPE_LIQUIDITY_POOL);
            default:
                throw new Exception("Unknown enum value: " + value);
        }
    }

    public static void Encode(XdrDataOutputStream stream, SCAddressType value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}