// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef opaque SCBytes<>;

//  ===========================================================================
public class SCBytes
{
    public SCBytes()
    {
    }

    public SCBytes(byte[] value)
    {
        InnerValue = value;
    }

    public byte[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, SCBytes encodedSCBytes)
    {
        var sCBytesSize = encodedSCBytes.InnerValue.Length;
        stream.WriteInt(sCBytesSize);
        stream.Write(encodedSCBytes.InnerValue, 0, sCBytesSize);
    }

    public static SCBytes Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SCBytes");
        maxDepth -= 1;
        var decodedSCBytes = new SCBytes();
        var sCBytesSize = stream.ReadInt();
        if (sCBytesSize < 0)
            throw new InvalidDataException("SCBytes size " + sCBytesSize + " is negative");
        var sCBytesRemainingInputLen = stream.GetRemainingInputLen();
        if (sCBytesRemainingInputLen >= 0 && sCBytesRemainingInputLen < sCBytesSize)
            throw new InvalidDataException("SCBytes size " + sCBytesSize + " exceeds remaining input length " + sCBytesRemainingInputLen);
        decodedSCBytes.InnerValue = new byte[sCBytesSize];
        stream.Read(decodedSCBytes.InnerValue, 0, sCBytesSize);
        return decodedSCBytes;
    }

    public static SCBytes Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
