// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SCContractInstance {
//      ContractExecutable executable;
//      SCMap* storage;
//  };

//  ===========================================================================
public class SCContractInstance
{
    public ContractExecutable Executable { get; set; }
    public SCMap Storage { get; set; }

    public static void Encode(XdrDataOutputStream stream, SCContractInstance encodedSCContractInstance)
    {
        ContractExecutable.Encode(stream, encodedSCContractInstance.Executable);
        if (encodedSCContractInstance.Storage != null)
        {
            stream.WriteInt(1);
            SCMap.Encode(stream, encodedSCContractInstance.Storage);
        }
        else
        {
            stream.WriteInt(0);
        }
    }

    public static SCContractInstance Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SCContractInstance");
        maxDepth -= 1;
        var decodedSCContractInstance = new SCContractInstance();
        decodedSCContractInstance.Executable = ContractExecutable.Decode(stream, maxDepth);
        var StoragePresent = stream.ReadInt();
        if (StoragePresent != 0)
        {
            decodedSCContractInstance.Storage = SCMap.Decode(stream, maxDepth);
        }
        return decodedSCContractInstance;
    }

    public static SCContractInstance Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
