// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SCMetaV0
//  {
//      string key<>;
//      string val<>;
//  };

//  ===========================================================================
public class SCMetaV0
{
    public string Key { get; set; }
    public string Val { get; set; }

    public static void Encode(XdrDataOutputStream stream, SCMetaV0 encodedSCMetaV0)
    {
        stream.WriteString(encodedSCMetaV0.Key);
        stream.WriteString(encodedSCMetaV0.Val);
    }

    public static SCMetaV0 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SCMetaV0");
        maxDepth -= 1;
        var decodedSCMetaV0 = new SCMetaV0();
        decodedSCMetaV0.Key = stream.ReadString();
        decodedSCMetaV0.Val = stream.ReadString();
        return decodedSCMetaV0;
    }

    public static SCMetaV0 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
