// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union SCMetaEntry switch (SCMetaKind kind)
//  {
//  case SC_META_V0:
//      SCMetaV0 v0;
//  };

//  ===========================================================================
public class SCMetaEntry
{
    public SCMetaKind Discriminant { get; set; } = new();

    public SCMetaV0 V0 { get; set; }

    public static void Encode(XdrDataOutputStream stream, SCMetaEntry encodedSCMetaEntry)
    {
        stream.WriteInt((int)encodedSCMetaEntry.Discriminant.InnerValue);
        switch (encodedSCMetaEntry.Discriminant.InnerValue)
        {
            case SCMetaKind.SCMetaKindEnum.SC_META_V0:
                SCMetaV0.Encode(stream, encodedSCMetaEntry.V0);
                break;
        }
    }

    public static SCMetaEntry Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedSCMetaEntry = new SCMetaEntry();
        var discriminant = SCMetaKind.Decode(stream, maxDepth);
        decodedSCMetaEntry.Discriminant = discriminant;
        switch (decodedSCMetaEntry.Discriminant.InnerValue)
        {
            case SCMetaKind.SCMetaKindEnum.SC_META_V0:
                decodedSCMetaEntry.V0 = SCMetaV0.Decode(stream, maxDepth);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
        }

        return decodedSCMetaEntry;
    }

    public static SCMetaEntry Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
