// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SCPBallot
//  {
//      uint32 counter; // n
//      Value value;    // x
//  };

//  ===========================================================================
public class SCPBallot
{
    public Uint32 Counter { get; set; }
    public Value Value { get; set; }

    public static void Encode(XdrDataOutputStream stream, SCPBallot encodedSCPBallot)
    {
        Uint32.Encode(stream, encodedSCPBallot.Counter);
        Value.Encode(stream, encodedSCPBallot.Value);
    }

    public static SCPBallot Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SCPBallot");
        maxDepth -= 1;
        var decodedSCPBallot = new SCPBallot();
        decodedSCPBallot.Counter = Uint32.Decode(stream, maxDepth);
        decodedSCPBallot.Value = Value.Decode(stream, maxDepth);
        return decodedSCPBallot;
    }

    public static SCPBallot Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
