// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union SCPHistoryEntry switch (int v)
//  {
//  case 0:
//      SCPHistoryEntryV0 v0;
//  };

//  ===========================================================================
public class SCPHistoryEntry
{
    public int Discriminant { get; set; }

    public SCPHistoryEntryV0 V0 { get; set; }

    public static void Encode(XdrDataOutputStream stream, SCPHistoryEntry encodedSCPHistoryEntry)
    {
        stream.WriteInt(encodedSCPHistoryEntry.Discriminant);
        switch (encodedSCPHistoryEntry.Discriminant)
        {
            case 0:
                SCPHistoryEntryV0.Encode(stream, encodedSCPHistoryEntry.V0);
                break;
        }
    }

    public static SCPHistoryEntry Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedSCPHistoryEntry = new SCPHistoryEntry();
        var discriminant = stream.ReadInt();
        decodedSCPHistoryEntry.Discriminant = discriminant;
        switch (decodedSCPHistoryEntry.Discriminant)
        {
            case 0:
                decodedSCPHistoryEntry.V0 = SCPHistoryEntryV0.Decode(stream, maxDepth);
                break;
            default:
                throw new IOException("Unknown discriminant value: " + discriminant);
        }

        return decodedSCPHistoryEntry;
    }

    public static SCPHistoryEntry Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
