// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum SCSpecUDTUnionCaseV0Kind
//  {
//      SC_SPEC_UDT_UNION_CASE_VOID_V0 = 0,
//      SC_SPEC_UDT_UNION_CASE_TUPLE_V0 = 1
//  };

//  ===========================================================================
public class SCSpecUDTUnionCaseV0Kind
{
    public enum SCSpecUDTUnionCaseV0KindEnum
    {
        SC_SPEC_UDT_UNION_CASE_VOID_V0 = 0,
        SC_SPEC_UDT_UNION_CASE_TUPLE_V0 = 1,
    }

    public SCSpecUDTUnionCaseV0KindEnum InnerValue { get; set; }

    public static SCSpecUDTUnionCaseV0Kind Create(SCSpecUDTUnionCaseV0KindEnum v)
    {
        return new SCSpecUDTUnionCaseV0Kind
        {
            InnerValue = v,
        };
    }

    public static SCSpecUDTUnionCaseV0Kind Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        _ = maxDepth;
        var value = stream.ReadInt();
        switch (value)
        {
            case 0: return Create(SCSpecUDTUnionCaseV0KindEnum.SC_SPEC_UDT_UNION_CASE_VOID_V0);
            case 1: return Create(SCSpecUDTUnionCaseV0KindEnum.SC_SPEC_UDT_UNION_CASE_TUPLE_V0);
            default:
                throw new InvalidDataException("Unknown enum value: " + value);
        }
    }

    public static SCSpecUDTUnionCaseV0Kind Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, SCSpecUDTUnionCaseV0Kind value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
