// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SCSpecEventV0
//  {
//      string doc<SC_SPEC_DOC_LIMIT>;
//      string lib<80>;
//      SCSymbol name;
//      SCSymbol prefixTopics<2>;
//      SCSpecEventParamV0 params<50>;
//      SCSpecEventDataFormat dataFormat;
//  };

//  ===========================================================================
public class SCSpecEventV0
{
    public string Doc { get; set; }
    public string Lib { get; set; }
    public SCSymbol Name { get; set; }
    public SCSymbol[] PrefixTopics { get; set; }
    public SCSpecEventParamV0[] Params { get; set; }
    public SCSpecEventDataFormat DataFormat { get; set; }

    public static void Encode(XdrDataOutputStream stream, SCSpecEventV0 encodedSCSpecEventV0)
    {
        stream.WriteString(encodedSCSpecEventV0.Doc);
        stream.WriteString(encodedSCSpecEventV0.Lib);
        SCSymbol.Encode(stream, encodedSCSpecEventV0.Name);
        var prefixTopicsSize = encodedSCSpecEventV0.PrefixTopics.Length;
        if (prefixTopicsSize > 2)
            throw new ArgumentException("prefixTopics size " + prefixTopicsSize + " exceeds max size 2");
        stream.WriteInt(prefixTopicsSize);
        for (var i = 0; i < prefixTopicsSize; i++)
        {
            SCSymbol.Encode(stream, encodedSCSpecEventV0.PrefixTopics[i]);
        }
        var paramsSize = encodedSCSpecEventV0.Params.Length;
        if (paramsSize > 50)
            throw new ArgumentException("params size " + paramsSize + " exceeds max size 50");
        stream.WriteInt(paramsSize);
        for (var i = 0; i < paramsSize; i++)
        {
            SCSpecEventParamV0.Encode(stream, encodedSCSpecEventV0.Params[i]);
        }
        SCSpecEventDataFormat.Encode(stream, encodedSCSpecEventV0.DataFormat);
    }

    public static SCSpecEventV0 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SCSpecEventV0");
        maxDepth -= 1;
        var decodedSCSpecEventV0 = new SCSpecEventV0();
        decodedSCSpecEventV0.Doc = stream.ReadString();
        decodedSCSpecEventV0.Lib = stream.ReadString();
        decodedSCSpecEventV0.Name = SCSymbol.Decode(stream, maxDepth);
        var prefixTopicsSize = stream.ReadInt();
        if (prefixTopicsSize < 0)
            throw new InvalidDataException("prefixTopics size " + prefixTopicsSize + " is negative");
        if (prefixTopicsSize > 2)
            throw new InvalidDataException("prefixTopics size " + prefixTopicsSize + " exceeds max size 2");
        var prefixTopicsRemainingInputLen = stream.GetRemainingInputLen();
        if (prefixTopicsRemainingInputLen >= 0 && prefixTopicsRemainingInputLen < prefixTopicsSize)
            throw new InvalidDataException("prefixTopics size " + prefixTopicsSize + " exceeds remaining input length " + prefixTopicsRemainingInputLen);
        decodedSCSpecEventV0.PrefixTopics = new SCSymbol[prefixTopicsSize];
        for (var i = 0; i < prefixTopicsSize; i++)
        {
            decodedSCSpecEventV0.PrefixTopics[i] = SCSymbol.Decode(stream, maxDepth);
        }
        var paramsSize = stream.ReadInt();
        if (paramsSize < 0)
            throw new InvalidDataException("params size " + paramsSize + " is negative");
        if (paramsSize > 50)
            throw new InvalidDataException("params size " + paramsSize + " exceeds max size 50");
        var paramsRemainingInputLen = stream.GetRemainingInputLen();
        if (paramsRemainingInputLen >= 0 && paramsRemainingInputLen < paramsSize)
            throw new InvalidDataException("params size " + paramsSize + " exceeds remaining input length " + paramsRemainingInputLen);
        decodedSCSpecEventV0.Params = new SCSpecEventParamV0[paramsSize];
        for (var i = 0; i < paramsSize; i++)
        {
            decodedSCSpecEventV0.Params[i] = SCSpecEventParamV0.Decode(stream, maxDepth);
        }
        decodedSCSpecEventV0.DataFormat = SCSpecEventDataFormat.Decode(stream, maxDepth);
        return decodedSCSpecEventV0;
    }

    public static SCSpecEventV0 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
