// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum SCSpecEventParamLocationV0
//  {
//      SC_SPEC_EVENT_PARAM_LOCATION_DATA = 0,
//      SC_SPEC_EVENT_PARAM_LOCATION_TOPIC_LIST = 1
//  };

//  ===========================================================================
public class SCSpecEventParamLocationV0
{
    public enum SCSpecEventParamLocationV0Enum
    {
        SC_SPEC_EVENT_PARAM_LOCATION_DATA = 0,
        SC_SPEC_EVENT_PARAM_LOCATION_TOPIC_LIST = 1,
    }

    public SCSpecEventParamLocationV0Enum InnerValue { get; set; }

    public static SCSpecEventParamLocationV0 Create(SCSpecEventParamLocationV0Enum v)
    {
        return new SCSpecEventParamLocationV0
        {
            InnerValue = v,
        };
    }

    public static SCSpecEventParamLocationV0 Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        var value = stream.ReadInt();
        switch (value)
        {
            case 0: return Create(SCSpecEventParamLocationV0Enum.SC_SPEC_EVENT_PARAM_LOCATION_DATA);
            case 1: return Create(SCSpecEventParamLocationV0Enum.SC_SPEC_EVENT_PARAM_LOCATION_TOPIC_LIST);
            default:
                throw new IOException("Unknown enum value: " + value);
        }
    }

    public static SCSpecEventParamLocationV0 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, SCSpecEventParamLocationV0 value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
