// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum SCSpecEventDataFormat
//  {
//      SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE = 0,
//      SC_SPEC_EVENT_DATA_FORMAT_VEC = 1,
//      SC_SPEC_EVENT_DATA_FORMAT_MAP = 2
//  };

//  ===========================================================================
public class SCSpecEventDataFormat
{
    public enum SCSpecEventDataFormatEnum
    {
        SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE = 0,
        SC_SPEC_EVENT_DATA_FORMAT_VEC = 1,
        SC_SPEC_EVENT_DATA_FORMAT_MAP = 2,
    }

    public SCSpecEventDataFormatEnum InnerValue { get; set; }

    public static SCSpecEventDataFormat Create(SCSpecEventDataFormatEnum v)
    {
        return new SCSpecEventDataFormat
        {
            InnerValue = v,
        };
    }

    public static SCSpecEventDataFormat Decode(XdrDataInputStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 0: return Create(SCSpecEventDataFormatEnum.SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE);
            case 1: return Create(SCSpecEventDataFormatEnum.SC_SPEC_EVENT_DATA_FORMAT_VEC);
            case 2: return Create(SCSpecEventDataFormatEnum.SC_SPEC_EVENT_DATA_FORMAT_MAP);
            default:
                throw new Exception("Unknown enum value: " + value);
        }
    }

    public static void Encode(XdrDataOutputStream stream, SCSpecEventDataFormat value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}