// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef string SCString<>;

//  ===========================================================================
public class SCString
{
    public SCString()
    {
    }

    public SCString(string value)
    {
        InnerValue = value;
    }

    /// <summary>
    ///     The raw bytes of the string exactly as they appear on the wire. They are not
    ///     guaranteed to be valid UTF-8 and are encoded and decoded verbatim.
    /// </summary>
    public byte[] InnerBytes { get; set; }

    /// <summary>
    ///     A UTF-8 view of <see cref="InnerBytes" />. The getter replaces invalid UTF-8 with
    ///     U+FFFD, so it is lossy for non-UTF-8 bytes, and decodes again on every read; the setter
    ///     replaces <see cref="InnerBytes" /> with the UTF-8 encoding of the value, in which an
    ///     unpaired surrogate becomes U+FFFD.
    /// </summary>
    public string InnerValue
    {
        get => InnerBytes == null ? null : System.Text.Encoding.UTF8.GetString(InnerBytes);
        set => InnerBytes = value == null ? null : System.Text.Encoding.UTF8.GetBytes(value);
    }

    public static void Encode(XdrDataOutputStream stream, SCString encodedSCString)
    {
        stream.WriteStringBytes(encodedSCString.InnerBytes);
    }

    public static SCString Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SCString");
        maxDepth -= 1;
        var decodedSCString = new SCString();
        decodedSCString.InnerBytes = stream.ReadStringBytes();
        return decodedSCString;
    }

    public static SCString Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
