// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef SCVal SCVec<>;

//  ===========================================================================
public class SCVec
{
    public SCVec()
    {
    }

    public SCVec(SCVal[] value)
    {
        InnerValue = value;
    }

    public SCVal[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, SCVec encodedSCVec)
    {
        var SCVecsize = encodedSCVec.InnerValue.Length;
        stream.WriteInt(SCVecsize);
        for (var i = 0; i < SCVecsize; i++)
        {
            SCVal.Encode(stream, encodedSCVec.InnerValue[i]);
        }
    }

    public static SCVec Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SCVec");
        maxDepth -= 1;
        var decodedSCVec = new SCVec();
        var SCVecsize = stream.ReadInt();
        if (SCVecsize < 0)
            throw new InvalidDataException("SCVec size " + SCVecsize + " is negative");
        decodedSCVec.InnerValue = new SCVal[SCVecsize];
        for (var i = 0; i < SCVecsize; i++)
        {
            decodedSCVec.InnerValue[i] = SCVal.Decode(stream, maxDepth);
        }
        return decodedSCVec;
    }

    public static SCVec Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
