// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SendMoreExtended
//  {
//      uint32 numMessages;
//      uint32 numBytes;
//  };

//  ===========================================================================
public class SendMoreExtended
{
    public Uint32 NumMessages { get; set; }
    public Uint32 NumBytes { get; set; }

    public static void Encode(XdrDataOutputStream stream, SendMoreExtended encodedSendMoreExtended)
    {
        Uint32.Encode(stream, encodedSendMoreExtended.NumMessages);
        Uint32.Encode(stream, encodedSendMoreExtended.NumBytes);
    }

    public static SendMoreExtended Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedSendMoreExtended = new SendMoreExtended();
        decodedSendMoreExtended.NumMessages = Uint32.Decode(stream, maxDepth);
        decodedSendMoreExtended.NumBytes = Uint32.Decode(stream, maxDepth);
        return decodedSendMoreExtended;
    }

    public static SendMoreExtended Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
