// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SerializedBinaryFuseFilter
//  {
//      BinaryFuseFilterType type;
//  
//      // Seed used to hash input to filter
//      ShortHashSeed inputHashSeed;
//  
//      // Seed used for internal filter hash operations
//      ShortHashSeed filterSeed;
//      uint32 segmentLength;
//      uint32 segementLengthMask;
//      uint32 segmentCount;
//      uint32 segmentCountLength;
//      uint32 fingerprintLength; // Length in terms of element count, not bytes
//  
//      // Array of uint8_t, uint16_t, or uint32_t depending on filter type
//      opaque fingerprints<>;
//  };

//  ===========================================================================
public class SerializedBinaryFuseFilter
{
    public BinaryFuseFilterType Type { get; set; }
    public ShortHashSeed InputHashSeed { get; set; }
    public ShortHashSeed FilterSeed { get; set; }
    public Uint32 SegmentLength { get; set; }
    public Uint32 SegementLengthMask { get; set; }
    public Uint32 SegmentCount { get; set; }
    public Uint32 SegmentCountLength { get; set; }
    public Uint32 FingerprintLength { get; set; }
    public byte[] Fingerprints { get; set; }

    public static void Encode(XdrDataOutputStream stream, SerializedBinaryFuseFilter encodedSerializedBinaryFuseFilter)
    {
        BinaryFuseFilterType.Encode(stream, encodedSerializedBinaryFuseFilter.Type);
        ShortHashSeed.Encode(stream, encodedSerializedBinaryFuseFilter.InputHashSeed);
        ShortHashSeed.Encode(stream, encodedSerializedBinaryFuseFilter.FilterSeed);
        Uint32.Encode(stream, encodedSerializedBinaryFuseFilter.SegmentLength);
        Uint32.Encode(stream, encodedSerializedBinaryFuseFilter.SegementLengthMask);
        Uint32.Encode(stream, encodedSerializedBinaryFuseFilter.SegmentCount);
        Uint32.Encode(stream, encodedSerializedBinaryFuseFilter.SegmentCountLength);
        Uint32.Encode(stream, encodedSerializedBinaryFuseFilter.FingerprintLength);
        var fingerprintssize = encodedSerializedBinaryFuseFilter.Fingerprints.Length;
        stream.WriteInt(fingerprintssize);
        stream.Write(encodedSerializedBinaryFuseFilter.Fingerprints, 0, fingerprintssize);
    }

    public static SerializedBinaryFuseFilter Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedSerializedBinaryFuseFilter = new SerializedBinaryFuseFilter();
        decodedSerializedBinaryFuseFilter.Type = BinaryFuseFilterType.Decode(stream, maxDepth);
        decodedSerializedBinaryFuseFilter.InputHashSeed = ShortHashSeed.Decode(stream, maxDepth);
        decodedSerializedBinaryFuseFilter.FilterSeed = ShortHashSeed.Decode(stream, maxDepth);
        decodedSerializedBinaryFuseFilter.SegmentLength = Uint32.Decode(stream, maxDepth);
        decodedSerializedBinaryFuseFilter.SegementLengthMask = Uint32.Decode(stream, maxDepth);
        decodedSerializedBinaryFuseFilter.SegmentCount = Uint32.Decode(stream, maxDepth);
        decodedSerializedBinaryFuseFilter.SegmentCountLength = Uint32.Decode(stream, maxDepth);
        decodedSerializedBinaryFuseFilter.FingerprintLength = Uint32.Decode(stream, maxDepth);
        var fingerprintssize = stream.ReadInt();
        if (fingerprintssize < 0)
            throw new IOException("fingerprints size " + fingerprintssize + " is negative");
        var fingerprintsRemainingInputLen = stream.GetRemainingInputLen();
        if (fingerprintsRemainingInputLen >= 0 && fingerprintsRemainingInputLen < fingerprintssize)
            throw new IOException("fingerprints size " + fingerprintssize + " exceeds remaining input length " + fingerprintsRemainingInputLen);
        decodedSerializedBinaryFuseFilter.Fingerprints = new byte[fingerprintssize];
        stream.Read(decodedSerializedBinaryFuseFilter.Fingerprints, 0, fingerprintssize);
        return decodedSerializedBinaryFuseFilter;
    }

    public static SerializedBinaryFuseFilter Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
