// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ShortHashSeed
//  {
//      opaque seed[16];
//  };

//  ===========================================================================
public class ShortHashSeed
{
    public byte[] Seed { get; set; }

    public static void Encode(XdrDataOutputStream stream, ShortHashSeed encodedShortHashSeed)
    {
        var seedSize = encodedShortHashSeed.Seed.Length;
        if (seedSize != 16)
            throw new ArgumentException("seed size " + seedSize + " does not match fixed size 16");
        stream.Write(encodedShortHashSeed.Seed, 0, seedSize);
    }

    public static ShortHashSeed Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding ShortHashSeed");
        maxDepth -= 1;
        var decodedShortHashSeed = new ShortHashSeed();
        var seedSize = 16;
        decodedShortHashSeed.Seed = new byte[seedSize];
        stream.Read(decodedShortHashSeed.Seed, 0, seedSize);
        return decodedShortHashSeed;
    }

    public static ShortHashSeed Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
