// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct ShortHashSeed
//  {
//      opaque seed[16];
//  };

//  ===========================================================================
public class ShortHashSeed
{
    public byte[] Seed { get; set; }

    public static void Encode(XdrDataOutputStream stream, ShortHashSeed encodedShortHashSeed)
    {
        var seedsize = encodedShortHashSeed.Seed.Length;
        if (seedsize != 16)
            throw new ArgumentException("seed size " + seedsize + " does not match fixed size 16");
        stream.Write(encodedShortHashSeed.Seed, 0, seedsize);
    }

    public static ShortHashSeed Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedShortHashSeed = new ShortHashSeed();
        var seedsize = 16;
        decodedShortHashSeed.Seed = new byte[seedsize];
        stream.Read(decodedShortHashSeed.Seed, 0, seedsize);
        return decodedShortHashSeed;
    }

    public static ShortHashSeed Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
