// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SignedTimeSlicedSurveyRequestMessage
//  {
//      Signature requestSignature;
//      TimeSlicedSurveyRequestMessage request;
//  };

//  ===========================================================================
public class SignedTimeSlicedSurveyRequestMessage
{
    public Signature RequestSignature { get; set; }
    public TimeSlicedSurveyRequestMessage Request { get; set; }

    public static void Encode(XdrDataOutputStream stream,
        SignedTimeSlicedSurveyRequestMessage encodedSignedTimeSlicedSurveyRequestMessage)
    {
        Signature.Encode(stream, encodedSignedTimeSlicedSurveyRequestMessage.RequestSignature);
        TimeSlicedSurveyRequestMessage.Encode(stream, encodedSignedTimeSlicedSurveyRequestMessage.Request);
    }

    public static SignedTimeSlicedSurveyRequestMessage Decode(XdrDataInputStream stream)
    {
        var decodedSignedTimeSlicedSurveyRequestMessage = new SignedTimeSlicedSurveyRequestMessage();
        decodedSignedTimeSlicedSurveyRequestMessage.RequestSignature = Signature.Decode(stream);
        decodedSignedTimeSlicedSurveyRequestMessage.Request = TimeSlicedSurveyRequestMessage.Decode(stream);
        return decodedSignedTimeSlicedSurveyRequestMessage;
    }
}