// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SignedTimeSlicedSurveyStopCollectingMessage
//  {
//      Signature signature;
//      TimeSlicedSurveyStopCollectingMessage stopCollecting;
//  };

//  ===========================================================================
public class SignedTimeSlicedSurveyStopCollectingMessage
{
    public Signature Signature { get; set; }
    public TimeSlicedSurveyStopCollectingMessage StopCollecting { get; set; }

    public static void Encode(XdrDataOutputStream stream,
        SignedTimeSlicedSurveyStopCollectingMessage encodedSignedTimeSlicedSurveyStopCollectingMessage)
    {
        Signature.Encode(stream, encodedSignedTimeSlicedSurveyStopCollectingMessage.Signature);
        TimeSlicedSurveyStopCollectingMessage.Encode(stream,
            encodedSignedTimeSlicedSurveyStopCollectingMessage.StopCollecting);
    }

    public static SignedTimeSlicedSurveyStopCollectingMessage Decode(XdrDataInputStream stream)
    {
        var decodedSignedTimeSlicedSurveyStopCollectingMessage = new SignedTimeSlicedSurveyStopCollectingMessage();
        decodedSignedTimeSlicedSurveyStopCollectingMessage.Signature = Signature.Decode(stream);
        decodedSignedTimeSlicedSurveyStopCollectingMessage.StopCollecting =
            TimeSlicedSurveyStopCollectingMessage.Decode(stream);
        return decodedSignedTimeSlicedSurveyStopCollectingMessage;
    }
}