// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union SorobanCredentials switch (SorobanCredentialsType type)
//  {
//  case SOROBAN_CREDENTIALS_SOURCE_ACCOUNT:
//      void;
//  case SOROBAN_CREDENTIALS_ADDRESS:
//      SorobanAddressCredentials address;
//  case SOROBAN_CREDENTIALS_ADDRESS_V2:
//      SorobanAddressCredentials addressV2;
//  case SOROBAN_CREDENTIALS_ADDRESS_WITH_DELEGATES:
//      SorobanAddressCredentialsWithDelegates addressWithDelegates;
//  };

//  ===========================================================================
public class SorobanCredentials
{
    public SorobanCredentialsType Discriminant { get; set; } = new();

    public SorobanAddressCredentials Address { get; set; }
    public SorobanAddressCredentials AddressV2 { get; set; }
    public SorobanAddressCredentialsWithDelegates AddressWithDelegates { get; set; }

    public static void Encode(XdrDataOutputStream stream, SorobanCredentials encodedSorobanCredentials)
    {
        stream.WriteInt((int)encodedSorobanCredentials.Discriminant.InnerValue);
        switch (encodedSorobanCredentials.Discriminant.InnerValue)
        {
            case SorobanCredentialsType.SorobanCredentialsTypeEnum.SOROBAN_CREDENTIALS_SOURCE_ACCOUNT:
                break;
            case SorobanCredentialsType.SorobanCredentialsTypeEnum.SOROBAN_CREDENTIALS_ADDRESS:
                SorobanAddressCredentials.Encode(stream, encodedSorobanCredentials.Address);
                break;
            case SorobanCredentialsType.SorobanCredentialsTypeEnum.SOROBAN_CREDENTIALS_ADDRESS_V2:
                SorobanAddressCredentials.Encode(stream, encodedSorobanCredentials.AddressV2);
                break;
            case SorobanCredentialsType.SorobanCredentialsTypeEnum.SOROBAN_CREDENTIALS_ADDRESS_WITH_DELEGATES:
                SorobanAddressCredentialsWithDelegates.Encode(stream, encodedSorobanCredentials.AddressWithDelegates);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + encodedSorobanCredentials.Discriminant.InnerValue);
        }
    }

    public static SorobanCredentials Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SorobanCredentials");
        maxDepth -= 1;
        var decodedSorobanCredentials = new SorobanCredentials();
        var discriminant = SorobanCredentialsType.Decode(stream, maxDepth);
        decodedSorobanCredentials.Discriminant = discriminant;
        switch (decodedSorobanCredentials.Discriminant.InnerValue)
        {
            case SorobanCredentialsType.SorobanCredentialsTypeEnum.SOROBAN_CREDENTIALS_SOURCE_ACCOUNT:
                break;
            case SorobanCredentialsType.SorobanCredentialsTypeEnum.SOROBAN_CREDENTIALS_ADDRESS:
                decodedSorobanCredentials.Address = SorobanAddressCredentials.Decode(stream, maxDepth);
                break;
            case SorobanCredentialsType.SorobanCredentialsTypeEnum.SOROBAN_CREDENTIALS_ADDRESS_V2:
                decodedSorobanCredentials.AddressV2 = SorobanAddressCredentials.Decode(stream, maxDepth);
                break;
            case SorobanCredentialsType.SorobanCredentialsTypeEnum.SOROBAN_CREDENTIALS_ADDRESS_WITH_DELEGATES:
                decodedSorobanCredentials.AddressWithDelegates = SorobanAddressCredentialsWithDelegates.Decode(stream, maxDepth);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
        }

        return decodedSorobanCredentials;
    }

    public static SorobanCredentials Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
