// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef SorobanAuthorizationEntry SorobanAuthorizationEntries<>;

//  ===========================================================================
public class SorobanAuthorizationEntries
{
    public SorobanAuthorizationEntries()
    {
    }

    public SorobanAuthorizationEntries(SorobanAuthorizationEntry[] value)
    {
        InnerValue = value;
    }

    public SorobanAuthorizationEntry[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, SorobanAuthorizationEntries encodedSorobanAuthorizationEntries)
    {
        var sorobanAuthorizationEntriesSize = encodedSorobanAuthorizationEntries.InnerValue.Length;
        stream.WriteInt(sorobanAuthorizationEntriesSize);
        for (var i = 0; i < sorobanAuthorizationEntriesSize; i++)
        {
            SorobanAuthorizationEntry.Encode(stream, encodedSorobanAuthorizationEntries.InnerValue[i]);
        }
    }

    public static SorobanAuthorizationEntries Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SorobanAuthorizationEntries");
        maxDepth -= 1;
        var decodedSorobanAuthorizationEntries = new SorobanAuthorizationEntries();
        var sorobanAuthorizationEntriesSize = stream.ReadInt();
        if (sorobanAuthorizationEntriesSize < 0)
            throw new InvalidDataException("SorobanAuthorizationEntries size " + sorobanAuthorizationEntriesSize + " is negative");
        decodedSorobanAuthorizationEntries.InnerValue = new SorobanAuthorizationEntry[sorobanAuthorizationEntriesSize];
        for (var i = 0; i < sorobanAuthorizationEntriesSize; i++)
        {
            decodedSorobanAuthorizationEntries.InnerValue[i] = SorobanAuthorizationEntry.Decode(stream, maxDepth);
        }
        return decodedSorobanAuthorizationEntries;
    }

    public static SorobanAuthorizationEntries Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
