// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SorobanResourcesExtV0
//  {
//      // Vector of indices representing what Soroban
//      // entries in the footprint are archived, based on the
//      // order of keys provided in the readWrite footprint.
//      uint32 archivedSorobanEntries<>;
//  };

//  ===========================================================================
public class SorobanResourcesExtV0
{
    public Uint32[] ArchivedSorobanEntries { get; set; }

    public static void Encode(XdrDataOutputStream stream, SorobanResourcesExtV0 encodedSorobanResourcesExtV0)
    {
        var archivedSorobanEntriessize = encodedSorobanResourcesExtV0.ArchivedSorobanEntries.Length;
        stream.WriteInt(archivedSorobanEntriessize);
        for (var i = 0; i < archivedSorobanEntriessize; i++)
        {
            Uint32.Encode(stream, encodedSorobanResourcesExtV0.ArchivedSorobanEntries[i]);
        }
    }

    public static SorobanResourcesExtV0 Decode(XdrDataInputStream stream)
    {
        var decodedSorobanResourcesExtV0 = new SorobanResourcesExtV0();
        var archivedSorobanEntriessize = stream.ReadInt();
        decodedSorobanResourcesExtV0.ArchivedSorobanEntries = new Uint32[archivedSorobanEntriessize];
        for (var i = 0; i < archivedSorobanEntriessize; i++)
        {
            decodedSorobanResourcesExtV0.ArchivedSorobanEntries[i] = Uint32.Decode(stream);
        }
        return decodedSorobanResourcesExtV0;
    }
}