// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SorobanDelegateSignature
//  {
//      SCAddress address;
//      SCVal signature;
//      SorobanDelegateSignature nestedDelegates<>;
//  };

//  ===========================================================================
public class SorobanDelegateSignature
{
    public SCAddress Address { get; set; }
    public SCVal Signature { get; set; }
    public SorobanDelegateSignature[] NestedDelegates { get; set; }

    public static void Encode(XdrDataOutputStream stream, SorobanDelegateSignature encodedSorobanDelegateSignature)
    {
        SCAddress.Encode(stream, encodedSorobanDelegateSignature.Address);
        SCVal.Encode(stream, encodedSorobanDelegateSignature.Signature);
        var nestedDelegatesSize = encodedSorobanDelegateSignature.NestedDelegates.Length;
        stream.WriteInt(nestedDelegatesSize);
        for (var i = 0; i < nestedDelegatesSize; i++)
        {
            SorobanDelegateSignature.Encode(stream, encodedSorobanDelegateSignature.NestedDelegates[i]);
        }
    }

    public static SorobanDelegateSignature Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SorobanDelegateSignature");
        maxDepth -= 1;
        var decodedSorobanDelegateSignature = new SorobanDelegateSignature();
        decodedSorobanDelegateSignature.Address = SCAddress.Decode(stream, maxDepth);
        decodedSorobanDelegateSignature.Signature = SCVal.Decode(stream, maxDepth);
        var nestedDelegatesSize = stream.ReadInt();
        if (nestedDelegatesSize < 0)
            throw new InvalidDataException("nestedDelegates size " + nestedDelegatesSize + " is negative");
        var nestedDelegatesRemainingInputLen = stream.GetRemainingInputLen();
        if (nestedDelegatesRemainingInputLen >= 0 && nestedDelegatesRemainingInputLen < nestedDelegatesSize)
            throw new InvalidDataException("nestedDelegates size " + nestedDelegatesSize + " exceeds remaining input length " + nestedDelegatesRemainingInputLen);
        decodedSorobanDelegateSignature.NestedDelegates = new SorobanDelegateSignature[nestedDelegatesSize];
        for (var i = 0; i < nestedDelegatesSize; i++)
        {
            decodedSorobanDelegateSignature.NestedDelegates[i] = SorobanDelegateSignature.Decode(stream, maxDepth);
        }
        return decodedSorobanDelegateSignature;
    }

    public static SorobanDelegateSignature Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
