// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SorobanTransactionMetaV2
//  {
//      SorobanTransactionMetaExt ext;
//  
//      SCVal* returnValue;
//  };

//  ===========================================================================
public class SorobanTransactionMetaV2
{
    public SorobanTransactionMetaExt Ext { get; set; }
    public SCVal ReturnValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, SorobanTransactionMetaV2 encodedSorobanTransactionMetaV2)
    {
        SorobanTransactionMetaExt.Encode(stream, encodedSorobanTransactionMetaV2.Ext);
        if (encodedSorobanTransactionMetaV2.ReturnValue != null)
        {
            stream.WriteInt(1);
            SCVal.Encode(stream, encodedSorobanTransactionMetaV2.ReturnValue);
        }
        else
        {
            stream.WriteInt(0);
        }
    }

    public static SorobanTransactionMetaV2 Decode(XdrDataInputStream stream)
    {
        var decodedSorobanTransactionMetaV2 = new SorobanTransactionMetaV2();
        decodedSorobanTransactionMetaV2.Ext = SorobanTransactionMetaExt.Decode(stream);
        var ReturnValuePresent = stream.ReadInt();
        if (ReturnValuePresent != 0)
        {
            decodedSorobanTransactionMetaV2.ReturnValue = SCVal.Decode(stream);
        }
        return decodedSorobanTransactionMetaV2;
    }
}