// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SorobanResources
//  {   
//      // The ledger footprint of the transaction.
//      LedgerFootprint footprint;
//      // The maximum number of instructions this transaction can use
//      uint32 instructions; 
//  
//      // The maximum number of bytes this transaction can read from disk backed entries
//      uint32 diskReadBytes;
//      // The maximum number of bytes this transaction can write to ledger
//      uint32 writeBytes;
//  };

//  ===========================================================================
public class SorobanResources
{
    public LedgerFootprint Footprint { get; set; }
    public Uint32 Instructions { get; set; }
    public Uint32 DiskReadBytes { get; set; }
    public Uint32 WriteBytes { get; set; }

    public static void Encode(XdrDataOutputStream stream, SorobanResources encodedSorobanResources)
    {
        LedgerFootprint.Encode(stream, encodedSorobanResources.Footprint);
        Uint32.Encode(stream, encodedSorobanResources.Instructions);
        Uint32.Encode(stream, encodedSorobanResources.DiskReadBytes);
        Uint32.Encode(stream, encodedSorobanResources.WriteBytes);
    }

    public static SorobanResources Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding SorobanResources");
        maxDepth -= 1;
        var decodedSorobanResources = new SorobanResources();
        decodedSorobanResources.Footprint = LedgerFootprint.Decode(stream, maxDepth);
        decodedSorobanResources.Instructions = Uint32.Decode(stream, maxDepth);
        decodedSorobanResources.DiskReadBytes = Uint32.Decode(stream, maxDepth);
        decodedSorobanResources.WriteBytes = Uint32.Decode(stream, maxDepth);
        return decodedSorobanResources;
    }

    public static SorobanResources Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
