// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct StellarValue
//  {
//      Hash txSetHash;      // transaction set to apply to previous ledger
//      TimePoint closeTime; // network close time
//  
//      // upgrades to apply to the previous ledger (usually empty)
//      // this is a vector of encoded 'LedgerUpgrade' so that nodes can drop
//      // unknown steps during consensus if needed.
//      // see notes below on 'LedgerUpgrade' for more detail
//      // max size is dictated by number of upgrade types (+ room for future)
//      UpgradeType upgrades<6>;
//  
//      // reserved for future use
//      union switch (StellarValueType v)
//      {
//      case STELLAR_VALUE_BASIC:
//          void;
//      case STELLAR_VALUE_SIGNED:
//          LedgerCloseValueSignature lcValueSignature;
//      }
//      ext;
//  };

//  ===========================================================================
public class StellarValue
{
    public Hash TxSetHash { get; set; }
    public TimePoint CloseTime { get; set; }
    public UpgradeType[] Upgrades { get; set; }
    public StellarValueExt Ext { get; set; }

    public static void Encode(XdrDataOutputStream stream, StellarValue encodedStellarValue)
    {
        Hash.Encode(stream, encodedStellarValue.TxSetHash);
        TimePoint.Encode(stream, encodedStellarValue.CloseTime);
        var upgradessize = encodedStellarValue.Upgrades.Length;
        if (upgradessize > 6)
            throw new ArgumentException("upgrades size " + upgradessize + " exceeds max size 6");
        stream.WriteInt(upgradessize);
        for (var i = 0; i < upgradessize; i++)
        {
            UpgradeType.Encode(stream, encodedStellarValue.Upgrades[i]);
        }
        StellarValueExt.Encode(stream, encodedStellarValue.Ext);
    }

    public static StellarValue Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedStellarValue = new StellarValue();
        decodedStellarValue.TxSetHash = Hash.Decode(stream, maxDepth);
        decodedStellarValue.CloseTime = TimePoint.Decode(stream, maxDepth);
        var upgradessize = stream.ReadInt();
        if (upgradessize < 0)
            throw new InvalidDataException("upgrades size " + upgradessize + " is negative");
        if (upgradessize > 6)
            throw new InvalidDataException("upgrades size " + upgradessize + " exceeds max size 6");
        decodedStellarValue.Upgrades = new UpgradeType[upgradessize];
        for (var i = 0; i < upgradessize; i++)
        {
            decodedStellarValue.Upgrades[i] = UpgradeType.Decode(stream, maxDepth);
        }
        decodedStellarValue.Ext = StellarValueExt.Decode(stream, maxDepth);
        return decodedStellarValue;
    }

    public static StellarValue Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public class StellarValueExt
    {
        public StellarValueType Discriminant { get; set; } = new();

        public LedgerCloseValueSignature LcValueSignature { get; set; }

        public static void Encode(XdrDataOutputStream stream, StellarValueExt encodedStellarValueExt)
        {
            stream.WriteInt((int)encodedStellarValueExt.Discriminant.InnerValue);
            switch (encodedStellarValueExt.Discriminant.InnerValue)
            {
                case StellarValueType.StellarValueTypeEnum.STELLAR_VALUE_BASIC:
                    break;
                case StellarValueType.StellarValueTypeEnum.STELLAR_VALUE_SIGNED:
                    LedgerCloseValueSignature.Encode(stream, encodedStellarValueExt.LcValueSignature);
                    break;
            }
        }

        public static StellarValueExt Decode(XdrDataInputStream stream, int maxDepth)
        {
            if (maxDepth <= 0)
                throw new InvalidDataException("Maximum decoding depth reached");
            maxDepth -= 1;
            var decodedStellarValueExt = new StellarValueExt();
            var discriminant = StellarValueType.Decode(stream, maxDepth);
            decodedStellarValueExt.Discriminant = discriminant;
            switch (decodedStellarValueExt.Discriminant.InnerValue)
            {
                case StellarValueType.StellarValueTypeEnum.STELLAR_VALUE_BASIC:
                    break;
                case StellarValueType.StellarValueTypeEnum.STELLAR_VALUE_SIGNED:
                    decodedStellarValueExt.LcValueSignature = LedgerCloseValueSignature.Decode(stream, maxDepth);
                    break;
                default:
                    throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
            }

            return decodedStellarValueExt;
        }

        public static StellarValueExt Decode(XdrDataInputStream stream)
        {
            return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
        }
    }
}
