// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union StoredTransactionSet switch (int v)
//  {
//  case 0:
//  	TransactionSet txSet;
//  case 1:
//  	GeneralizedTransactionSet generalizedTxSet;
//  };

//  ===========================================================================
public class StoredTransactionSet
{
    public int Discriminant { get; set; }

    public TransactionSet TxSet { get; set; }
    public GeneralizedTransactionSet GeneralizedTxSet { get; set; }

    public static void Encode(XdrDataOutputStream stream, StoredTransactionSet encodedStoredTransactionSet)
    {
        stream.WriteInt(encodedStoredTransactionSet.Discriminant);
        switch (encodedStoredTransactionSet.Discriminant)
        {
            case 0:
                TransactionSet.Encode(stream, encodedStoredTransactionSet.TxSet);
                break;
            case 1:
                GeneralizedTransactionSet.Encode(stream, encodedStoredTransactionSet.GeneralizedTxSet);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + encodedStoredTransactionSet.Discriminant);
        }
    }

    public static StoredTransactionSet Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding StoredTransactionSet");
        maxDepth -= 1;
        var decodedStoredTransactionSet = new StoredTransactionSet();
        var discriminant = stream.ReadInt();
        decodedStoredTransactionSet.Discriminant = discriminant;
        switch (decodedStoredTransactionSet.Discriminant)
        {
            case 0:
                decodedStoredTransactionSet.TxSet = TransactionSet.Decode(stream, maxDepth);
                break;
            case 1:
                decodedStoredTransactionSet.GeneralizedTxSet = GeneralizedTransactionSet.Decode(stream, maxDepth);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant);
        }

        return decodedStoredTransactionSet;
    }

    public static StoredTransactionSet Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
