// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef string string32<32>;

//  ===========================================================================
public class String32
{
    public String32()
    {
    }

    public String32(string value)
    {
        InnerValue = value;
    }

    public string InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, String32 encodedString32)
    {
        stream.WriteString(encodedString32.InnerValue);
    }

    public static String32 Decode(XdrDataInputStream stream)
    {
        var decodedString32 = new String32();
        decodedString32.InnerValue = stream.ReadString();
        return decodedString32;
    }
}