// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum SurveyMessageResponseType
//  {
//      SURVEY_TOPOLOGY_RESPONSE_V2 = 2
//  };

//  ===========================================================================
public class SurveyMessageResponseType
{
    public enum SurveyMessageResponseTypeEnum
    {
        SURVEY_TOPOLOGY_RESPONSE_V2 = 2,
    }

    public SurveyMessageResponseTypeEnum InnerValue { get; set; }

    public static SurveyMessageResponseType Create(SurveyMessageResponseTypeEnum v)
    {
        return new SurveyMessageResponseType
        {
            InnerValue = v,
        };
    }

    public static SurveyMessageResponseType Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        _ = maxDepth;
        var value = stream.ReadInt();
        switch (value)
        {
            case 2: return Create(SurveyMessageResponseTypeEnum.SURVEY_TOPOLOGY_RESPONSE_V2);
            default:
                throw new InvalidDataException("Unknown enum value: " + value);
        }
    }

    public static SurveyMessageResponseType Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, SurveyMessageResponseType value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
