// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct SurveyResponseMessage
//  {
//      NodeID surveyorPeerID;
//      NodeID surveyedPeerID;
//      uint32 ledgerNum;
//      SurveyMessageCommandType commandType;
//      EncryptedBody encryptedBody;
//  };

//  ===========================================================================
public class SurveyResponseMessage
{
    public NodeID SurveyorPeerID { get; set; }
    public NodeID SurveyedPeerID { get; set; }
    public Uint32 LedgerNum { get; set; }
    public SurveyMessageCommandType CommandType { get; set; }
    public EncryptedBody EncryptedBody { get; set; }

    public static void Encode(XdrDataOutputStream stream, SurveyResponseMessage encodedSurveyResponseMessage)
    {
        NodeID.Encode(stream, encodedSurveyResponseMessage.SurveyorPeerID);
        NodeID.Encode(stream, encodedSurveyResponseMessage.SurveyedPeerID);
        Uint32.Encode(stream, encodedSurveyResponseMessage.LedgerNum);
        SurveyMessageCommandType.Encode(stream, encodedSurveyResponseMessage.CommandType);
        EncryptedBody.Encode(stream, encodedSurveyResponseMessage.EncryptedBody);
    }

    public static SurveyResponseMessage Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedSurveyResponseMessage = new SurveyResponseMessage();
        decodedSurveyResponseMessage.SurveyorPeerID = NodeID.Decode(stream, maxDepth);
        decodedSurveyResponseMessage.SurveyedPeerID = NodeID.Decode(stream, maxDepth);
        decodedSurveyResponseMessage.LedgerNum = Uint32.Decode(stream, maxDepth);
        decodedSurveyResponseMessage.CommandType = SurveyMessageCommandType.Decode(stream, maxDepth);
        decodedSurveyResponseMessage.EncryptedBody = EncryptedBody.Decode(stream, maxDepth);
        return decodedSurveyResponseMessage;
    }

    public static SurveyResponseMessage Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
