// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum SurveyMessageCommandType
//  {
//      TIME_SLICED_SURVEY_TOPOLOGY = 1
//  };

//  ===========================================================================
public class SurveyMessageCommandType
{
    public enum SurveyMessageCommandTypeEnum
    {
        TIME_SLICED_SURVEY_TOPOLOGY = 1,
    }

    public SurveyMessageCommandTypeEnum InnerValue { get; set; }

    public static SurveyMessageCommandType Create(SurveyMessageCommandTypeEnum v)
    {
        return new SurveyMessageCommandType
        {
            InnerValue = v,
        };
    }

    public static SurveyMessageCommandType Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        _ = maxDepth;
        var value = stream.ReadInt();
        switch (value)
        {
            case 1: return Create(SurveyMessageCommandTypeEnum.TIME_SLICED_SURVEY_TOPOLOGY);
            default:
                throw new InvalidDataException("Unknown enum value: " + value);
        }
    }

    public static SurveyMessageCommandType Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, SurveyMessageCommandType value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
