// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct TimeSlicedSurveyStartCollectingMessage
//  {
//      NodeID surveyorID;
//      uint32 nonce;
//      uint32 ledgerNum;
//  };

//  ===========================================================================
public class TimeSlicedSurveyStartCollectingMessage
{
    public NodeID SurveyorID { get; set; }
    public Uint32 Nonce { get; set; }
    public Uint32 LedgerNum { get; set; }

    public static void Encode(XdrDataOutputStream stream,
        TimeSlicedSurveyStartCollectingMessage encodedTimeSlicedSurveyStartCollectingMessage)
    {
        NodeID.Encode(stream, encodedTimeSlicedSurveyStartCollectingMessage.SurveyorID);
        Uint32.Encode(stream, encodedTimeSlicedSurveyStartCollectingMessage.Nonce);
        Uint32.Encode(stream, encodedTimeSlicedSurveyStartCollectingMessage.LedgerNum);
    }

    public static TimeSlicedSurveyStartCollectingMessage Decode(XdrDataInputStream stream)
    {
        var decodedTimeSlicedSurveyStartCollectingMessage = new TimeSlicedSurveyStartCollectingMessage();
        decodedTimeSlicedSurveyStartCollectingMessage.SurveyorID = NodeID.Decode(stream);
        decodedTimeSlicedSurveyStartCollectingMessage.Nonce = Uint32.Decode(stream);
        decodedTimeSlicedSurveyStartCollectingMessage.LedgerNum = Uint32.Decode(stream);
        return decodedTimeSlicedSurveyStartCollectingMessage;
    }
}