// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct TimeSlicedSurveyRequestMessage
//  {
//      SurveyRequestMessage request;
//      uint32 nonce;
//      uint32 inboundPeersIndex;
//      uint32 outboundPeersIndex;
//  };

//  ===========================================================================
public class TimeSlicedSurveyRequestMessage
{
    public SurveyRequestMessage Request { get; set; }
    public Uint32 Nonce { get; set; }
    public Uint32 InboundPeersIndex { get; set; }
    public Uint32 OutboundPeersIndex { get; set; }

    public static void Encode(XdrDataOutputStream stream, TimeSlicedSurveyRequestMessage encodedTimeSlicedSurveyRequestMessage)
    {
        SurveyRequestMessage.Encode(stream, encodedTimeSlicedSurveyRequestMessage.Request);
        Uint32.Encode(stream, encodedTimeSlicedSurveyRequestMessage.Nonce);
        Uint32.Encode(stream, encodedTimeSlicedSurveyRequestMessage.InboundPeersIndex);
        Uint32.Encode(stream, encodedTimeSlicedSurveyRequestMessage.OutboundPeersIndex);
    }

    public static TimeSlicedSurveyRequestMessage Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedTimeSlicedSurveyRequestMessage = new TimeSlicedSurveyRequestMessage();
        decodedTimeSlicedSurveyRequestMessage.Request = SurveyRequestMessage.Decode(stream, maxDepth);
        decodedTimeSlicedSurveyRequestMessage.Nonce = Uint32.Decode(stream, maxDepth);
        decodedTimeSlicedSurveyRequestMessage.InboundPeersIndex = Uint32.Decode(stream, maxDepth);
        decodedTimeSlicedSurveyRequestMessage.OutboundPeersIndex = Uint32.Decode(stream, maxDepth);
        return decodedTimeSlicedSurveyRequestMessage;
    }

    public static TimeSlicedSurveyRequestMessage Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
