// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct TimeSlicedSurveyStartCollectingMessage
//  {
//      NodeID surveyorID;
//      uint32 nonce;
//      uint32 ledgerNum;
//  };

//  ===========================================================================
public class TimeSlicedSurveyStartCollectingMessage
{
    public NodeID SurveyorID { get; set; }
    public Uint32 Nonce { get; set; }
    public Uint32 LedgerNum { get; set; }

    public static void Encode(XdrDataOutputStream stream, TimeSlicedSurveyStartCollectingMessage encodedTimeSlicedSurveyStartCollectingMessage)
    {
        NodeID.Encode(stream, encodedTimeSlicedSurveyStartCollectingMessage.SurveyorID);
        Uint32.Encode(stream, encodedTimeSlicedSurveyStartCollectingMessage.Nonce);
        Uint32.Encode(stream, encodedTimeSlicedSurveyStartCollectingMessage.LedgerNum);
    }

    public static TimeSlicedSurveyStartCollectingMessage Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedTimeSlicedSurveyStartCollectingMessage = new TimeSlicedSurveyStartCollectingMessage();
        decodedTimeSlicedSurveyStartCollectingMessage.SurveyorID = NodeID.Decode(stream, maxDepth);
        decodedTimeSlicedSurveyStartCollectingMessage.Nonce = Uint32.Decode(stream, maxDepth);
        decodedTimeSlicedSurveyStartCollectingMessage.LedgerNum = Uint32.Decode(stream, maxDepth);
        return decodedTimeSlicedSurveyStartCollectingMessage;
    }

    public static TimeSlicedSurveyStartCollectingMessage Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
