// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct TransactionMetaV4
//  {
//      ExtensionPoint ext;
//  
//      LedgerEntryChanges txChangesBefore;  // tx level changes before operations
//                                           // are applied if any
//      OperationMetaV2 operations<>;        // meta for each operation
//      LedgerEntryChanges txChangesAfter;   // tx level changes after operations are
//                                           // applied if any
//      SorobanTransactionMetaV2* sorobanMeta; // Soroban-specific meta (only for
//                                             // Soroban transactions).
//  
//      TransactionEvent events<>; // Used for transaction-level events (like fee payment)
//      DiagnosticEvent diagnosticEvents<>; // Used for all diagnostic information
//  };

//  ===========================================================================
public class TransactionMetaV4
{
    public ExtensionPoint Ext { get; set; }
    public LedgerEntryChanges TxChangesBefore { get; set; }
    public OperationMetaV2[] Operations { get; set; }
    public LedgerEntryChanges TxChangesAfter { get; set; }
    public SorobanTransactionMetaV2 SorobanMeta { get; set; }
    public TransactionEvent[] Events { get; set; }
    public DiagnosticEvent[] DiagnosticEvents { get; set; }

    public static void Encode(XdrDataOutputStream stream, TransactionMetaV4 encodedTransactionMetaV4)
    {
        ExtensionPoint.Encode(stream, encodedTransactionMetaV4.Ext);
        LedgerEntryChanges.Encode(stream, encodedTransactionMetaV4.TxChangesBefore);
        var operationsSize = encodedTransactionMetaV4.Operations.Length;
        stream.WriteInt(operationsSize);
        for (var i = 0; i < operationsSize; i++)
        {
            OperationMetaV2.Encode(stream, encodedTransactionMetaV4.Operations[i]);
        }
        LedgerEntryChanges.Encode(stream, encodedTransactionMetaV4.TxChangesAfter);
        if (encodedTransactionMetaV4.SorobanMeta != null)
        {
            stream.WriteInt(1);
            SorobanTransactionMetaV2.Encode(stream, encodedTransactionMetaV4.SorobanMeta);
        }
        else
        {
            stream.WriteInt(0);
        }
        var eventsSize = encodedTransactionMetaV4.Events.Length;
        stream.WriteInt(eventsSize);
        for (var i = 0; i < eventsSize; i++)
        {
            TransactionEvent.Encode(stream, encodedTransactionMetaV4.Events[i]);
        }
        var diagnosticEventsSize = encodedTransactionMetaV4.DiagnosticEvents.Length;
        stream.WriteInt(diagnosticEventsSize);
        for (var i = 0; i < diagnosticEventsSize; i++)
        {
            DiagnosticEvent.Encode(stream, encodedTransactionMetaV4.DiagnosticEvents[i]);
        }
    }

    public static TransactionMetaV4 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding TransactionMetaV4");
        maxDepth -= 1;
        var decodedTransactionMetaV4 = new TransactionMetaV4();
        decodedTransactionMetaV4.Ext = ExtensionPoint.Decode(stream, maxDepth);
        decodedTransactionMetaV4.TxChangesBefore = LedgerEntryChanges.Decode(stream, maxDepth);
        var operationsSize = stream.ReadInt();
        if (operationsSize < 0)
            throw new InvalidDataException("operations size " + operationsSize + " is negative");
        var operationsRemainingInputLen = stream.GetRemainingInputLen();
        if (operationsRemainingInputLen >= 0 && operationsRemainingInputLen < operationsSize)
            throw new InvalidDataException("operations size " + operationsSize + " exceeds remaining input length " + operationsRemainingInputLen);
        decodedTransactionMetaV4.Operations = new OperationMetaV2[operationsSize];
        for (var i = 0; i < operationsSize; i++)
        {
            decodedTransactionMetaV4.Operations[i] = OperationMetaV2.Decode(stream, maxDepth);
        }
        decodedTransactionMetaV4.TxChangesAfter = LedgerEntryChanges.Decode(stream, maxDepth);
        var sorobanMetaPresent = stream.ReadInt();
        if (sorobanMetaPresent != 0)
        {
            decodedTransactionMetaV4.SorobanMeta = SorobanTransactionMetaV2.Decode(stream, maxDepth);
        }
        var eventsSize = stream.ReadInt();
        if (eventsSize < 0)
            throw new InvalidDataException("events size " + eventsSize + " is negative");
        var eventsRemainingInputLen = stream.GetRemainingInputLen();
        if (eventsRemainingInputLen >= 0 && eventsRemainingInputLen < eventsSize)
            throw new InvalidDataException("events size " + eventsSize + " exceeds remaining input length " + eventsRemainingInputLen);
        decodedTransactionMetaV4.Events = new TransactionEvent[eventsSize];
        for (var i = 0; i < eventsSize; i++)
        {
            decodedTransactionMetaV4.Events[i] = TransactionEvent.Decode(stream, maxDepth);
        }
        var diagnosticEventsSize = stream.ReadInt();
        if (diagnosticEventsSize < 0)
            throw new InvalidDataException("diagnosticEvents size " + diagnosticEventsSize + " is negative");
        var diagnosticEventsRemainingInputLen = stream.GetRemainingInputLen();
        if (diagnosticEventsRemainingInputLen >= 0 && diagnosticEventsRemainingInputLen < diagnosticEventsSize)
            throw new InvalidDataException("diagnosticEvents size " + diagnosticEventsSize + " exceeds remaining input length " + diagnosticEventsRemainingInputLen);
        decodedTransactionMetaV4.DiagnosticEvents = new DiagnosticEvent[diagnosticEventsSize];
        for (var i = 0; i < diagnosticEventsSize; i++)
        {
            decodedTransactionMetaV4.DiagnosticEvents[i] = DiagnosticEvent.Decode(stream, maxDepth);
        }
        return decodedTransactionMetaV4;
    }

    public static TransactionMetaV4 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
