// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union TransactionPhase switch (int v)
//  {
//  case 0:
//      TxSetComponent v0Components<>;
//  case 1:
//      ParallelTxsComponent parallelTxsComponent;
//  };

//  ===========================================================================
public class TransactionPhase
{
    public int Discriminant { get; set; }

    public TxSetComponent[] V0Components { get; set; }
    public ParallelTxsComponent ParallelTxsComponent { get; set; }

    public static void Encode(XdrDataOutputStream stream, TransactionPhase encodedTransactionPhase)
    {
        stream.WriteInt(encodedTransactionPhase.Discriminant);
        switch (encodedTransactionPhase.Discriminant)
        {
            case 0:
                var v0Componentssize = encodedTransactionPhase.V0Components.Length;
                stream.WriteInt(v0Componentssize);
                for (var i = 0; i < v0Componentssize; i++)
                {
                    TxSetComponent.Encode(stream, encodedTransactionPhase.V0Components[i]);
                }
                break;
            case 1:
                ParallelTxsComponent.Encode(stream, encodedTransactionPhase.ParallelTxsComponent);
                break;
        }
    }

    public static TransactionPhase Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedTransactionPhase = new TransactionPhase();
        var discriminant = stream.ReadInt();
        decodedTransactionPhase.Discriminant = discriminant;
        switch (decodedTransactionPhase.Discriminant)
        {
            case 0:
                var v0Componentssize = stream.ReadInt();
                if (v0Componentssize < 0)
                    throw new IOException("v0Components size " + v0Componentssize + " is negative");
                var v0ComponentsRemainingInputLen = stream.GetRemainingInputLen();
                if (v0ComponentsRemainingInputLen >= 0 && v0ComponentsRemainingInputLen < v0Componentssize)
                    throw new IOException("v0Components size " + v0Componentssize + " exceeds remaining input length " + v0ComponentsRemainingInputLen);
                decodedTransactionPhase.V0Components = new TxSetComponent[v0Componentssize];
                for (var i = 0; i < v0Componentssize; i++)
                {
                    decodedTransactionPhase.V0Components[i] = TxSetComponent.Decode(stream, maxDepth);
                }
                break;
            case 1:
                decodedTransactionPhase.ParallelTxsComponent = ParallelTxsComponent.Decode(stream, maxDepth);
                break;
            default:
                throw new IOException("Unknown discriminant value: " + discriminant);
        }

        return decodedTransactionPhase;
    }

    public static TransactionPhase Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
