// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct TransactionSetV1
//  {
//      Hash previousLedgerHash;
//      TransactionPhase phases<>;
//  };

//  ===========================================================================
public class TransactionSetV1
{
    public Hash PreviousLedgerHash { get; set; }
    public TransactionPhase[] Phases { get; set; }

    public static void Encode(XdrDataOutputStream stream, TransactionSetV1 encodedTransactionSetV1)
    {
        Hash.Encode(stream, encodedTransactionSetV1.PreviousLedgerHash);
        var phasessize = encodedTransactionSetV1.Phases.Length;
        stream.WriteInt(phasessize);
        for (var i = 0; i < phasessize; i++)
        {
            TransactionPhase.Encode(stream, encodedTransactionSetV1.Phases[i]);
        }
    }

    public static TransactionSetV1 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedTransactionSetV1 = new TransactionSetV1();
        decodedTransactionSetV1.PreviousLedgerHash = Hash.Decode(stream, maxDepth);
        var phasessize = stream.ReadInt();
        if (phasessize < 0)
            throw new InvalidDataException("phases size " + phasessize + " is negative");
        decodedTransactionSetV1.Phases = new TransactionPhase[phasessize];
        for (var i = 0; i < phasessize; i++)
        {
            decodedTransactionSetV1.Phases[i] = TransactionPhase.Decode(stream, maxDepth);
        }
        return decodedTransactionSetV1;
    }

    public static TransactionSetV1 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
