// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct TransactionResultSet
//  {
//      TransactionResultPair results<>;
//  };

//  ===========================================================================
public class TransactionResultSet
{
    public TransactionResultPair[] Results { get; set; }

    public static void Encode(XdrDataOutputStream stream, TransactionResultSet encodedTransactionResultSet)
    {
        var resultsSize = encodedTransactionResultSet.Results.Length;
        stream.WriteInt(resultsSize);
        for (var i = 0; i < resultsSize; i++)
        {
            TransactionResultPair.Encode(stream, encodedTransactionResultSet.Results[i]);
        }
    }

    public static TransactionResultSet Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding TransactionResultSet");
        maxDepth -= 1;
        var decodedTransactionResultSet = new TransactionResultSet();
        var resultsSize = stream.ReadInt();
        if (resultsSize < 0)
            throw new InvalidDataException("results size " + resultsSize + " is negative");
        var resultsRemainingInputLen = stream.GetRemainingInputLen();
        if (resultsRemainingInputLen >= 0 && resultsRemainingInputLen < resultsSize)
            throw new InvalidDataException("results size " + resultsSize + " exceeds remaining input length " + resultsRemainingInputLen);
        decodedTransactionResultSet.Results = new TransactionResultPair[resultsSize];
        for (var i = 0; i < resultsSize; i++)
        {
            decodedTransactionResultSet.Results[i] = TransactionResultPair.Decode(stream, maxDepth);
        }
        return decodedTransactionResultSet;
    }

    public static TransactionResultSet Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
