// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union TransactionMeta switch (int v)
//  {
//  case 0:
//      OperationMeta operations<>;
//  case 1:
//      TransactionMetaV1 v1;
//  case 2:
//      TransactionMetaV2 v2;
//  case 3:
//      TransactionMetaV3 v3;
//  case 4:
//      TransactionMetaV4 v4;
//  };

//  ===========================================================================
public class TransactionMeta
{
    public int Discriminant { get; set; }

    public OperationMeta[] Operations { get; set; }
    public TransactionMetaV1 V1 { get; set; }
    public TransactionMetaV2 V2 { get; set; }
    public TransactionMetaV3 V3 { get; set; }
    public TransactionMetaV4 V4 { get; set; }

    public static void Encode(XdrDataOutputStream stream, TransactionMeta encodedTransactionMeta)
    {
        stream.WriteInt(encodedTransactionMeta.Discriminant);
        switch (encodedTransactionMeta.Discriminant)
        {
            case 0:
                var operationsSize = encodedTransactionMeta.Operations.Length;
                stream.WriteInt(operationsSize);
                for (var i = 0; i < operationsSize; i++)
                {
                    OperationMeta.Encode(stream, encodedTransactionMeta.Operations[i]);
                }
                break;
            case 1:
                TransactionMetaV1.Encode(stream, encodedTransactionMeta.V1);
                break;
            case 2:
                TransactionMetaV2.Encode(stream, encodedTransactionMeta.V2);
                break;
            case 3:
                TransactionMetaV3.Encode(stream, encodedTransactionMeta.V3);
                break;
            case 4:
                TransactionMetaV4.Encode(stream, encodedTransactionMeta.V4);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + encodedTransactionMeta.Discriminant);
        }
    }

    public static TransactionMeta Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding TransactionMeta");
        maxDepth -= 1;
        var decodedTransactionMeta = new TransactionMeta();
        var discriminant = stream.ReadInt();
        decodedTransactionMeta.Discriminant = discriminant;
        switch (decodedTransactionMeta.Discriminant)
        {
            case 0:
                var operationsSize = stream.ReadInt();
                if (operationsSize < 0)
                    throw new InvalidDataException("operations size " + operationsSize + " is negative");
                decodedTransactionMeta.Operations = new OperationMeta[operationsSize];
                for (var i = 0; i < operationsSize; i++)
                {
                    decodedTransactionMeta.Operations[i] = OperationMeta.Decode(stream, maxDepth);
                }
                break;
            case 1:
                decodedTransactionMeta.V1 = TransactionMetaV1.Decode(stream, maxDepth);
                break;
            case 2:
                decodedTransactionMeta.V2 = TransactionMetaV2.Decode(stream, maxDepth);
                break;
            case 3:
                decodedTransactionMeta.V3 = TransactionMetaV3.Decode(stream, maxDepth);
                break;
            case 4:
                decodedTransactionMeta.V4 = TransactionMetaV4.Decode(stream, maxDepth);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant);
        }

        return decodedTransactionMeta;
    }

    public static TransactionMeta Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
