// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct TransactionResultMeta
//  {
//      TransactionResultPair result;
//      LedgerEntryChanges feeProcessing;
//      TransactionMeta txApplyProcessing;
//  };

//  ===========================================================================
public class TransactionResultMeta
{
    public TransactionResultPair Result { get; set; }
    public LedgerEntryChanges FeeProcessing { get; set; }
    public TransactionMeta TxApplyProcessing { get; set; }

    public static void Encode(XdrDataOutputStream stream, TransactionResultMeta encodedTransactionResultMeta)
    {
        TransactionResultPair.Encode(stream, encodedTransactionResultMeta.Result);
        LedgerEntryChanges.Encode(stream, encodedTransactionResultMeta.FeeProcessing);
        TransactionMeta.Encode(stream, encodedTransactionResultMeta.TxApplyProcessing);
    }

    public static TransactionResultMeta Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedTransactionResultMeta = new TransactionResultMeta();
        decodedTransactionResultMeta.Result = TransactionResultPair.Decode(stream, maxDepth);
        decodedTransactionResultMeta.FeeProcessing = LedgerEntryChanges.Decode(stream, maxDepth);
        decodedTransactionResultMeta.TxApplyProcessing = TransactionMeta.Decode(stream, maxDepth);
        return decodedTransactionResultMeta;
    }

    public static TransactionResultMeta Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
