// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union TrustLineAsset switch (AssetType type)
//  {
//  case ASSET_TYPE_NATIVE: // Not credit
//      void;
//  
//  case ASSET_TYPE_CREDIT_ALPHANUM4:
//      AlphaNum4 alphaNum4;
//  
//  case ASSET_TYPE_CREDIT_ALPHANUM12:
//      AlphaNum12 alphaNum12;
//  
//  case ASSET_TYPE_POOL_SHARE:
//      PoolID liquidityPoolID;
//  
//      // add other asset types here in the future
//  };

//  ===========================================================================
public class TrustLineAsset
{
    public AssetType Discriminant { get; set; } = new();

    public AlphaNum4 AlphaNum4 { get; set; }
    public AlphaNum12 AlphaNum12 { get; set; }
    public PoolID LiquidityPoolID { get; set; }

    public static void Encode(XdrDataOutputStream stream, TrustLineAsset encodedTrustLineAsset)
    {
        stream.WriteInt((int)encodedTrustLineAsset.Discriminant.InnerValue);
        switch (encodedTrustLineAsset.Discriminant.InnerValue)
        {
            case AssetType.AssetTypeEnum.ASSET_TYPE_NATIVE:
                break;
            case AssetType.AssetTypeEnum.ASSET_TYPE_CREDIT_ALPHANUM4:
                AlphaNum4.Encode(stream, encodedTrustLineAsset.AlphaNum4);
                break;
            case AssetType.AssetTypeEnum.ASSET_TYPE_CREDIT_ALPHANUM12:
                AlphaNum12.Encode(stream, encodedTrustLineAsset.AlphaNum12);
                break;
            case AssetType.AssetTypeEnum.ASSET_TYPE_POOL_SHARE:
                PoolID.Encode(stream, encodedTrustLineAsset.LiquidityPoolID);
                break;
        }
    }

    public static TrustLineAsset Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedTrustLineAsset = new TrustLineAsset();
        var discriminant = AssetType.Decode(stream, maxDepth);
        decodedTrustLineAsset.Discriminant = discriminant;
        switch (decodedTrustLineAsset.Discriminant.InnerValue)
        {
            case AssetType.AssetTypeEnum.ASSET_TYPE_NATIVE:
                break;
            case AssetType.AssetTypeEnum.ASSET_TYPE_CREDIT_ALPHANUM4:
                decodedTrustLineAsset.AlphaNum4 = AlphaNum4.Decode(stream, maxDepth);
                break;
            case AssetType.AssetTypeEnum.ASSET_TYPE_CREDIT_ALPHANUM12:
                decodedTrustLineAsset.AlphaNum12 = AlphaNum12.Decode(stream, maxDepth);
                break;
            case AssetType.AssetTypeEnum.ASSET_TYPE_POOL_SHARE:
                decodedTrustLineAsset.LiquidityPoolID = PoolID.Decode(stream, maxDepth);
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant);
        }

        return decodedTrustLineAsset;
    }

    public static TrustLineAsset Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
