// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct TTLEntry {
//      // Hash of the LedgerKey that is associated with this TTLEntry
//      Hash keyHash;
//      uint32 liveUntilLedgerSeq;
//  };

//  ===========================================================================
public class TTLEntry
{
    public Hash KeyHash { get; set; }
    public Uint32 LiveUntilLedgerSeq { get; set; }

    public static void Encode(XdrDataOutputStream stream, TTLEntry encodedTTLEntry)
    {
        Hash.Encode(stream, encodedTTLEntry.KeyHash);
        Uint32.Encode(stream, encodedTTLEntry.LiveUntilLedgerSeq);
    }

    public static TTLEntry Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding TTLEntry");
        maxDepth -= 1;
        var decodedTTLEntry = new TTLEntry();
        decodedTTLEntry.KeyHash = Hash.Decode(stream, maxDepth);
        decodedTTLEntry.LiveUntilLedgerSeq = Uint32.Decode(stream, maxDepth);
        return decodedTTLEntry;
    }

    public static TTLEntry Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
