// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef Hash TxAdvertVector<TX_ADVERT_VECTOR_MAX_SIZE>;

//  ===========================================================================
public class TxAdvertVector
{
    public TxAdvertVector()
    {
    }

    public TxAdvertVector(Hash[] value)
    {
        InnerValue = value;
    }

    public Hash[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, TxAdvertVector encodedTxAdvertVector)
    {
        var TxAdvertVectorsize = encodedTxAdvertVector.InnerValue.Length;
        if (TxAdvertVectorsize > 1000)
            throw new ArgumentException("TxAdvertVector size " + TxAdvertVectorsize + " exceeds max size 1000");
        stream.WriteInt(TxAdvertVectorsize);
        for (var i = 0; i < TxAdvertVectorsize; i++)
        {
            Hash.Encode(stream, encodedTxAdvertVector.InnerValue[i]);
        }
    }

    public static TxAdvertVector Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedTxAdvertVector = new TxAdvertVector();
        var TxAdvertVectorsize = stream.ReadInt();
        if (TxAdvertVectorsize < 0)
            throw new InvalidDataException("TxAdvertVector size " + TxAdvertVectorsize + " is negative");
        if (TxAdvertVectorsize > 1000)
            throw new InvalidDataException("TxAdvertVector size " + TxAdvertVectorsize + " exceeds max size 1000");
        var TxAdvertVectorRemainingInputLen = stream.GetRemainingInputLen();
        if (TxAdvertVectorRemainingInputLen >= 0 && TxAdvertVectorRemainingInputLen < TxAdvertVectorsize)
            throw new InvalidDataException("TxAdvertVector size " + TxAdvertVectorsize + " exceeds remaining input length " + TxAdvertVectorRemainingInputLen);
        decodedTxAdvertVector.InnerValue = new Hash[TxAdvertVectorsize];
        for (var i = 0; i < TxAdvertVectorsize; i++)
        {
            decodedTxAdvertVector.InnerValue[i] = Hash.Decode(stream, maxDepth);
        }
        return decodedTxAdvertVector;
    }

    public static TxAdvertVector Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
