// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef Hash TxDemandVector<TX_DEMAND_VECTOR_MAX_SIZE>;

//  ===========================================================================
public class TxDemandVector
{
    public TxDemandVector()
    {
    }

    public TxDemandVector(Hash[] value)
    {
        InnerValue = value;
    }

    public Hash[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, TxDemandVector encodedTxDemandVector)
    {
        var TxDemandVectorsize = encodedTxDemandVector.InnerValue.Length;
        if (TxDemandVectorsize > 1000)
            throw new ArgumentException("TxDemandVector size " + TxDemandVectorsize + " exceeds max size 1000");
        stream.WriteInt(TxDemandVectorsize);
        for (var i = 0; i < TxDemandVectorsize; i++)
        {
            Hash.Encode(stream, encodedTxDemandVector.InnerValue[i]);
        }
    }

    public static TxDemandVector Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedTxDemandVector = new TxDemandVector();
        var TxDemandVectorsize = stream.ReadInt();
        if (TxDemandVectorsize < 0)
            throw new InvalidDataException("TxDemandVector size " + TxDemandVectorsize + " is negative");
        if (TxDemandVectorsize > 1000)
            throw new InvalidDataException("TxDemandVector size " + TxDemandVectorsize + " exceeds max size 1000");
        decodedTxDemandVector.InnerValue = new Hash[TxDemandVectorsize];
        for (var i = 0; i < TxDemandVectorsize; i++)
        {
            decodedTxDemandVector.InnerValue[i] = Hash.Decode(stream, maxDepth);
        }
        return decodedTxDemandVector;
    }

    public static TxDemandVector Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
