// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef opaque uint256[32];

//  ===========================================================================
public class Uint256
{
    public Uint256()
    {
    }

    public Uint256(byte[] value)
    {
        InnerValue = value;
    }

    public byte[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Uint256 encodedUint256)
    {
        var uint256Size = encodedUint256.InnerValue.Length;
        if (uint256Size != 32)
            throw new ArgumentException("uint256 size " + uint256Size + " does not match fixed size 32");
        stream.Write(encodedUint256.InnerValue, 0, uint256Size);
    }

    public static Uint256 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding Uint256");
        maxDepth -= 1;
        var decodedUint256 = new Uint256();
        var uint256Size = 32;
        decodedUint256.InnerValue = new byte[uint256Size];
        stream.Read(decodedUint256.InnerValue, 0, uint256Size);
        return decodedUint256;
    }

    public static Uint256 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
