// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct UpgradeEntryMeta
//  {
//      LedgerUpgrade upgrade;
//      LedgerEntryChanges changes;
//  };

//  ===========================================================================
public class UpgradeEntryMeta
{
    public LedgerUpgrade Upgrade { get; set; }
    public LedgerEntryChanges Changes { get; set; }

    public static void Encode(XdrDataOutputStream stream, UpgradeEntryMeta encodedUpgradeEntryMeta)
    {
        LedgerUpgrade.Encode(stream, encodedUpgradeEntryMeta.Upgrade);
        LedgerEntryChanges.Encode(stream, encodedUpgradeEntryMeta.Changes);
    }

    public static UpgradeEntryMeta Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedUpgradeEntryMeta = new UpgradeEntryMeta();
        decodedUpgradeEntryMeta.Upgrade = LedgerUpgrade.Decode(stream, maxDepth);
        decodedUpgradeEntryMeta.Changes = LedgerEntryChanges.Decode(stream, maxDepth);
        return decodedUpgradeEntryMeta;
    }

    public static UpgradeEntryMeta Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
