// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef opaque UpgradeType<128>;

//  ===========================================================================
public class UpgradeType
{
    public UpgradeType()
    {
    }

    public UpgradeType(byte[] value)
    {
        InnerValue = value;
    }

    public byte[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, UpgradeType encodedUpgradeType)
    {
        var upgradeTypeSize = encodedUpgradeType.InnerValue.Length;
        if (upgradeTypeSize > 128)
            throw new ArgumentException("UpgradeType size " + upgradeTypeSize + " exceeds max size 128");
        stream.WriteInt(upgradeTypeSize);
        stream.Write(encodedUpgradeType.InnerValue, 0, upgradeTypeSize);
    }

    public static UpgradeType Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding UpgradeType");
        maxDepth -= 1;
        var decodedUpgradeType = new UpgradeType();
        var upgradeTypeSize = stream.ReadInt();
        if (upgradeTypeSize < 0)
            throw new InvalidDataException("UpgradeType size " + upgradeTypeSize + " is negative");
        if (upgradeTypeSize > 128)
            throw new InvalidDataException("UpgradeType size " + upgradeTypeSize + " exceeds max size 128");
        var upgradeTypeRemainingInputLen = stream.GetRemainingInputLen();
        if (upgradeTypeRemainingInputLen >= 0 && upgradeTypeRemainingInputLen < upgradeTypeSize)
            throw new InvalidDataException("UpgradeType size " + upgradeTypeSize + " exceeds remaining input length " + upgradeTypeRemainingInputLen);
        decodedUpgradeType.InnerValue = new byte[upgradeTypeSize];
        stream.Read(decodedUpgradeType.InnerValue, 0, upgradeTypeSize);
        return decodedUpgradeType;
    }

    public static UpgradeType Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
