// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef int Arr[2];

//  ===========================================================================
public class Arr
{
    public Arr()
    {
    }

    public Arr(int[] value)
    {
        InnerValue = value;
    }

    public int[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Arr encodedArr)
    {
        var Arrsize = encodedArr.InnerValue.Length;
        if (Arrsize != 2)
            throw new ArgumentException("Arr size " + Arrsize + " does not match fixed size 2");
        for (var i = 0; i < Arrsize; i++)
        {
            stream.WriteInt(encodedArr.InnerValue[i]);
        }
    }

    public static Arr Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedArr = new Arr();
        var Arrsize = 2;
        decodedArr.InnerValue = new int[Arrsize];
        for (var i = 0; i < Arrsize; i++)
        {
            decodedArr.InnerValue[i] = stream.ReadInt();
        }
        return decodedArr;
    }

    public static Arr Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
