// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef string str2<>;

//  ===========================================================================
public class Str2
{
    public Str2()
    {
    }

    public Str2(string value)
    {
        InnerValue = value;
    }

    public string InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Str2 encodedStr2)
    {
        stream.WriteString(encodedStr2.InnerValue);
    }

    public static Str2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedStr2 = new Str2();
        decodedStr2.InnerValue = stream.ReadString();
        return decodedStr2;
    }

    public static Str2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
