// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

namespace StellarDotnetSdk.Xdr;

public static class Constants
{
    public const int BAR = FOO;
    public const int FOO = 1244;
}
