// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef Hash Hashes2<12>;

//  ===========================================================================
public class Hashes2
{
    public Hashes2()
    {
    }

    public Hashes2(Hash[] value)
    {
        InnerValue = value;
    }

    public Hash[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Hashes2 encodedHashes2)
    {
        var hashes2Size = encodedHashes2.InnerValue.Length;
        if (hashes2Size > 12)
            throw new ArgumentException("Hashes2 size " + hashes2Size + " exceeds max size 12");
        stream.WriteInt(hashes2Size);
        for (var i = 0; i < hashes2Size; i++)
        {
            Hash.Encode(stream, encodedHashes2.InnerValue[i]);
        }
    }

    public static Hashes2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding Hashes2");
        maxDepth -= 1;
        var decodedHashes2 = new Hashes2();
        var hashes2Size = stream.ReadInt();
        if (hashes2Size < 0)
            throw new InvalidDataException("Hashes2 size " + hashes2Size + " is negative");
        if (hashes2Size > 12)
            throw new InvalidDataException("Hashes2 size " + hashes2Size + " exceeds max size 12");
        var hashes2RemainingInputLen = stream.GetRemainingInputLen();
        if (hashes2RemainingInputLen >= 0 && hashes2RemainingInputLen < hashes2Size)
            throw new InvalidDataException("Hashes2 size " + hashes2Size + " exceeds remaining input length " + hashes2RemainingInputLen);
        decodedHashes2.InnerValue = new Hash[hashes2Size];
        for (var i = 0; i < hashes2Size; i++)
        {
            decodedHashes2.InnerValue[i] = Hash.Decode(stream, maxDepth);
        }
        return decodedHashes2;
    }

    public static Hashes2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
