// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef Hash Hashes3<>;

//  ===========================================================================
public class Hashes3
{
    public Hashes3()
    {
    }

    public Hashes3(Hash[] value)
    {
        InnerValue = value;
    }

    public Hash[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Hashes3 encodedHashes3)
    {
        var hashes3Size = encodedHashes3.InnerValue.Length;
        stream.WriteInt(hashes3Size);
        for (var i = 0; i < hashes3Size; i++)
        {
            Hash.Encode(stream, encodedHashes3.InnerValue[i]);
        }
    }

    public static Hashes3 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding Hashes3");
        maxDepth -= 1;
        var decodedHashes3 = new Hashes3();
        var hashes3Size = stream.ReadInt();
        if (hashes3Size < 0)
            throw new InvalidDataException("Hashes3 size " + hashes3Size + " is negative");
        var hashes3RemainingInputLen = stream.GetRemainingInputLen();
        if (hashes3RemainingInputLen >= 0 && hashes3RemainingInputLen < hashes3Size)
            throw new InvalidDataException("Hashes3 size " + hashes3Size + " exceeds remaining input length " + hashes3RemainingInputLen);
        decodedHashes3.InnerValue = new Hash[hashes3Size];
        for (var i = 0; i < hashes3Size; i++)
        {
            decodedHashes3.InnerValue[i] = Hash.Decode(stream, maxDepth);
        }
        return decodedHashes3;
    }

    public static Hashes3 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
