// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef Hash Hashes1[12];

//  ===========================================================================
public class Hashes1
{
    public Hashes1()
    {
    }

    public Hashes1(Hash[] value)
    {
        InnerValue = value;
    }

    public Hash[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Hashes1 encodedHashes1)
    {
        var hashes1Size = encodedHashes1.InnerValue.Length;
        if (hashes1Size != 12)
            throw new ArgumentException("Hashes1 size " + hashes1Size + " does not match fixed size 12");
        for (var i = 0; i < hashes1Size; i++)
        {
            Hash.Encode(stream, encodedHashes1.InnerValue[i]);
        }
    }

    public static Hashes1 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding Hashes1");
        maxDepth -= 1;
        var decodedHashes1 = new Hashes1();
        var hashes1Size = 12;
        decodedHashes1.InnerValue = new Hash[hashes1Size];
        for (var i = 0; i < hashes1Size; i++)
        {
            decodedHashes1.InnerValue[i] = Hash.Decode(stream, maxDepth);
        }
        return decodedHashes1;
    }

    public static Hashes1 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
