// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct HasStuff
//  {
//    LotsOfMyStructs data;
//  };

//  ===========================================================================
public class HasStuff
{
    public LotsOfMyStructs Data { get; set; }

    public static void Encode(XdrDataOutputStream stream, HasStuff encodedHasStuff)
    {
        LotsOfMyStructs.Encode(stream, encodedHasStuff.Data);
    }

    public static HasStuff Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding HasStuff");
        maxDepth -= 1;
        var decodedHasStuff = new HasStuff();
        decodedHasStuff.Data = LotsOfMyStructs.Decode(stream, maxDepth);
        return decodedHasStuff;
    }

    public static HasStuff Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
