// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef unsigned int    int3;

//  ===========================================================================
public class Int3
{
    public Int3()
    {
    }

    public Int3(uint value)
    {
        InnerValue = value;
    }

    public uint InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Int3 encodedInt3)
    {
        stream.WriteUInt(encodedInt3.InnerValue);
    }

    public static Int3 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedInt3 = new Int3();
        decodedInt3.InnerValue = stream.ReadUInt();
        return decodedInt3;
    }

    public static Int3 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
