// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  struct LotsOfMyStructs
//  {
//      MyStruct members<>;
//  };

//  ===========================================================================
public class LotsOfMyStructs
{
    public MyStruct[] Members { get; set; }

    public static void Encode(XdrDataOutputStream stream, LotsOfMyStructs encodedLotsOfMyStructs)
    {
        var membersSize = encodedLotsOfMyStructs.Members.Length;
        stream.WriteInt(membersSize);
        for (var i = 0; i < membersSize; i++)
        {
            MyStruct.Encode(stream, encodedLotsOfMyStructs.Members[i]);
        }
    }

    public static LotsOfMyStructs Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding LotsOfMyStructs");
        maxDepth -= 1;
        var decodedLotsOfMyStructs = new LotsOfMyStructs();
        var membersSize = stream.ReadInt();
        if (membersSize < 0)
            throw new InvalidDataException("members size " + membersSize + " is negative");
        decodedLotsOfMyStructs.Members = new MyStruct[membersSize];
        for (var i = 0; i < membersSize; i++)
        {
            decodedLotsOfMyStructs.Members[i] = MyStruct.Decode(stream, maxDepth);
        }
        return decodedLotsOfMyStructs;
    }

    public static LotsOfMyStructs Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
