// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef opaque uint512[64];

//  ===========================================================================
public class Uint512
{
    public Uint512()
    {
    }

    public Uint512(byte[] value)
    {
        InnerValue = value;
    }

    public byte[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Uint512 encodedUint512)
    {
        var uint512Size = encodedUint512.InnerValue.Length;
        if (uint512Size != 64)
            throw new ArgumentException("uint512 size " + uint512Size + " does not match fixed size 64");
        stream.Write(encodedUint512.InnerValue, 0, uint512Size);
    }

    public static Uint512 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding Uint512");
        maxDepth -= 1;
        var decodedUint512 = new Uint512();
        var uint512Size = 64;
        decodedUint512.InnerValue = new byte[uint512Size];
        stream.Read(decodedUint512.InnerValue, 0, uint512Size);
        return decodedUint512;
    }

    public static Uint512 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
