// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef int Error;

//  ===========================================================================
public class Error
{
    public Error()
    {
    }

    public Error(int value)
    {
        InnerValue = value;
    }

    public int InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Error encodedError)
    {
        stream.WriteInt(encodedError.InnerValue);
    }

    public static Error Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding Error");
        maxDepth -= 1;
        var decodedError = new Error();
        decodedError.InnerValue = stream.ReadInt();
        return decodedError;
    }

    public static Error Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
