// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  union MyUnion switch (UnionKey type)
//  {
//      case ERROR:
//          Error error;
//      case MULTI:
//          Multi things<>;
//  
//  
//  };

//  ===========================================================================
public class MyUnion
{
    public UnionKey Discriminant { get; set; } = new();

    public Error Error { get; set; }
    public Multi[] Things { get; set; }

    public static void Encode(XdrDataOutputStream stream, MyUnion encodedMyUnion)
    {
        stream.WriteInt((int)encodedMyUnion.Discriminant.InnerValue);
        switch (encodedMyUnion.Discriminant.InnerValue)
        {
            case UnionKey.UnionKeyEnum.ERROR:
                Error.Encode(stream, encodedMyUnion.Error);
                break;
            case UnionKey.UnionKeyEnum.MULTI:
                var thingssize = encodedMyUnion.Things.Length;
                stream.WriteInt(thingssize);
                for (var i = 0; i < thingssize; i++)
                {
                    Multi.Encode(stream, encodedMyUnion.Things[i]);
                }
                break;
        }
    }

    public static MyUnion Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding MyUnion");
        maxDepth -= 1;
        var decodedMyUnion = new MyUnion();
        var discriminant = UnionKey.Decode(stream, maxDepth);
        decodedMyUnion.Discriminant = discriminant;
        switch (decodedMyUnion.Discriminant.InnerValue)
        {
            case UnionKey.UnionKeyEnum.ERROR:
                decodedMyUnion.Error = Error.Decode(stream, maxDepth);
                break;
            case UnionKey.UnionKeyEnum.MULTI:
                var thingssize = stream.ReadInt();
                if (thingssize < 0)
                    throw new InvalidDataException("things size " + thingssize + " is negative");
                decodedMyUnion.Things = new Multi[thingssize];
                for (var i = 0; i < thingssize; i++)
                {
                    decodedMyUnion.Things[i] = Multi.Decode(stream, maxDepth);
                }
                break;
            default:
                throw new InvalidDataException("Unknown discriminant value: " + discriminant.InnerValue);
        }

        return decodedMyUnion;
    }

    public static MyUnion Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
