// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef int TestArray[FOO];

//  ===========================================================================
public class TestArray
{
    public TestArray()
    {
    }

    public TestArray(int[] value)
    {
        InnerValue = value;
    }

    public int[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, TestArray encodedTestArray)
    {
        var testArraySize = encodedTestArray.InnerValue.Length;
        if (testArraySize != Constants.FOO)
            throw new ArgumentException("TestArray size " + testArraySize + " does not match fixed size FOO");
        for (var i = 0; i < testArraySize; i++)
        {
            stream.WriteInt(encodedTestArray.InnerValue[i]);
        }
    }

    public static TestArray Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding TestArray");
        maxDepth -= 1;
        var decodedTestArray = new TestArray();
        var testArraySize = Constants.FOO;
        decodedTestArray.InnerValue = new int[testArraySize];
        for (var i = 0; i < testArraySize; i++)
        {
            decodedTestArray.InnerValue[i] = stream.ReadInt();
        }
        return decodedTestArray;
    }

    public static TestArray Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
