// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef int TestArray2<FOO>;

//  ===========================================================================
public class TestArray2
{
    public TestArray2()
    {
    }

    public TestArray2(int[] value)
    {
        InnerValue = value;
    }

    public int[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, TestArray2 encodedTestArray2)
    {
        var testArray2Size = encodedTestArray2.InnerValue.Length;
        if (testArray2Size > 1)
            throw new ArgumentException("TestArray2 size " + testArray2Size + " exceeds max size 1");
        stream.WriteInt(testArray2Size);
        for (var i = 0; i < testArray2Size; i++)
        {
            stream.WriteInt(encodedTestArray2.InnerValue[i]);
        }
    }

    public static TestArray2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding TestArray2");
        maxDepth -= 1;
        var decodedTestArray2 = new TestArray2();
        var testArray2Size = stream.ReadInt();
        if (testArray2Size < 0)
            throw new InvalidDataException("TestArray2 size " + testArray2Size + " is negative");
        if (testArray2Size > 1)
            throw new InvalidDataException("TestArray2 size " + testArray2Size + " exceeds max size 1");
        var testArray2RemainingInputLen = stream.GetRemainingInputLen();
        if (testArray2RemainingInputLen >= 0 && testArray2RemainingInputLen < testArray2Size)
            throw new InvalidDataException("TestArray2 size " + testArray2Size + " exceeds remaining input length " + testArray2RemainingInputLen);
        decodedTestArray2.InnerValue = new int[testArray2Size];
        for (var i = 0; i < testArray2Size; i++)
        {
            decodedTestArray2.InnerValue[i] = stream.ReadInt();
        }
        return decodedTestArray2;
    }

    public static TestArray2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
