// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef int TestArray2<FOO>;

//  ===========================================================================
public class TestArray2
{
    public TestArray2()
    {
    }

    public TestArray2(int[] value)
    {
        InnerValue = value;
    }

    public int[] InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, TestArray2 encodedTestArray2)
    {
        var TestArray2size = encodedTestArray2.InnerValue.Length;
        if (TestArray2size > 1)
            throw new ArgumentException("TestArray2 size " + TestArray2size + " exceeds max size 1");
        stream.WriteInt(TestArray2size);
        for (var i = 0; i < TestArray2size; i++)
        {
            stream.WriteInt(encodedTestArray2.InnerValue[i]);
        }
    }

    public static TestArray2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedTestArray2 = new TestArray2();
        var TestArray2size = stream.ReadInt();
        if (TestArray2size < 0)
            throw new InvalidDataException("TestArray2 size " + TestArray2size + " is negative");
        if (TestArray2size > 1)
            throw new InvalidDataException("TestArray2 size " + TestArray2size + " exceeds max size 1");
        decodedTestArray2.InnerValue = new int[TestArray2size];
        for (var i = 0; i < TestArray2size; i++)
        {
            decodedTestArray2.InnerValue[i] = stream.ReadInt();
        }
        return decodedTestArray2;
    }

    public static TestArray2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
