// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef int Foo;

//  ===========================================================================
public class Foo
{
    public Foo()
    {
    }

    public Foo(int value)
    {
        InnerValue = value;
    }

    public int InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, Foo encodedFoo)
    {
        stream.WriteInt(encodedFoo.InnerValue);
    }

    public static Foo Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new InvalidDataException("Maximum decoding depth reached while decoding Foo");
        maxDepth -= 1;
        var decodedFoo = new Foo();
        decodedFoo.InnerValue = stream.ReadInt();
        return decodedFoo;
    }

    public static Foo Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
