// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum UnionKey {
//    ONE = 1,
//    TWO = 2,
//    OFFER = 3
//  };

//  ===========================================================================
public class UnionKey
{
    public enum UnionKeyEnum
    {
        ONE = 1,
        TWO = 2,
        OFFER = 3,
    }

    public UnionKeyEnum InnerValue { get; set; }

    public static UnionKey Create(UnionKeyEnum v)
    {
        return new UnionKey
        {
            InnerValue = v,
        };
    }

    public static UnionKey Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        var value = stream.ReadInt();
        switch (value)
        {
            case 1: return Create(UnionKeyEnum.ONE);
            case 2: return Create(UnionKeyEnum.TWO);
            case 3: return Create(UnionKeyEnum.OFFER);
            default:
                throw new IOException("Unknown enum value: " + value);
        }
    }

    public static UnionKey Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, UnionKey value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
