// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum Color2 {
//      RED2=RED,
//      GREEN2=1,
//      BLUE2=2
//  };

//  ===========================================================================
public class Color2
{
    public enum Color2Enum
    {
        RED2 = 0,
        GREEN2 = 1,
        BLUE2 = 2,
    }

    public Color2Enum InnerValue { get; set; }

    public static Color2 Create(Color2Enum v)
    {
        return new Color2
        {
            InnerValue = v,
        };
    }

    public static Color2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        _ = maxDepth;
        var value = stream.ReadInt();
        switch (value)
        {
            case 0: return Create(Color2Enum.RED2);
            case 1: return Create(Color2Enum.GREEN2);
            case 2: return Create(Color2Enum.BLUE2);
            default:
                throw new InvalidDataException("Unknown enum value: " + value);
        }
    }

    public static Color2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, Color2 value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
