// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  enum Color3 {
//      RED_1=1,
//      RED_2_TWO=2,
//      RED_3=3
//  };

//  ===========================================================================
public class Color3
{
    public enum Color3Enum
    {
        RED_1 = 1,
        RED_2_TWO = 2,
        RED_3 = 3,
    }

    public Color3Enum InnerValue { get; set; }

    public static Color3 Create(Color3Enum v)
    {
        return new Color3
        {
            InnerValue = v,
        };
    }

    public static Color3 Decode(XdrDataInputStream stream, int maxDepth)
    {
        // maxDepth is intentionally not checked - enums are leaf types
        _ = maxDepth;
        var value = stream.ReadInt();
        switch (value)
        {
            case 1: return Create(Color3Enum.RED_1);
            case 2: return Create(Color3Enum.RED_2_TWO);
            case 3: return Create(Color3Enum.RED_3);
            default:
                throw new InvalidDataException("Unknown enum value: " + value);
        }
    }

    public static Color3 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }

    public static void Encode(XdrDataOutputStream stream, Color3 value)
    {
        stream.WriteInt((int)value.InnerValue);
    }
}
