// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

using System;
using System.IO;

namespace StellarDotnetSdk.Xdr;

// === xdr source ============================================================

//  typedef IntUnion IntUnion2;

//  ===========================================================================
public class IntUnion2
{
    public IntUnion2()
    {
    }

    public IntUnion2(IntUnion value)
    {
        InnerValue = value;
    }

    public IntUnion InnerValue { get; set; }

    public static void Encode(XdrDataOutputStream stream, IntUnion2 encodedIntUnion2)
    {
        IntUnion.Encode(stream, encodedIntUnion2.InnerValue);
    }

    public static IntUnion2 Decode(XdrDataInputStream stream, int maxDepth)
    {
        if (maxDepth <= 0)
            throw new IOException("Maximum decoding depth reached");
        maxDepth -= 1;
        var decodedIntUnion2 = new IntUnion2();
        decodedIntUnion2.InnerValue = IntUnion.Decode(stream, maxDepth);
        return decodedIntUnion2;
    }

    public static IntUnion2 Decode(XdrDataInputStream stream)
    {
        return Decode(stream, XdrDataInputStream.DefaultMaxDepth);
    }
}
